import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  GUIDES,
  LEARN,
  OG_IMAGE,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/how-to-practice-guitar-improvisation`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to practice guitar improvisation";

const DESCRIPTION =
  "Practice guitar improvisation with constraint drills, call and response, and phrases that land on chord tones over a 12-bar blues in A, recorded every session.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Practice improvising", href: "/how-to-practice-guitar-improvisation" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/how-to-practice-guitar-improvisation"),
  title: "How to Practice Guitar Improvisation | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Do I need to know music theory to improvise?",
    a: "You need a little, and you can learn it as you go. One scale shape, the names of the chords you are playing over, and where the third of each chord sits will carry you a long way. Everything else on this page is ear and habit, built by playing over chords and listening back.",
  },
  {
    q: "Which scale should I improvise with first?",
    a: "The minor pentatonic, in the first position. Five notes, two per string, and every note sounds acceptable over a blues or a minor rock progression. That freedom lets you put your attention on rhythm, phrasing and landing notes, which are what make improvising sound like music.",
  },
  {
    q: "How do I stop sounding like I am just running up and down a scale?",
    a: "Play fewer notes and leave space. Use short phrases with rests between them, repeat a phrase and change one thing, and end each phrase on a chord tone instead of wherever the scale happened to run out. The constraint drills on this page force all three.",
  },
  {
    q: "Is it OK to use licks I have learned?",
    a: "Yes. Learned phrases are vocabulary, the same way borrowed words are for a speaker. The skill is placing them over the right chord and changing them: start a lick on a different beat, shorten it, or end it on a different chord tone, and it becomes yours.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/advanced",
  "/how-to-practice-guitar-scales",
  "/learn-guitar-fretboard-notes",
  "/record-guitar-practice-on-phone",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/how-to-practice-guitar-improvisation"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: CANONICAL,
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: { "@id": "https://suedeai.ai/founder#person" },
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function HowToPracticeGuitarImprovisationPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/how-to-practice-guitar-improvisation"
        crumbs={CRUMBS}
        title={
          <>
            How to practice improvising,{" "}
            <em className="font-display italic text-peach">
              one constraint at a time.
            </em>
          </>
        }
        dek="Improvising is a string of small choices made in time. Practice the choosing: fewer notes, more space, and every phrase ending somewhere on purpose."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To practice guitar improvisation, pick one key, one backing track and
          one scale position, then play over it with deliberate limits: two
          notes only, one string only, short phrases with rests between them,
          and phrases that answer each other in call and response. Then learn
          where each chord&apos;s tones sit, especially the third, and practice
          ending phrases on them. A 12-bar blues in A with the A minor
          pentatonic scale is the classic place to start. Record every session
          and keep one phrase you like.
        </p>

        <p>
          This page is about making up phrases over chords: what to practice so that improvising stops sounding like a scale played in order. How to practice the scale itself, until the shape plays smoothly in time, is covered in the <Link href="/how-to-practice-guitar-scales">scale practice guide</Link>.
        </p>

        <h2>Improvising is choosing, so practice choosing</h2>

        <p>
          The usual obstacle in improvising is not a lack of notes. It is too
          many options at once. With a whole scale under your
          fingers and no plan, the hand falls back on its habit, which is
          running the scale up and down. Constraints remove options so you can
          hear the effect of the ones that are left. Every drill below takes
          something away on purpose.
        </p>

        <h2>Set up: one key, one backing, one position</h2>

        <p>
          Start with a 12-bar blues in A. The form, one chord per bar, is:
        </p>

        <ul>
          <li>Bars 1 to 4: A7, A7, A7, A7.</li>
          <li>Bars 5 to 8: D7, D7, A7, A7.</li>
          <li>Bars 9 to 12: E7, D7, A7, E7.</li>
        </ul>

        <p>
          Use any 12-bar blues backing track in A, or record yourself playing
          the chords for three choruses on your phone and loop it. Start around
          70 to 90 BPM.
        </p>

        <p>
          The scale is A minor pentatonic in its first position, at fret 5:
          A, C, D, E and G.
        </p>

        <ul>
          <li>String 6: fret 5 (A) and fret 8 (C).</li>
          <li>String 5: fret 5 (D) and fret 7 (E).</li>
          <li>String 4: fret 5 (G) and fret 7 (A).</li>
          <li>String 3: fret 5 (C) and fret 7 (D).</li>
          <li>String 2: fret 5 (E) and fret 8 (G).</li>
          <li>String 1: fret 5 (A) and fret 8 (C).</li>
        </ul>

        <p>
          Stage 5 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link> covers both the twelve-bar form and a first solo built on four-bar phrases.
        </p>

        <h2>The constraint drills</h2>

        <p>
          Give each drill at least three full choruses before moving on. The
          point is to stay inside the limit long enough to find what it makes
          possible.
        </p>

        <ol>
          <li>
            <strong>Two notes only.</strong> Use A (string 1, fret 5) and C
            (string 1, fret 8). With pitch taken away, rhythm is the only
            variable: long notes, short notes, repeated notes, silence. Many
            great blues phrases are two notes and a strong rhythm.
          </li>
          <li>
            <strong>One string only.</strong> Play the scale notes on string 2
            or string 3 alone, sliding between them. Phrases on one string move
            horizontally along the neck, which breaks the box habit.
          </li>
          <li>
            <strong>Play two bars, rest two bars.</strong> Silence is part of
            the phrase. Forcing the rest also gives you time to hear the chord
            change coming and plan the next idea.
          </li>
          <li>
            <strong>Call and response.</strong> Play a short phrase as a
            question, then answer it with a phrase that starts the same way and
            ends differently. Many memorable solos are built from pairs like
            this.
          </li>
          <li>
            <strong>Repeat and vary.</strong> Play one phrase, then repeat it
            with one change: a different rhythm, a different last note, or the
            same shape over the next chord. Developing one idea through a whole
            chorus sounds composed, even when it is not.
          </li>
        </ol>

        <h2>Land on the chord, not just in the key</h2>

        <p>
          The minor pentatonic works over the whole blues, which is why it is
          usually the first scale players learn for soloing. What makes a phrase sound like it
          knows the chord changes is where it ends. The strongest landing note
          is usually the third of the chord of the moment:
        </p>

        <ul>
          <li>
            Over A7, the third is C sharp, at string 3 fret 6. The scale&apos;s
            C at fret 5 is one fret below it, so sliding or bending from C to C
            sharp is the classic blues resolution.
          </li>
          <li>Over D7, the third is F sharp, at string 2 fret 7.</li>
          <li>Over E7, the third is G sharp, at string 4 fret 6.</li>
        </ul>

        <p>
          Practice ending every phrase on one of those notes, timed to arrive
          as the chord does. The <Link href="/advanced/blues-landing-notes">Land on the Chord Tone drill</Link> gives you phrases that resolve to each third over A7, D7 and E7 and checks every note with your microphone, then asks you to improvise your own phrase to the same landing note.
        </p>

        <p>
          When the thirds are comfortable, the <Link href="/advanced/guide-tones">Guide Tones drill</Link> takes the same idea into a ii-V-I in C, playing only the third and seventh of each chord so you hear how they move by half steps. Stage 6 of the curriculum calls this Target the Third.
        </p>

        <h2>Approach notes and enclosures</h2>

        <p>
          Once you know your target, you can decorate the arrival. An enclosure
          plays the note above the target, then the note below it, then the
          target itself, so the line sounds like it is homing in. The <Link href="/advanced/enclosures">Enclosures drill</Link> practices four targets, C sharp, F sharp, A and E, each approached from above and below. Use it on the landing notes from the blues above.
        </p>

        <h2>Add one color note</h2>

        <p>
          Adding a single note to a scale you already own is the quickest route
          to a new sound. Over an A minor chord, add F sharp, the major sixth,
          and the pentatonic takes on the brighter minor color of the Dorian
          mode. The <Link href="/advanced/dorian-color">Add the Dorian Sixth drill</Link> gives you a phrase with that note in it, then asks you to improvise with it and resolve to A or C rather than to the F sharp itself.
        </p>

        <h2>Steal phrases by ear</h2>

        <p>
          Every improviser&apos;s vocabulary comes from other players. Pick a
          short phrase from a recording you love, four to eight notes, and find
          it on the neck by ear: hear it, sing it, find the first note, then the
          next. The <Link href="/advanced/phrase-by-ear">Eight-Note Phrase by Ear drill</Link> trains the process one note at a time. Then use the repeat-and-vary drill on it until it fits your own playing.
        </p>

        <h2>A 25-minute improvisation session</h2>

        <ol>
          <li>
            <strong>5 minutes, vocabulary:</strong> one phrase learned by ear,
            or one drill from the Advanced Lab.
          </li>
          <li>
            <strong>5 minutes, today&apos;s constraint:</strong> one of the
            five drills above, over the backing, for at least three choruses.
          </li>
          <li>
            <strong>5 minutes, landing notes:</strong> every phrase ends on the
            third of the current chord.
          </li>
          <li>
            <strong>7 minutes, free improvisation, recorded:</strong> no rules
            except to keep going through mistakes.
          </li>
          <li>
            <strong>3 minutes, listen back:</strong> mark the best phrase and
            write down how it starts. Start tomorrow&apos;s free improvisation
            by playing it.
          </li>
        </ol>

        <p>
          Recording is what turns this into progress you can hear. The <Link href="/record-guitar-practice-on-phone">phone recording guide</Link> covers placement and what to listen for, and a monthly comparison of the same 12 bars shows changes in phrasing that are hard to notice day to day. The note names behind the landing notes are covered in the <Link href="/learn-guitar-fretboard-notes">fretboard notes guide</Link>.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
