import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  GUIDES,
  LEARN,
  OG_IMAGE,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/how-to-play-barre-chords`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to play barre chords and the F chord";

const DESCRIPTION =
  "Play the F barre chord cleanly: index placement, arm weight instead of a thumb squeeze, a four-step path from Fmaj7 to full F, and the E and A shapes up the neck.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Barre chords and the F chord", href: "/how-to-play-barre-chords" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/how-to-play-barre-chords"),
  title: "How to Play Barre Chords and the F Chord | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "How long does it take to learn barre chords?",
    a: "Expect weeks of short daily practice rather than days, and expect the F chord at fret 1 to come last. The four-step path on this page lets you play songs with a smaller F along the way, so the weeks are spent playing music instead of waiting for one chord.",
  },
  {
    q: "Is it OK to play the small F instead of the full barre?",
    a: "Yes. The four-string F (xx3211) and the five-string version (x33211) are both real F major chords, and plenty of songs sound better with them. Learn the full barre as well, because the same E shape becomes every major chord up the neck once you can hold it.",
  },
  {
    q: "Will lighter strings make barre chords easier?",
    a: "Lighter strings need less force, so yes, and a professional setup that lowers the action and the nut slots often makes an even bigger difference. If chords at fret 1 feel much harder than the same shape at fret 5, the setup is worth checking.",
  },
  {
    q: "Why does my thumb hurt when I play barre chords?",
    a: "Usually because the thumb is squeezing the neck to supply the pressure. Move the thumb lower behind the neck, roughly behind the middle finger, and let the weight of your arm pull the fingers into the strings. Pain that stays after rest, or spreads to the wrist or forearm, is a reason to stop and get it checked.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/how-to-change-chords-faster",
  "/learn-guitar-fretboard-notes",
  "/guitar-finger-pain",
  "/tempo",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/how-to-play-barre-chords"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: CANONICAL,
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: { "@id": "https://suedeai.ai/founder#person" },
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function HowToPlayBarreChordsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/how-to-play-barre-chords"
        crumbs={CRUMBS}
        title={
          <>
            Barre chords and the F chord,{" "}
            <em className="font-display italic text-peach">
              without the death grip.
            </em>
          </>
        }
        dek="A barre chord is leverage, not strength. Put the index finger in the right place, let your arm do the pressing, and build the F chord in four steps."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To play a barre chord, lay your index finger straight across the
          strings just behind the fret, rolled slightly onto its thumb-side
          edge, and let the weight of your arm pull the fingers into the neck
          instead of squeezing with your thumb. For the F chord (133211), the
          index only has to sound strings 6, 2 and 1, because the other fingers
          cover the rest. Build up to it in four steps: Fmaj7, a four-string F,
          a five-string F, then the full barre. Check every chord string by
          string, and practice the full shape higher up the neck first, where it
          is easier, before bringing it down to fret 1.
        </p>

        <p>
          Fingerings below list frets from string 6 (low E) to string 1 (high
          E), with x for a string you do not play and 0 for an open string.
        </p>

        <h2>Why the F chord stops so many players</h2>

        <p>
          F is usually the first chord where one finger has to hold down several
          strings at once, and it arrives at fret 1, right next to the nut, where the strings have
          the least room to flex and take the most force to press. Most
          players try it with the open-chord technique they already have:
          pressing harder with the fingertip and squeezing with the thumb. That
          produces a sore thumb and dead strings, and it is why the barre feels
          like a strength problem. Stage 5 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link> opens with a lesson called Barre Is Leverage, Not Strength, and that is the right frame.
        </p>

        <h2>What actually needs to be pressed</h2>

        <p>
          The full F major chord is 133211:
        </p>

        <ul>
          <li>Index finger barred across all six strings at fret 1.</li>
          <li>Middle finger on string 3, fret 2.</li>
          <li>Ring finger on string 5, fret 3.</li>
          <li>Pinky on string 4, fret 3.</li>
        </ul>

        <p>
          The ring, pinky and middle fingers fret strings 5, 4 and 3. So the
          barre only has to sound three strings: string 6, string 2 and string
          1. Knowing that changes where you put your attention. You do not need
          even pressure along the whole finger. You need it at the very end
          (string 1), near the middle crease (string 2), and at the base
          (string 6).
        </p>

        <p>
          The creases of the index finger are the usual reason a string dies.
          If string 2 or 1 thuds, slide the finger a few millimeters toward or
          away from the headstock, or move the whole barre slightly up or down
          across the strings so the crease falls between strings instead of on
          one.
        </p>

        <h2>Leverage instead of squeeze</h2>

        <ul>
          <li>
            <strong>Index close to the fret.</strong> Right behind the fret
            wire, not in the middle of the space. The closer it is, the less
            force a clean note needs.
          </li>
          <li>
            <strong>Roll the index onto its edge.</strong> Turn it slightly so
            the harder, thumb-side edge of the finger meets the strings instead
            of the soft flat pad.
          </li>
          <li>
            <strong>Thumb low and loose.</strong> Place it on the back of the
            neck roughly behind the middle finger, not hooked over the top. It
            balances; it does not clamp.
          </li>
          <li>
            <strong>Let the arm do it.</strong> With the elbow relaxed at your
            side, let the weight of the arm draw the fingers back into the
            strings, as if gently pulling the neck toward you. On an electric
            with a strap, or a guitar braced against your body, this supplies
            most of the pressure.
          </li>
          <li>
            <strong>Use the minimum.</strong> Press until every string sounds,
            then ease off until one starts to buzz, then add back just enough.
            That is the pressure the chord needs.
          </li>
        </ul>

        <h2>The four-step path to F</h2>

        <ol>
          <li>
            <strong>Fmaj7 (xx3210).</strong> Ring finger on string 4 fret 3,
            middle on string 3 fret 2, index on string 2 fret 1, string 1 open.
            No barre at all, and it gets the fingers used to the F shape.
          </li>
          <li>
            <strong>Four-string F (xx3211).</strong> The same shape, but the
            index now flattens across strings 2 and 1 at fret 1. This is a
            small barre, two strings wide, and a complete F major chord.
          </li>
          <li>
            <strong>Five-string F (x33211).</strong> Add the bass: ring finger
            on string 5 fret 3, pinky on string 4 fret 3, middle on string 3
            fret 2, index barring strings 2 and 1 at fret 1.
          </li>
          <li>
            <strong>Full F (133211).</strong> Extend the index across all six
            strings so it also frets string 6 at fret 1.
          </li>
        </ol>

        <p>
          Move to the next step only when the current one rings clean four times
          in a row from a cold start. In the meantime, use the step you have in
          your songs. Every one of them is an F chord.
        </p>

        <h2>Start higher, then slide down</h2>

        <p>
          The full barre shape is easier around fret 5, where the strings flex
          more easily under the finger and the frets sit closer together. Play the same shape at fret 5 (577655) and you
          have A major. Once it rings, move it down one fret at a time: A flat
          at fret 4, G at 3, F sharp at 2, and F at 1. Each step shows you
          exactly which string fails first as the shape gets harder.
        </p>

        <h2>Check it string by string</h2>

        <p>
          Strum the chord once, then pick each string from 6 to 1. Fix only the
          first string that fails, then check again. Common culprits: string 2 or string 1 under an index crease, string 3
          when the middle finger collapses flat, and string 2 touched by the
          underside of the middle finger.
          Arching the middle, ring and pinky fingers more steeply clears the
          strings under them.
        </p>

        <h2>The E shape and the A shape</h2>

        <p>
          The F chord is the E shape: an open E major chord moved up one fret
          with the index barre playing the role of the nut. Move it anywhere and
          the root on string 6 names the chord, so the E shape at fret 3 is G
          and at fret 8 is C. Lift the middle finger and you have the minor
          version: F minor is 133111.
        </p>

        <p>
          The second barre shape is the A shape, with its root on string 5. B
          flat major is x13331: index barre at fret 1, and the ring finger
          flattened across strings 4, 3 and 2 at fret 3. B major is the same
          shape at fret 2, x24442. The minor version comes from the open A minor
          shape: B minor is x24432, with the index barre at fret 2, middle on
          string 2 fret 3, ring on string 4 fret 4, and pinky on string 3 fret 4.
        </p>

        <p>
          With those two shapes, you can play every major and minor chord,
          placing the root on string 6 or string 5. The <Link href="/advanced/movable-shape-roots">first movable shape drill</Link> trains exactly that placement, and the <Link href="/learn-guitar-fretboard-notes">fretboard notes guide</Link> covers the note names on both strings and how these shapes fit into the CAGED system. Stage 6 of the curriculum, Whole Neck, builds both shapes in five positions.
        </p>

        <h2>Changing into F</h2>

        <p>
          C (x32010) to F (133211) has an anchor. The ring finger is on string 5
          at fret 3 in both chords, so it stays down. The middle finger moves
          from string 4 to string 3, still at fret 2, the pinky drops onto string
          4 at fret 3, and the index lays flat across fret 1. Practice it with
          one-minute changes and the techniques in the <Link href="/how-to-change-chords-faster">chord change guide</Link>, then put the change on a ladder with the <Link href="/tempo">tempo ladder builder</Link>.
        </p>

        <h2>A ten-minute barre session</h2>

        <ol>
          <li>
            <strong>2 minutes, squeeze and release:</strong> form the barre
            shape at fret 5. At 60 BPM on the <Link href="/practice">metronome</Link>, press for four beats, then release to light contact for four beats, without lifting off the strings.
          </li>
          <li>
            <strong>2 minutes, string check:</strong> pick each string and fix
            the first one that fails.
          </li>
          <li>
            <strong>2 minutes, slide down:</strong> fret 5 to fret 1, one fret
            at a time, checking at each stop.
          </li>
          <li>
            <strong>3 minutes, changes:</strong> C to F one-minute changes,
            using whichever F step you are on.
          </li>
          <li>
            <strong>1 minute:</strong> a song with an F in it.
          </li>
        </ol>

        <p>
          Barre practice brings a new kind of soreness at the side of the index
          finger and the base of the thumb. A little tenderness is expected.
          Aching in the wrist or forearm is a signal to stop, and the <Link href="/guitar-finger-pain">finger and hand pain guide</Link> covers the warning signs and the setup changes that make barre chords easier.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
