import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  ARTICLE_AUTHOR,
  GUIDES,
  LEARN,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/how-to-practice-guitar-scales`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to practice guitar scales so they turn into music";

const DESCRIPTION =
  "Practice guitar scales as music: learn one shape cold, then add sequences, thirds, a drone, rhythm and chord tones, with tempos and a 15-minute daily plan.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Practice scales", href: "/how-to-practice-guitar-scales" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/how-to-practice-guitar-scales"),
  title: "How to Practice Guitar Scales So They Sound Like Music | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // No `images` key: Next attaches the colocated opengraph-image.tsx card
    // only when the page leaves `images` unset.
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Which guitar scales should I learn first?",
    a: "The minor pentatonic in its first position, then the major scale. The minor pentatonic is five notes, two per string, and it works over blues and a great deal of rock. The major scale is the reference every other scale and mode is described against, so it pays back everything you learn after it.",
  },
  {
    q: "How fast should I play scales?",
    a: "Only as fast as you can play them evenly, in time, with every note clean. Start with eighth notes at 60 BPM and climb in steps of about 5 BPM, moving up only after a few clean passes in a row. A ladder from 60 to 100 BPM in eighth notes is a solid first target.",
  },
  {
    q: "Should I use alternate picking for scales?",
    a: "Yes, as your default: down, up, down, up, regardless of string changes. It keeps the picking hand in time and makes speed possible later. Practice legato as a separate skill, picking the first note on each string and hammering the rest.",
  },
  {
    q: "How do I know a scale is learned?",
    a: "Play it cold, at the start of a session, with no warm-up. Start it from any note, play it in a sequence, and make a four-bar phrase with it over a chord. If all of that works without looking at a diagram, the scale is learned. If any part fails, that part is tomorrow's practice.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/tempo",
  "/how-to-practice-guitar-improvisation",
  "/learn-guitar-fretboard-notes",
  "/advanced",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/how-to-practice-guitar-scales"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${CANONICAL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: ARTICLE_AUTHOR,
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function HowToPracticeGuitarScalesPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/how-to-practice-guitar-scales"
        crumbs={CRUMBS}
        title={
          <>
            How to practice scales so they{" "}
            <em className="font-display italic text-peach">turn into music.</em>
          </>
        }
        dek="Up and down a scale is a finger exercise. Sequences, intervals, a drone, rhythm and chord tones are what turn the same notes into music."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To practice guitar scales so they become music, learn one shape until
          you can play it cold, in time, with alternate picking. Then stop
          playing it only up and down. Play it in sequences and in thirds, play
          it over a drone so you hear what each note does, play it in rhythms
          with rests, and pick out the chord tones inside it. Five to fifteen
          minutes a day on one scale, done this way, builds more usable playing
          than an hour of running every shape you know.
        </p>

        <p>
          This page is about the scale itself: how to practice a shape so it plays like music instead of an exercise. Using scales to make up phrases over chords is covered in the <Link href="/how-to-practice-guitar-improvisation">improvisation guide</Link>.
        </p>

        <h2>Why up and down does not transfer</h2>

        <p>
          Music almost never runs a scale from its lowest note to its highest
          in even notes. It skips, repeats, changes direction, rests and lands
          on particular notes. A scale practiced only as a straight run trains
          one path through the notes, and that path rarely appears in a song.
        </p>

        <p>
          There is also no target in it. In their 1993 study of violinists at a
          music academy in Berlin, K. Anders Ericsson, Ralf Krampe and Clemens
          Tesch-R&ouml;mer described deliberate practice as activity designed
          specifically to improve performance, done with full concentration,
          with feedback on the result. Running a scale you already know, while
          thinking about something else, has none of those features. Every step
          below adds a specific target and a way to check it.
        </p>

        <h2>Step 1: one shape, cold</h2>

        <p>
          Choose one shape and one key. Two good starting points:
        </p>

        <ul>
          <li>
            <strong>A minor pentatonic, first position.</strong> A, C, D, E and
            G, two notes per string between frets 5 and 8: frets 5 and 8 on
            strings 6, 2 and 1, and frets 5 and 7 on strings 5, 4 and 3.
          </li>
          <li>
            <strong>G major, three notes per string.</strong> G, A, B, C, D, E
            and F sharp. The <Link href="/advanced/three-note-legato-g-major">Three Notes a String drill</Link> plays it across four strings, string 6 at frets 3, 5 and 7, string 5 at 3, 5 and 7, then strings 4 and 3 at 4, 5 and 7, and checks every note with your microphone.
          </li>
        </ul>

        <p>
          Every major scale follows the same pattern of whole steps (W, two
          frets) and half steps (H, one fret): W W H W W W H. C major is C, D,
          E, F, G, A, B, with no sharps or flats. G major is G, A, B, C, D, E, F
          sharp.
        </p>

        <p>
          Play the shape in eighth notes with strict alternate picking, down,
          up, down, up, against the <Link href="/practice">metronome</Link> at 60 BPM. Climb in steps of about 5 BPM, moving up only after three clean passes in a row, and drop back a step when a pass breaks. The <Link href="/tempo">tempo ladder builder</Link> lays out the steps. Stage 4 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link>, The First Scale, runs this exact ladder from 60 to 100 BPM.
        </p>

        <p>
          The shape is learned when you can play it cold, first thing in a
          session, with your eyes off the fretboard. Until then, the other steps
          will be about finding notes instead of making music.
        </p>

        <h2>Step 2: sequences</h2>

        <p>
          A sequence plays the scale in short overlapping groups, so the line
          moves forward while changing direction. In C major, groups of three
          go C D E, D E F, E F G, F G A, and on up the scale. Groups of four go C
          D E F, D E F G, E F G A. Play each sequence ascending, then descending
          (C B A, B A G, A G F).
        </p>

        <p>
          Sequences break the single straight path, force your hands to start
          from every note in the shape, and produce lines that already sound
          like melodic runs. Keep them at a tempo where the picking stays
          strictly alternate, which is usually slower than your straight scale
          tempo at first.
        </p>

        <h2>Step 3: intervals</h2>

        <p>
          Play the scale in thirds: each note followed by the note two scale
          steps above it. In C major that is C E, D F, E G, F A, G B, A C, B D.
          Thirds are the building blocks of chords and of a lot of melody, so
          this one exercise makes the scale sound musical immediately. When
          thirds are smooth, try fourths (C F, D G, E A) and sixths (C A, D B, E
          C).
        </p>

        <h2>Step 4: hear it against a drone</h2>

        <p>
          A note only has a musical meaning against something else. Let the
          open A string ring and play the A minor scale (A, B, C, D, E, F, G) over
          it slowly, holding each note for a few seconds. Notice which notes
          sound settled (A, C and E, the notes of an A minor chord), which pull
          toward a neighbor, and which add tension or color.
        </p>

        <p>
          Then change one note. The <Link href="/advanced/aeolian-vs-dorian">One Root, Two Modes drill</Link> plays A Aeolian and then A Dorian, which differ only in the sixth, F in Aeolian and F sharp in Dorian. Hearing that one note change against a fixed root is how modes stop being a theory topic and start being sounds you can choose.
        </p>

        <h2>Step 5: rhythm, not just notes</h2>

        <p>
          Play the same shape in different rhythms: quarter notes, eighth notes,
          triplets, then a long-short pattern such as a dotted eighth followed by
          a sixteenth. Then add rests. Play four notes and rest for four beats,
          or start the run on beat 2 instead of beat 1.
        </p>

        <p>
          Finish this step by making a four-bar phrase from the shape: a short
          idea in bar 1, a repeat with a change in bar 2, something longer in bar
          3, and a held note in bar 4. That is the moment a scale becomes a
          melody.
        </p>

        <h2>Step 6: the chord tones inside the scale</h2>

        <p>
          Every scale contains chords, and every chord is a set of notes you can
          find inside the shape. In C major, the C chord is C, E and G, D minor
          is D, F and A, and G7 is G, B, D and F. Play those notes inside the
          scale shape, low to high, as arpeggios.
        </p>

        <p>
          The <Link href="/advanced/ii-v-i-arpeggios">ii-V-I Arpeggios drill</Link> spells Dm7 (D, F, A, C), G7 (G, B, D, F) and Cmaj7 (C, E, G, B) note by note in one position. Knowing where the chord tones sit inside a shape is what lets you aim a line at the chord of the moment instead of wandering through the key.
        </p>

        <h2>Step 7: connect positions</h2>

        <p>
          One shape covers four or five frets. To use the whole neck, learn the
          neighboring shape and practice the shift between them: play up one
          shape and slide on one string into the next. The <Link href="/learn-guitar-fretboard-notes">fretboard notes guide</Link> shows how the five CAGED shapes map the major scale positions across the neck, and Stage 6 of the curriculum, Whole Neck, teaches the major scale in five positions and how to connect them.
        </p>

        <h2>A fifteen-minute scale session</h2>

        <ol>
          <li>
            <strong>3 minutes:</strong> today&apos;s shape cold, once, at your
            current ladder tempo. Note whether it held.
          </li>
          <li>
            <strong>4 minutes:</strong> one sequence, ascending and descending,
            against the click.
          </li>
          <li>
            <strong>3 minutes:</strong> thirds, or the drone, alternating by day.
          </li>
          <li>
            <strong>3 minutes:</strong> chord tones inside the shape.
          </li>
          <li>
            <strong>2 minutes:</strong> one four-bar phrase from the shape,
            recorded. Keep the best one.
          </li>
        </ol>

        <p>
          On a short day, do the cold pass and the four-bar phrase. That keeps
          both ends of the job alive: the shape your hands know, and the music
          you make with it. When you want to take those phrases over chord
          changes, the <Link href="/how-to-practice-guitar-improvisation">improvisation guide</Link> picks up from here.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
