import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  GUIDES,
  LEARN,
  OG_IMAGE,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/coming-back-to-guitar`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "Coming back to guitar after years away: a 30-day restart";

const DESCRIPTION =
  "Restart guitar after a long break: get the instrument set up, rebuild your fingertips in short sessions, record a fresh baseline, and finish one song in 30 days.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Coming back to guitar", href: "/coming-back-to-guitar" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/coming-back-to-guitar"),
  title: "Coming Back to Guitar After Years Away: A 30-Day Restart | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Will I have to start from scratch?",
    a: "Rarely. Chord shapes, songs you once knew well and your sense of how the instrument works tend to come back much faster than they took to learn. What fades most is the physical layer: calluses, finger strength, speed and stamina. Rebuild that gently and you skip most of the beginner stage.",
  },
  {
    q: "How long until I am back to where I was?",
    a: "It depends on how far you went and how long you were away, so measure it instead of guessing. Record a baseline in your first week and the same take on day 30. The comparison tells you how fast you are coming back, and it usually shows more progress than your sense of it does.",
  },
  {
    q: "Should I buy a new guitar?",
    a: "Get the one you have restrung and set up first. A setup by a guitar technician fixes most of what makes an old guitar hard to play, for a fraction of the cost of a new one. If you still want a new guitar after a month of playing, you will know much better what you want from it.",
  },
  {
    q: "Should I take lessons again?",
    a: "Lessons help most once you know what you want to work on. Spend the first two weeks finding your level and recording a baseline, then choose: the GuitarHub curriculum for a structured path from wherever you land, or a teacher for live feedback on the specific thing your recordings point at.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/start",
  "/breakthrough",
  "/guitar-finger-pain",
  "/how-to-memorize-songs-on-guitar",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/coming-back-to-guitar"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: CANONICAL,
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: { "@id": "https://suedeai.ai/founder#person" },
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function ComingBackToGuitarPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/coming-back-to-guitar"
        crumbs={CRUMBS}
        title={
          <>
            Coming back to guitar after years away:{" "}
            <em className="font-display italic text-peach">a 30-day restart.</em>
          </>
        }
        dek="Most of what you learned is still there. The guitar needs a setup, your fingertips need two weeks, and the month needs one finish line."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To come back to guitar after years away, start with the instrument:
          new strings, a tuning check, and a setup if the strings sit high.
          Then rebuild your fingertips with two short sessions a day for the
          first two weeks, record a fresh baseline of where you are now, and
          pick one song to finish by day 30. Relearning is faster than learning
          the first time, so most of the restart is physical: calluses, finger
          strength and stamina. Measure the month with a recording on day 1 and
          day 30, not with your memory of how you used to play.
        </p>

        <h2>Week zero: the guitar</h2>

        <p>
          A guitar that sat in a case or a closet for years usually needs
          attention before it is pleasant to play. Changes in humidity and
          temperature can move the neck, and old strings lose their tone and
          corrode.
        </p>

        <ul>
          <li>
            <strong>Restring it.</strong> Fresh strings sound brighter, stay in
            tune better, and are kinder to soft fingertips than corroded ones.
            If you used heavy strings before, this is a good moment to go a
            gauge lighter.
          </li>
          <li>
            <strong>Tune and recheck.</strong> Use the <Link href="/practice">guitar tuner</Link> on all six strings, E, A, D, G, B, E from low to high. New strings stretch, so expect to retune several times in the first few days.
          </li>
          <li>
            <strong>Check the action.</strong> If the strings sit noticeably
            higher above the frets than you remember, or notes buzz, the neck
            has probably moved. A setup by a guitar technician adjusts it and is one of the best-value
            repairs an old guitar can get.
          </li>
          <li>
            <strong>Electrics and pickups.</strong> Crackling volume or tone
            knobs usually need cleaning. On an acoustic with a pickup, replace
            the battery.
          </li>
        </ul>

        <h2>Days 1 to 7: fingertips and a fresh baseline</h2>

        <p>
          Your calluses are gone, and your hands remember shapes your fingertips
          can no longer hold for long. The classic restart mistake is a three-hour first session that ends in blisters and a week off. Play 10
          to 15 minutes, two or three times a day, and stop when a fingertip
          feels hot or stings. The <Link href="/guitar-finger-pain">finger pain guide</Link> covers how calluses rebuild and the warning signs that mean stop.
        </p>

        <p>
          In the first week, record a baseline. Three short takes on your phone,
          each without warming up on it first:
        </p>

        <ol>
          <li>A song you used to know, as far as you can get without stopping.</li>
          <li>The open chords you remember, each strummed and then picked string by string.</li>
          <li>Any scale or riff your hands still know.</li>
        </ol>

        <p>
          These takes are the start line for this restart, not a verdict on the
          years away. Do not compare them with your memory of how you used to
          play, which is reliably more flattering than any recording. Compare
          them with day 30. The <Link href="/record-guitar-practice-on-phone">phone recording guide</Link> covers how to set up so the two takes are comparable.
        </p>

        <h2>What comes back fast, and what takes longer</h2>

        <p>
          Relearning is faster than learning. In his memory experiments
          published in 1885, Hermann Ebbinghaus found that relearning material
          he had already forgotten took less time than learning it the first
          time, and he named the difference savings. Returning players
          experience the same thing on the instrument: a chord shape or a song
          that took weeks the first time often returns in a few sessions.
        </p>

        <p>
          What takes longer is the physical layer. Fingertips need a couple of
          weeks of short daily sessions, and speed and stamina rebuild over the
          month. Plan for that. Spend the first two weeks on material you
          already know at comfortable tempos, and save the hardest passage you
          used to play for after the calluses are back.
        </p>

        <h2>Find your level, then pick one finish line</h2>

        <p>
          Your level now may not match your level when you stopped, and it may
          be uneven: chords intact, lead playing rusty, reading forgotten. The <Link href="/start">find your level page</Link> asks three questions and opens at the right place, and the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link> lets you jump straight to the stage that matches, from open chords and strumming to barre chords and the whole neck.
        </p>

        <p>
          Then choose one finish line for days 8 to 30. One song, played start
          to finish without stopping, at a tempo you choose, recorded on day 30.
          One finish line beats a plan to get everything back at once, because
          it gives every session the same target. The <Link href="/breakthrough">30-day breakthrough planner</Link> turns that finish line into four weeks of practice focuses, and if you cannot tell what is holding the song back, the <Link href="/diagnose">practice plateau diagnostic</Link> names the most likely cause.
        </p>

        <h2>Days 8 to 30: run the loop</h2>

        <p>
          The restart month uses the same four stages as the <Link href="/method">GuitarHub method</Link>: baseline, isolate, reconnect, prove.
        </p>

        <ul>
          <li>
            <strong>Baseline:</strong> the first-week recording of your chosen
            song shows where it breaks.
          </li>
          <li>
            <strong>Isolate:</strong> take the first place it breaks, two beats
            either side, and slow it down until it is clean every time. The <Link href="/tempo">tempo ladder builder</Link> sets the steps back up to song tempo.
          </li>
          <li>
            <strong>Reconnect:</strong> put the repaired spot back into the
            section, then the whole song.
          </li>
          <li>
            <strong>Prove:</strong> on day 30, record the same song the same way
            and compare it with the baseline.
          </li>
        </ul>

        <h2>Play from memory before you look</h2>

        <p>
          For songs you used to know, try to play them from memory before you
          look up the chords or tab. Struggling to recall is not wasted time. In
          a 2006 study, Henry Roediger and Jeffrey Karpicke found that students
          who practiced recalling a passage remembered more of it a week later
          than students who spent the same time rereading it. On guitar, the
          attempt to retrieve a song strengthens it more than reading it again.
          Look it up after the attempt, fix what you missed, and try again from
          memory the next day. The <Link href="/how-to-memorize-songs-on-guitar">guide to memorizing songs</Link> goes further into learning the form instead of the finger path.
        </p>

        <h2>Fit it into an adult week</h2>

        <p>
          If work and family filled the time before, they are still there. Protect one longer session a week and keep the
          other days short. The <Link href="/guitar-practice-schedule">practice schedule guide</Link> builds a week that survives a busy Wednesday, and the <Link href="/session">practice session builder</Link> turns the minutes you have on a given day into timed blocks. One line per session in the <Link href="/log">practice evidence log</Link> shows you, within a couple of weeks, which days actually happen.
        </p>

        <h2>Restart mistakes to skip</h2>

        <ul>
          <li>
            <strong>A marathon first session.</strong> Blisters cost you more
            days than the session gained.
          </li>
          <li>
            <strong>Starting with your hardest old song at full speed.</strong>{" "}
            Start with the easiest song you remember and earn the hard one by
            week three.
          </li>
          <li>
            <strong>Buying gear before playing.</strong> A setup and new strings
            first. Play a month, then decide what you actually want.
          </li>
          <li>
            <strong>Trying to recover everything at once.</strong> One finish
            line for the month. Everything else waits for month two.
          </li>
        </ul>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
