/**
 * The learning catalog the browser needs: lesson and module ids, order, type,
 * minutes, and a four-number summary of each practice spec.
 *
 * Client components and the progress, access and sync logic they run read
 * this instead of lib/learning/curriculum.ts. The full curriculum (titles,
 * summaries, practice targets, the voice track's prose, every demo asset) stays
 * in server modules, and pages pass client components only the fields they
 * render. data/catalog.json is generated by `npm run learning:catalog` from
 * the curriculum and checked against it by tests/learning-catalog.test.ts.
 */
import catalog from "./data/catalog.json" with { type: "json" };
import { decodeStageTwoAsset, type StageTwoAsset } from "./stage-two.ts";
import type { LessonType, TrackId } from "./models.ts";

/** What progress, readiness and cloud-evidence checks read from a practice spec. */
export interface CatalogPractice {
  passScore: number;
  targetCount: number;
  /** Beat of the final target: an attempt shorter than this cannot be complete. */
  lastBeat: number;
  revision?: number;
  completionMinimumBPM?: number;
}
export interface CatalogLesson { id: string; type: LessonType; minutes: number; practice?: CatalogPractice }
export interface CatalogModule { id: string; lessons: CatalogLesson[] }
export interface CatalogLevel { id: string; stage?: number; access?: "free" | "paid"; modules: CatalogModule[] }
export interface LearningCatalog {
  schemaVersion: 1;
  tracks: Record<TrackId, CatalogLevel[]>;
  /** Lessons with authored instruction, in index order, with what the browser checks about each. */
  guided: CatalogGuidedLesson[];
  /** Raw authored assets that gate a guided reflection (manual changes and chord studies) only. */
  stageEvidenceAssets: Record<string, unknown>;
}
export interface CatalogGuidedLesson { id: string; selfCheck?: true; quiz?: unknown; stageEvidenceAssetIds?: string[] }
export interface CatalogEntry { lesson: CatalogLesson; module: CatalogModule; level: CatalogLevel }

/** The lazily loaded guitar search index (data/lesson-search-guitar.json). */
export interface LessonSearchEntry { id: string; title: string; summary: string; type: LessonType; minutes: number; mic: boolean; moduleId: string; moduleName: string; levelName: string }
export interface LessonSearchIndex { schemaVersion: 1; lessons: LessonSearchEntry[] }

export const learningCatalog = catalog as unknown as LearningCatalog;

const entries = Object.fromEntries((Object.keys(learningCatalog.tracks) as TrackId[]).map(track => [
  track,
  learningCatalog.tracks[track].flatMap(level => level.modules.flatMap(module => module.lessons.map(lesson => ({ lesson, module, level })))),
])) as Record<TrackId, CatalogEntry[]>;
const byId = Object.fromEntries((Object.keys(entries) as TrackId[]).map(track => [track, new Map(entries[track].map(entry => [entry.lesson.id, entry]))])) as Record<TrackId, Map<string, CatalogEntry>>;

/** Every lesson in curriculum order, like `allLessons` in curriculum.ts. */
export function catalogLessons(track: TrackId): readonly CatalogEntry[] { return entries[track]; }
export function catalogLesson(track: TrackId, lessonId: string): CatalogEntry | undefined { return byId[track].get(lessonId); }

/** The decoded asset behind one of a lesson's `stageEvidenceAssetIds`. */
export function stageEvidenceAsset(id: string): StageTwoAsset {
  const raw = learningCatalog.stageEvidenceAssets[id];
  const asset = raw && typeof raw === "object" ? decodeStageTwoAsset(id, raw as Record<string, unknown>) : null;
  if (!asset) throw new Error(`Missing stage evidence asset: ${id}`);
  return asset;
}
