import type { Metadata } from "next";
import Link from "next/link";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, STRUMLY, TOOLS } from "@/lib/site";

const CANONICAL = "https://guitarhub.org/guitar-practice-plateau";
const PUBLISHED = "2026-08-29";

const HEADLINE = "Why guitar practice plateaus, and how to break one";

const DESCRIPTION =
  "You practiced for years and stopped improving. Six habits cause a guitar plateau. Learn how to recognize each one in your own playing and what to change.";

export const metadata: Metadata = {
  title: "Why Guitar Practice Plateaus and What Fixes It | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description:
      "Six causes of a guitar plateau, the tell that reveals each one in your own playing, and the fix to run this week.",
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

// The Organization and Person nodes are defined once, in app/layout.tsx, under
// these @ids. Referencing them rather than restating them keeps one entity per
// @id across the site instead of minting a duplicate author on every guide.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

// One Article node. No FAQPage: the headings on this page are statements, not
// questions, and a FAQPage whose Q&A does not appear verbatim in the visible
// text is a structured-data violation. Add one only if a real Q&A block lands
// here later.
const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: HEADLINE,
  description: DESCRIPTION,
  // Google lists `image` as a recommended Article property, and without it
  // the page is not eligible for an Article rich result. Every route serves
  // the 1200x630 card generated by app/opengraph-image.tsx.
  image: "https://guitarhub.org/opengraph-image",
  datePublished: PUBLISHED,
  dateModified: PUBLISHED,
  inLanguage: "en-US",
  mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
  author: { "@id": JASON_PERSON_ID },
  publisher: { "@id": SUEDE_ORG_ID },
};

// Ordered deliberately: the diagnostic first, because that is where the page
// ends, then the tool and the two guides that pick up where the causes stop.
// Pulled from the route registry so the titles and blurbs cannot drift.
const RELATED_HREFS = [
  "/diagnose",
  "/tempo",
  "/deliberate-practice-guitar",
  "/guitar-practice-routine-intermediate",
];

const RELATED = RELATED_HREFS.flatMap((href) =>
  [...TOOLS, ...GUIDES].filter((entry) => entry.href === href),
);

export default function GuitarPracticePlateauPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        title={
          <>
            Why guitar practice plateaus,{" "}
            <em className="font-display italic text-peach">
              and how to break one.
            </em>
          </>
        }
        dek="You have played for years and the playing stopped changing. More hours will not fix that on their own. What the hours contain is the thing to change."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          Guitar practice plateaus when the difficulty of what you play stops
          rising while the hours keep going in. Adding time to a session that
          contains nothing difficult produces more of the same playing. Six
          causes are worth ruling out first: practicing what already sounds
          good, never playing at performance tempo, never hearing yourself from
          outside your own head, having no single target you could pass or fail,
          starting new material before the last piece is finished, and working
          around a technique problem instead of repairing it. Each one has a
          tell you can check in your own playing and a fix you can start this
          week.
        </p>

        <h2>A plateau is a repetition problem, not a volume problem</h2>

        <p>
          The first stretch of playing improves on its own. Almost everything is
          new, so difficulty arrives without being scheduled: every chord shape,
          every strum pattern, every song is something you could not do last
          month. Then it stops arriving. You know enough shapes to get through
          most of what you attempt, and a session fills up with things you can
          already play at the speed you can already play them.
        </p>

        <p>
          What improves is what is currently failing. Practice changes the
          playing at the edge where you can just barely hold it together, and
          nowhere else. A session with no failure in it maintains you at exactly
          the level you walked in with, which is why a plateau survives more
          practice. The hour was not wasted. It was spent on the part that was
          already finished.
        </p>

        <p>
          Read the six statements below. Any that are true of your last three
          sessions are causes, not moods.
        </p>

        <ul>
          <li>You practiced things you can already play.</li>
          <li>You never reached the tempo the music is actually played at.</li>
          <li>You have not heard a recording of yourself in the last month.</li>
          <li>You cannot name one thing that would count as finished.</li>
          <li>You started something new before the last thing was done.</li>
          <li>
            You changed a fingering, a voicing, or an arrangement to avoid a
            movement you cannot make.
          </li>
        </ul>

        <h2>The six causes, the tell, and the fix</h2>

        <h3>You practice what already sounds good</h3>

        <p>
          Comfortable playing is the default, because it is the only part of
          practice that sounds like music. Nobody schedules it. It happens
          because starting from something familiar is easier than starting from
          something broken, and once the guitar is out and the sound is good,
          stopping to work on something that sounds bad takes a decision.
        </p>

        <p>
          <strong>The tell.</strong> Your practice sounds good from the next
          room. If someone walking past would think you were playing rather than
          working, most of the hour was maintenance.
        </p>

        <p>
          <strong>The fix.</strong> Put one thing in the session you cannot yet
          do: a passage that breaks down by the third bar, a change you miss
          more often than you land. Ten minutes of it, first, while your hands
          and your attention are fresh. Keep the comfortable playing. Move it to
          the end, where it belongs.
        </p>

        <h3>You never play at performance tempo</h3>

        <p>
          Slow practice is correct, and it is also where plateaus hide. A
          passage rehearsed only well under tempo never meets the problems that
          appear at full speed. The picking hand stiffens. The fretting hand
          starts arriving late. A shift that was comfortable becomes a jump.
          Those are not faster versions of the slow-tempo problems. They are
          different problems, and they exist only above a certain speed.
        </p>

        <p>
          <strong>The tell.</strong> You know exactly how the passage feels at
          your practice tempo and have no idea how it feels at the real one,
          because you have not tried it there in weeks.
        </p>

        <p>
          <strong>The fix.</strong> Play it at the target tempo once at the
          start of every session, badly if that is what happens. The failed
          attempt tells you which bar is the actual problem, and it is usually
          one bar rather than the whole passage. Then work in steps below it and
          return to the top before you stop. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> lays those steps out
          for a passage you choose.
        </p>

        <h3>You never hear yourself from outside</h3>

        <p>
          You cannot hear your own timing while you are producing it. Your ears
          are busy predicting what your hands are about to do, and the
          prediction smooths over the gaps. A recording removes the prediction.
        </p>

        <p>
          The first one is unpleasant. It is also the most information you will
          get all week: a transition that rushes, a chord that never fully
          rings, a fill landing half a beat late, dynamics that sit flat from
          the first bar to the last. None of that is audible from behind the
          guitar.
        </p>

        <p>
          <strong>The tell.</strong> You describe your sessions in feelings.
          Good days and bad days, rather than a specific thing that got better.
        </p>

        <p>
          <strong>The fix.</strong> Record one take a week on your phone. One
          attempt, no edit, no second try. Listen once and write down the first
          thing that is wrong. That becomes the difficult ten minutes of the
          next session. The recording matters less than the comparison: a take
          from four weeks ago is the only honest evidence that anything changed.
        </p>

        <h3>You have no single target you could pass or fail</h3>

        <p>
          &ldquo;Get better at soloing&rdquo; cannot be finished, so it cannot
          be practiced. It has no end and no test, which makes every session
          equally defensible and none of them aimed. A target that works is one
          a stranger could score. &ldquo;Play the intro at full tempo, twice
          through, no stops, no buzzes&rdquo; is a target. &ldquo;Improve my
          rhythm&rdquo; is a subject heading.
        </p>

        <p>
          That is the whole difference between{" "}
          <Link href="/deliberate-practice-guitar">deliberate practice</Link>{" "}
          and playing something again. The first has a standard it can fail.
        </p>

        <p>
          <strong>The tell.</strong> Asked what you are working on, you name a
          subject rather than a passage. Scales. Timing. Theory. Speed.
        </p>

        <p>
          <strong>The fix.</strong> Write one sentence containing a specific
          piece of music, a specific tempo, and a specific standard for clean,
          with a date on it four weeks out. One sentence, not five.
        </p>

        <h3>You start new material before the last piece is finished</h3>

        <p>
          Beginning is the enjoyable part. The first days on a new song produce
          visible progress every time you sit down, because everything in it is
          new. The end of a piece is the opposite: slow, unglamorous, four bars
          that still fall apart while the rest is fine. There is always another
          song more interesting than those four bars.
        </p>

        <p>
          A shelf of nearly finished pieces feels like a repertoire and behaves
          like nothing. Under any pressure, a room, a camera, another player,
          the unfinished parts are precisely what breaks, because they were
          never taken past the point where they hold.
        </p>

        <p>
          <strong>The tell.</strong> You can start twenty songs and play none of
          them all the way through at tempo.
        </p>

        <p>
          <strong>The fix.</strong> Finish one. Pick the closest to done, decide
          in advance what finished means, and start nothing new until it holds.
          The <Link href="/readiness">song readiness score</Link> checks a song
          against the parts that break under pressure, which is usually not the
          part you have been practicing.
        </p>

        <h3>You worked around a technique problem instead of repairing it</h3>

        <p>
          Every guitarist carries some technique debt. The barre that never
          rings, so you play the three-string version. The pinky you stopped
          using early and never brought back. The alternate picking that turns
          into all downstrokes once the tempo rises. The shift you avoid by
          choosing another position. Each substitution was reasonable at the
          time, and each one let you keep playing.
        </p>

        <p>
          The debt stays invisible while the workaround holds. It becomes
          visible when a piece requires the thing you routed around, and by then
          it is not one piece. It is a category of music you quietly stopped
          attempting.
        </p>

        <p>
          <strong>The tell.</strong> There are songs you decided you do not
          like, and they happen to require the same movement.
        </p>

        <p>
          <strong>The fix.</strong> Name the movement and practice it away from
          any song, a few minutes at the start of the session. The barre on its
          own. The pinky on its own. Isolated technique is dull, and it is the
          only way the debt gets paid. Chord changes respond particularly well
          to isolation, and the Strumly guide to{" "}
          <a href={STRUMLY.chordTransitions}>smoother chord transitions</a>{" "}
          takes one change apart.
        </p>

        <h2>Change one thing, not six</h2>

        <p>
          Six causes is a diagnosis, not a task list. Rebuilding an entire
          routine in a week fails the way a crash diet fails: none of it
          survives a bad Tuesday. Pick the cause whose tell was most obviously
          true, and change one thing about how the session runs.
        </p>

        <ol>
          <li>
            Record a baseline take before you change anything. One attempt, at
            the tempo you can currently manage.
          </li>
          <li>
            Choose the single cause whose tell you recognized fastest. The fast
            recognition is usually the honest one.
          </li>
          <li>
            Change one thing about the session, and write the change down so you
            cannot renegotiate it midweek.
          </li>
          <li>Run the changed session for a week without adjusting it again.</li>
          <li>
            Record the same take at the end of the week and listen to the two
            back to back.
          </li>
        </ol>

        <p>
          If the two recordings sound the same, the change was the wrong one or
          it was too small. That is worth knowing, and it took a week to find
          out. If you need a shape for the rest of the week around that one
          change, the Strumly guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers the ordering.
        </p>

        <h2>How you will know the plateau broke</h2>

        <p>
          Not by feeling better. Feeling is the least reliable instrument in the
          room, and it moves with sleep, mood, and how the guitar happens to be
          set up that day.
        </p>

        <p>
          The plateau broke when something you could not play a month ago is
          something you can play now, at tempo, on demand, with a recording at
          each end to prove it. That is a small claim. It is also a real one,
          and it repeats: a month later, on the next thing you could not do.
        </p>

        <p>
          If more than one of the six tells was true and you cannot decide where
          to start, the{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> asks a short
          set of questions and names the part of your practice that stopped
          producing change. It takes a couple of minutes, needs no account, and
          nothing leaves your browser.
        </p>
      </Article>
    </>
  );
}
