import test from "node:test";
import assert from "node:assert/strict";
import nativeEvidence from "../contracts/learning-evidence.json" with { type: "json" };
import { parseLearningAttempt, type LearningAttempt } from "../lib/learning-account/contracts.ts";
import { mergeAccountProgress, mergeAccountReading, syncLessonMap } from "../lib/learning-sync/evidence.ts";
import { allLessons, getLesson } from "../lib/learning/curriculum.ts";
import { getInstructionQuiz } from "../lib/learning/instruction-index.ts";
import { emptyProgress, emptyReadingQuizProgress, parseProgress } from "../lib/learning/progress.ts";

const id = "a0000000-0000-4000-8000-000000000099";
const createdAt = "2026-09-15T00:00:00.000Z";
function importProgress(attempt: LearningAttempt) {
  return mergeAccountProgress(emptyProgress(attempt.track), emptyReadingQuizProgress(attempt.track), [attempt]);
}

test("the native completion contract retains every fixture and declares no divergence", () => {
  assert.equal(nativeEvidence.version, 1);
  assert.equal(nativeEvidence.fixtures.length, 27);
  assert.equal(new Set(nativeEvidence.fixtures.map(fixture => fixture.case)).size, 27);
  assert.deepEqual(nativeEvidence.knownDivergences, []);
});
// Vendored verbatim from guitarhub-ios/contracts/learning-evidence.json. The
// expected outcomes are generated by native LearningEvidence, not web helpers.
for (const fixture of nativeEvidence.fixtures) {
  test(`native completion fixture: ${fixture.case}`, () => {
    const attempt = parseLearningAttempt(fixture.attempt, syncLessonMap);
    const actual = importProgress(attempt).lessons[attempt.lessonId]?.assessment === "ready";
    assert.equal(actual, fixture.expectedCompleted, fixture.case);
  });
}

test("a manual reading override cannot import answers or replace a valid reading result", () => {
  const lessonId = "g-l1-m3-04";
  const quiz = getInstructionQuiz(lessonId)!;
  const reflection = parseLearningAttempt({ version: 1, id, track: "guitar", lessonId, kind: "reading", createdAt,
    practiceSeconds: null, exerciseRevision: null, source: "selfReported", disposition: "reflection",
    assessment: "ready", score: null, bpm: null,
    details: { localSource: "readingQuiz", readingQuizAttempt: { id, lessonId, createdAt,
      answers: Object.fromEntries(quiz.items.map(item => [item.id, { optionIndex: item.correctOptionIndex, answeredAt: createdAt }])) } },
  }, syncLessonMap);
  const override = parseLearningAttempt({ ...reflection, disposition: "manualOverride" }, syncLessonMap);
  const reading = emptyReadingQuizProgress("guitar");
  assert.deepEqual(mergeAccountReading(reading, [override]), reading);
  assert.equal(importProgress(override).lessons[lessonId], undefined);
  const valid = mergeAccountReading(reading, [reflection]);
  assert.equal(importProgress(reflection).lessons[lessonId].assessment, "ready");
  assert.deepEqual(mergeAccountReading(valid, [override]), valid);
});

const opening = getLesson("guitar", "g-l1-m1-02")!.lesson;
const versioned = allLessons("guitar").find(({ lesson }) => lesson.practiceSpec?.revision !== undefined)!.lesson;
for (const lesson of [opening, versioned]) {
  const spec = lesson.practiceSpec!;
  const currentRevision = spec.revision ?? null;
  const revisions = [...new Set([(currentRevision ?? 0) + 1, currentRevision, null])];
  test(`local results for ${lesson.id} require exact current revision and preserve earlier evidence`, () => {
    for (const revision of [...revisions, undefined]) {
      const record = { updatedAt: createdAt, practiceSeconds: 600, source: "measured", assessment: "ready",
        score: 100, bpm: spec.bpm, practiceSpecRevision: revision };
      const raw = JSON.stringify({ version: 1, track: "guitar", lessons: { [lesson.id]: record },
        measuredAttempts: [{ id, lessonId: lesson.id, record }] });
      const progress = parseProgress(raw, "guitar", [lesson.id]);
      const expected = (revision ?? null) === currentRevision ? "ready" : "repeat";
      assert.equal(progress.lessons[lesson.id]?.assessment, expected, `revision ${revision}`);
      assert.equal(progress.measuredAttempts?.length, 1);
      assert.equal(progress.measuredAttempts[0].record.assessment, expected);
      assert.equal(progress.measuredAttempts[0].record.score, 100);
      assert.equal(progress.measuredAttempts[0].record.practiceSpecRevision ?? null, revision ?? null);
    }
  });
  test(`imported results for ${lesson.id} require exact current revision and preserve earlier evidence`, () => {
    for (const revision of revisions) {
      const attempt = parseLearningAttempt({ version: 1, id, track: "guitar", lessonId: lesson.id,
        kind: "microphone", createdAt, practiceSeconds: 600, exerciseRevision: revision,
        source: "measured", disposition: "scored", assessment: "ready", score: 100, bpm: spec.bpm,
        details: { practiceScore: { targetCount: spec.targets.length, matchedTargets: spec.targets.length, passed: true } },
      }, syncLessonMap);
      const progress = importProgress(attempt);
      const expected = revision === currentRevision ? "ready" : "repeat";
      assert.equal(progress.lessons[lesson.id].assessment, expected, `revision ${revision}`);
      assert.equal(progress.measuredAttempts?.length, 1);
      assert.equal(progress.measuredAttempts[0].record.assessment, expected);
      assert.equal(progress.measuredAttempts[0].record.score, 100);
      assert.equal(progress.measuredAttempts[0].record.practiceSpecRevision ?? null, revision);
    }
  });
}
