import type { Metadata } from "next";
import Link from "next/link";
import Article, { type RelatedLink } from "@/components/Article";
import { GUIDES, OG_IMAGE, SITE_URL, STRUMLY, TOOLS } from "@/lib/site";

const CANONICAL = `${SITE_URL}/why-cant-i-play-guitar-fast`;
const PUBLISHED = "2026-08-29";

const HEADLINE =
  "Why you cannot play it fast yet: five causes of a guitar speed ceiling";

const DESCRIPTION =
  "A guitar speed ceiling has five common causes. Find the tell that reveals each one in your own playing, the fix for it, and how to build the climb.";

export const metadata: Metadata = {
  title: "Why You Can't Play Guitar Fast Yet | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description:
      "Speed is not a separate skill. Five causes of a stuck tempo, the tell for each, and why slow practice only helps when the slow motion is the same motion.",
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

// The Organization and Person nodes are defined once, in app/layout.tsx, under
// these @ids. Referenced rather than restated, so the site keeps one entity per
// @id instead of minting a duplicate author on every guide.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

// One Article node. No FAQPage: every heading here is a statement, and a
// FAQPage whose Q&A does not appear verbatim in the visible text is a
// structured-data violation.
const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: HEADLINE,
  description: DESCRIPTION,
  // Google lists `image` as a recommended Article property, and without it the
  // page is not eligible for an Article rich result. Every route serves the
  // 1200x630 card generated by app/opengraph-image.tsx.
  image: `${SITE_URL}/opengraph-image`,
  datePublished: PUBLISHED,
  dateModified: PUBLISHED,
  inLanguage: "en-US",
  mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
  author: { "@id": JASON_PERSON_ID },
  publisher: { "@id": SUEDE_ORG_ID },
};

/**
 * Related links resolve from the route registry by href, so a title or blurb
 * edited in `lib/site.ts` propagates here. `FALLBACKS` covers a route that
 * exists on disk but is not in the registry yet; the registry entry wins the
 * moment one appears, so this cannot go stale in the other direction.
 */
const FALLBACKS: Record<string, RelatedLink> = {
  "/practicing-guitar-with-a-metronome": {
    href: "/practicing-guitar-with-a-metronome",
    title: "Practicing guitar with a metronome",
    blurb:
      "How to use a click so it shows you where your timing goes, instead of covering it up.",
  },
};

const RELATED_HREFS = [
  "/tempo",
  "/practicing-guitar-with-a-metronome",
  "/guitar-practice-plateau",
  "/how-to-practice-guitar-effectively",
] as const;

const RELATED: readonly RelatedLink[] = RELATED_HREFS.map(
  (href) =>
    [...TOOLS, ...GUIDES].find((entry) => entry.href === href) ??
    FALLBACKS[href],
);

export default function WhyCantIPlayGuitarFastPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        eyebrow="GuitarHub guide"
        title={
          <>
            Why you cannot play it{" "}
            <em className="font-display italic text-peach">fast yet.</em>
          </>
        }
        dek="A speed ceiling is a diagnosis, not a verdict. Five causes, the tell that reveals each one in your own playing, and the fix that moves it."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          You cannot play it fast yet because the motion you are repeating is
          not the motion the tempo needs. A speed ceiling is almost never a
          talent limit or a rep-count problem. It is one of five things:
          practicing at a tempo where the motion has already broken down,
          tension in the fretting or picking hand, the two hands landing at
          different moments, speeding up a passage that is not yet accurate, and
          never spending time in the narrow band just below the ceiling. Each
          has a tell you can check today and a different fix. More of the same
          practice will not move any of them.
        </p>

        <h2>A ceiling is a fact about the motion</h2>

        <p>
          Fast playing is the same motion made smaller, timed more exactly, and
          produced with less effort. Nothing new appears at 160 BPM that was
          absent at 90; what changes is the tolerance. A finger that travels an
          inch has time for that at 90 and does not at 160, so a motion that fit
          before stops fitting and the passage breaks in the same place every
          time. A ceiling belongs to a motion, not to a player: you might run
          sixteenths at 130 in one riff and stall at 95 in another.
        </p>

        <h2>Why &ldquo;just play it slow&rdquo; is incomplete</h2>

        <p>
          Slow practice helps only if the slow motion is the same motion, and
          often it is not. At a comfortable tempo you have time to lift fingers
          high, press harder than the note needs, re-aim the pick, and gather
          yourself before the hard bar. None of that fits at speed, and
          repetition builds whatever you repeat: slow practice full of large
          motions builds a motion with a low ceiling, and builds it well.
        </p>

        <p>Two questions make slow practice honest.</p>

        <ul>
          <li>
            <strong>
              Is this a smaller version of the fast motion, or a different one?
            </strong>{" "}
            Fingers stay near the strings, the pick keeps its angle and its
            short distance, and nothing pauses before the difficult bar. If any
            of that is untrue, you are rehearsing something that cannot
            scale.
          </li>
          <li>
            <strong>Does the shape survive one step up?</strong> Add a small
            increase and watch the same list. If the fingers start flying or the
            wrist locks, the tempo you own is lower than the number you use.
          </li>
        </ul>

        <p>
          The click is what makes any of this measurable:{" "}
          <Link href="/practicing-guitar-with-a-metronome">
            practicing guitar with a metronome
          </Link>{" "}
          covers using one honestly, and{" "}
          <Link href="/how-to-practice-guitar-effectively">
            how to practice guitar effectively
          </Link>{" "}
          covers the rest of the session.
        </p>

        <h2>The five causes, the tell, and the fix</h2>

        <h3>1. You practice at a tempo where the motion is already wrong</h3>

        <p>
          <strong>The tell.</strong> You can name the tempo where it gets messy,
          and most of your repetitions happen within a few clicks of it, because
          that is where the passage feels like work.
        </p>

        <p>
          <strong>The fix.</strong> Find the tempo you own, as a measurement
          rather than an opinion: three passes in a row, cold, at the start of a
          session, no missed notes, no rushing, no mid-phrase recovery. A pass
          you saved is not a clean pass. Whatever survives is the bottom of your
          ladder, normally well below the number you called your tempo.
        </p>

        <h3>2. You are holding tension you cannot feel</h3>

        <p>
          Speed is the rate at which a motion can reverse. A finger pressing
          harder than the note needs has to stop pressing before it can leave; a
          locked hand has to be overcome before the pick can change direction.
          Tension caps how fast a motion turns around, and it accumulates.
        </p>

        <p>
          <strong>The tells.</strong>
        </p>

        <ul>
          <li>The forearm burns or the hand cramps within half a minute.</li>
          <li>The pick rotates in your fingers, or you regrip between phrases.</li>
          <li>
            Passes get worse across a set instead of better. Technique does not
            degrade over five repetitions; tension does.
          </li>
          <li>
            The note <em>after</em> the difficult bit lands late even though the
            difficult bit worked.
          </li>
        </ul>

        <p>
          <strong>The fix.</strong> Find your pressure floor: fret a note,
          release until it buzzes, add back the least pressure that clears it,
          and play there. Drop the volume too, since loud playing recruits
          tension in both hands. Scan where you have attention to spare: jaw,
          shoulder, fretting thumb, pick grip, breath. And end a repetition when
          the tension arrives rather than pushing to the end of the bar. Pushing
          through is a repetition of playing tense.
        </p>

        <h3>3. Your hands are not landing together</h3>

        <p>
          Each hand can be individually competent and jointly wrong. At a low
          tempo the window for arriving together is wide enough that nobody
          notices the gap; as the tempo climbs the window narrows and the gap
          does not. The sound is not wrong notes but a smear: the tail of the
          previous note under the new attack, or a muted click where the pick
          beat the finger.
        </p>

        <p>
          <strong>The tells.</strong>
        </p>

        <ul>
          <li>
            Slowly, every note is right. Fast, it is sloppy, and you cannot name
            which note is wrong.
          </li>
          <li>
            It is acceptable clean and unusable with gain. Distortion amplifies
            what happens between notes, which is where a sync problem lives.
          </li>
          <li>
            Picked passages break down while legato ones survive, or the
            reverse. The failure is in the join.
          </li>
        </ul>

        <p>
          <strong>The fix</strong> is to take the hands apart at the tempo you
          want, then rejoin them below it. Mute the strings and play the picking
          pattern alone at the target tempo: if it is uneven there, the problem
          is the pattern, not the sync. Then play the passage with no pick,
          hammering every note: if it is uneven here, the fretting hand is out of
          time. Put them together slowly enough to hear each attack separately.
          The tempo where you can hear the seam is where you can close it.
        </p>

        <p>
          One more test: start the passage on an upstroke. If it works one way
          and collapses the other, the pick direction was never decided. Where
          the join is between chord shapes, Strumly&apos;s guide to{" "}
          <a href={STRUMLY.chordTransitions}>smoother chord transitions</a>{" "}
          covers what the hands have to agree on.
        </p>

        <h3>4. The passage is not accurate yet</h3>

        <p>
          Speed does not produce accuracy. It removes the time you were quietly
          using to correct.
        </p>

        <p>
          <strong>The tell, and the most useful one here:</strong> watch{" "}
          <em>where</em> the errors land across four or five passes. A failure in
          the same place every time is a mechanical problem at that spot, and one
          of the three causes above will name it. A failure that moves means the
          passage is not learned yet. The two feel identical from inside the room
          and need different weeks.
        </p>

        <p>
          A second tell: you cannot say out loud which finger plays each note,
          where the shift happens, and which way each pick stroke goes. A passage
          that was never decided cannot be made automatic, because you play a
          slightly different one every time.
        </p>

        <p>
          <strong>The fix.</strong> Decide it — position, fingering, shift
          points, pick direction — and leave it alone for the week. Then take one
          pass at the comfortable tempo, no run-up. If you miss, the passage is
          still under construction, and that is this week&apos;s work.
        </p>

        <h3>5. You never spend time just under the ceiling</h3>

        <p>
          Two habits produce this and they look like opposites: living at the
          ceiling and nowhere else, so every repetition is a repetition of the
          passage failing, or living well below it and trying the song tempo once
          at the end of a session to see whether it has arrived.
        </p>

        <p>
          Both leave the same range empty, and that range does the work: from a
          few rungs under your best clean tempo up to it. Fast enough that the
          motion has to become efficient, slow enough that it stays correct.
        </p>

        <p>
          <strong>The tell.</strong> Your metronome has two numbers in it, the
          safe one and the song&apos;s one, and nothing between them has had a
          session of its own.
        </p>

        <p>
          <strong>The fix.</strong> Put most of a session&apos;s tempo work
          inside that band, and move its top one rung at a time. Which is what a
          ladder is.
        </p>

        <h2>The climb: capped steps, holds, and back-offs</h2>

        <p>
          A tempo ladder is the ordered set of tempos between the speed you own
          and the speed you want, one session per rung. The parts that are not a
          straight line are what make it hold.
        </p>

        <ul>
          <li>
            <strong>The first rung is a measurement, not practice.</strong> You
            are finding the fastest tempo you can play the passage three times
            cleanly in a row, cold. Start above it and every later rung is a
            guess.
          </li>
          <li>
            <strong>Steps are capped, not averaged.</strong> No rung asks for
            more than about a tenth of the tempo you are leaving, and never more
            than 10 BPM, because hands feel proportion rather than arithmetic.
          </li>
          <li>
            <strong>Some rungs repeat the previous tempo.</strong> Reaching a
            tempo once and owning it are different skills, and the second comes
            only from repetitions at a speed you reached.
          </li>
          <li>
            <strong>One ladder per passage, not per song.</strong> Three spots
            holding a song back is three ladders.
          </li>
        </ul>

        <h3>What a back-off rep is for</h3>

        <p>
          At least one session goes down on purpose. A back-off drops below the
          top tempo you reached and climbs back through the rungs you passed,
          inside one sitting. Three things happen there that a straight climb
          cannot produce.
        </p>

        <ul>
          <li>
            <strong>It finds the rung you skipped.</strong> A ladder climbed once
            leaves rungs you reached and never owned. Walking back up exposes the
            one that fails, and that tempo is what the next session works on.
          </li>
          <li>
            <strong>It turns a ceiling into a floor.</strong> A number you hit
            once, on a good day, after warming up, is a ceiling. A number you can
            arrive at from below, cold, is a floor, and the floor is what shows
            up when someone is listening.
          </li>
          <li>
            <strong>It removes the incentive to protect the number.</strong> Once
            the top tempo is something you re-earn, there is nothing to defend,
            and the quiet edits stop: the simplified voicing, the dropped note,
            the generous definition of clean.
          </li>
        </ul>

        <p>
          The <Link href="/tempo">tempo ladder builder</Link> writes that
          sequence out: enter the tempo you already play cleanly and the tempo
          you want, choose how many sessions to spend, and it returns the rungs
          in order with a pass condition on each. Where those sessions sit in a
          week is a separate question, and Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers it.
        </p>

        <h2>Two checks before you commit a month</h2>

        <p>
          Count the recording against a metronome instead of trusting the number
          in your head; chasing a tempo the record never played is an avoidable
          way to fail. And check that you are playing the same part, because fast
          playing on records is often the easy version: an open string where you
          are shifting, hammer-ons where you are picking every note.
        </p>

        <h2>What to do this week</h2>

        <ol>
          <li>
            Pick one passage, not a song: the bar or two that breaks, plus a beat
            either side. Measure its baseline cold, first thing in a session, and
            write the number down.
          </li>
          <li>
            Run the tells. Do the errors sit in one place or move? Is the fifth
            pass worse than the first? Does the picking pattern hold on muted
            strings?
          </li>
          <li>
            Build the ladder from that baseline to a target you can reach this
            month, not automatically the tempo on the record.
          </li>
          <li>
            At the end, record one pass at the top tempo against a recording
            made today. That comparison is the evidence.
          </li>
        </ol>

        <p>
          If nothing in your playing has moved for months, rather than this one
          passage, start with{" "}
          <Link href="/guitar-practice-plateau">
            why guitar practice plateaus
          </Link>
          . If you are not sure which it is, the{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> ends with a
          named blocker.
        </p>

      </Article>
    </>
  );
}
