import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, SITE_URL, STRUMLY } from "@/lib/site";

const CANONICAL = `${SITE_URL}/method`;
const PUBLISHED = "2026-08-29";

const TITLE = "The GuitarHub Method: A Four-Stage Practice Loop";
const DESCRIPTION =
  "Baseline, isolate, reconnect, prove: the four-stage loop GuitarHub runs on, what each stage asks, how to do it badly, and how you know you can move on.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Related links are pulled from the route registry by href so the titles and
 * blurbs stay in one place. Listed explicitly rather than filtered, because the
 * order below is a reading order, not the registry's order.
 */
const RELATED_HREFS = [
  "/how-to-practice-guitar-effectively",
  "/guitar-practice-plateau",
  "/guitar-practice-routine-intermediate",
  "/30-day-guitar-challenge",
] as const;

const RELATED = RELATED_HREFS.flatMap((href) =>
  GUIDES.filter((guide) => guide.href === href),
);

/**
 * Rendered as the visible Q&A section AND as the FAQPage nodes below, from this
 * one array. Schema.org requires the marked-up answer to appear on the page, so
 * generating both from the same source is the only way to guarantee it stays
 * true after an edit. Keep these plain strings: no links, no markup.
 */
const FAQS = [
  {
    q: "How long is one loop?",
    a: "Four weeks, one stage per week. That is the cadence the planner builds, and it is a default rather than a rule. The exit tests govern the handoff: a stage that meets its test on Tuesday hands off on Tuesday, and one that has not met its test has not finished.",
  },
  {
    q: "What do I need in order to record myself?",
    a: "A phone. A voice memo is enough to hear a dropped beat, a missed change, or a tempo that sags. GuitarHub does not upload, store, or listen to your recordings. The planner keeps only your goal and the actions you have checked, in your own browser.",
  },
  {
    q: "Does this replace a teacher?",
    a: "No. A good teacher can do the isolate stage for you in about a minute, which is most of what you are paying for. The loop is a structure for the other six days, and it makes lessons more useful. You arrive with a recording and a specific question.",
  },
  {
    q: "What if week four shows no change?",
    a: "Then you have learned something specific and cheap. Either the finish line was wrong for a month of work, or the isolate stage had no real target, or the fix was not reconnected under pressure. Each points at a different next month, and a clear negative result beats a feeling.",
  },
] as const;

// The canonical estate @ids, copied from app/layout.tsx. Referenced rather than
// redefined: the Organization and Person nodes are already declared once in the
// root layout, which renders on this page too.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: "The GuitarHub method: baseline, isolate, reconnect, prove",
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without
      // it the page is not eligible for an Article rich result. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: PUBLISHED,
      inLanguage: "en-US",
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

export default function MethodPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        eyebrow="The GuitarHub method"
        title={
          <>
            The loop: baseline, isolate, reconnect,{" "}
            <em className="font-display italic text-peach">prove.</em>
          </>
        }
        dek="One goal at a time, four stages, and an exit test for each one. This is the method the tools and guides on this site are built around."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          The GuitarHub method is a four-stage loop you run against one goal at a
          time: baseline, isolate, reconnect, prove. You record where you
          actually are. You cut the problem down to the smallest piece that still
          fails. You put that repaired piece back under the pressure of a full
          performance. Then you record the same thing again and compare the two
          takes. Each stage has an exit test, so you can tell when it is finished
          instead of guessing, and the last stage hands you the first stage of
          the next loop.
        </p>

        <p>
          It is a loop rather than a curriculum. The useful information arrives
          late. You cannot know which transition is costing you the song until
          you have played the song badly onto a recording. Run the stages out of
          order and you get the most common failure in adult practice: four
          weeks of honest work on the part that was not the problem.
        </p>

        <h2>Stage one: Baseline</h2>

        <p>
          Pick one finish line specific enough that a recording can settle it.{" "}
          <em>
            Play the song from the count-in to the last chord without stopping
          </em>{" "}
          is a finish line. <em>Get better at rhythm</em> is not. Then record one
          take: start to finish, no restarts, at a tempo you would actually
          attempt. Listen once, all the way through, and write down where it
          breaks.
        </p>

        <ul>
          <li>
            <strong>Done badly: warming up first.</strong> A baseline taken after
            twenty minutes on the hard part measures your best conditions, which
            you will not have in week four.
          </li>
          <li>
            <strong>Done badly: stopping when it goes wrong.</strong> The restart
            is the information. A take that survives to the end shows which
            failures cascade and which ones you play through.
          </li>
          <li>
            <strong>Done badly: keeping the best of eight takes.</strong> Best of
            eight is a ceiling. What the month has to move is the floor.
          </li>
        </ul>

        <p>
          <strong>The question this stage answers:</strong> where does this fall
          apart, and when? Not how good you are, which is a rating you can argue
          with. A timestamp is not.
        </p>

        <p>
          <strong>Move on when</strong> you can name the failure in one sentence
          containing a location. <em>The chorus-to-bridge change drops a
          beat.</em> If your sentence has no location in it, listen again. If you
          can hear that something is wrong but cannot place it, the{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> ends with a
          named blocker, which is the sentence this stage exists to produce.
        </p>

        <h2>Stage two: Isolate</h2>

        <p>
          Shrink the failure until it stops failing, along two axes at once. Cut
          the length, down to the smallest unit that still contains the problem,
          which for a transition is often one beat either side of the join. Cut
          the tempo, down to where you play it correctly on purpose rather than
          correctly by luck. Then repeat it until correct is boring, not until it
          is occasionally right. Occasionally right is what you already had.
        </p>

        <ul>
          <li>
            <strong>Done badly: playing the whole song slowly.</strong> That is
            the same problem at a lower speed, plus many repetitions of
            everything that was already fine.
          </li>
          <li>
            <strong>
              Done badly: snapping the tempo back after one clean repetition.
            </strong>{" "}
            One clean repetition is a coincidence until it repeats.
          </li>
          <li>
            <strong>Done badly: editing the problem away.</strong> Simplifying
            the voicing or switching to an easier fingering is a legitimate
            arrangement decision and a dishonest fix. Decide out loud which one
            you are making.
          </li>
        </ul>

        <p>
          <strong>The question this stage answers:</strong> what is the smallest
          change that fixes this?
        </p>

        <p>
          <strong>Move on when</strong> you can play the fragment correctly
          several times in a row, cold: first thing in a session, no run-up. Cold
          is the test. In performance the passage arrives unannounced, with your
          hands wherever the previous bar left them.
        </p>

        <p>
          Write the tempo down, or the next session starts from a guess. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> turns one passage into
          a starting speed, a target, and the steps between. For a join between
          chords, Strumly&apos;s guide to{" "}
          <a href={STRUMLY.chordTransitions}>smoother chord transitions</a>{" "}
          covers what to change while you are down there.
        </p>

        <h2>Stage three: Reconnect</h2>

        <p>
          Put the repaired fragment back and add the pressure you removed, one
          layer at a time: the bars either side, then the full section, then the
          full piece, then a click, then a backing track, then one take with no
          restarts, then a camera.
        </p>

        <p>
          This is the stage most players skip, and it is why a part works in
          practice and falls apart in the song. A fragment drilled in isolation
          comes with its own on-ramp: you know it is coming and your hand is
          already in position. In the piece it arrives with no warning, with your
          attention already moving to the next thing.
        </p>

        <ul>
          <li>
            <strong>Done badly: adding every layer at once.</strong> Straight
            from the isolated loop to a full take with a click and a camera. It
            falls apart, you decide the fix failed, and you go back to drilling
            the fragment, which was already fine.
          </li>
          <li>
            <strong>Done badly: never leaving the loop.</strong> The isolated
            fragment is now the part that feels good, so the week quietly becomes
            more of it.
          </li>
        </ul>

        <p>
          <strong>The question this stage answers:</strong> does the fix survive
          contact with the music around it?
        </p>

        <p>
          <strong>Move on when</strong> you can play the full section at a tempo
          where the whole thing survives and the repaired spot is no longer what
          breaks. It does not have to be the best part. It has to stop being the
          worst one.
        </p>

        <p>
          Where those layers sit in a week is a scheduling problem too.
          Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers building the week around them. For the session in front of
          you, the <Link href="/session">practice session builder</Link> turns
          the minutes you have and the failure you named into blocks that add
          up exactly, then points its largest block at the repair.
        </p>

        <h2>Stage four: Prove</h2>

        <p>
          Record the same thing you recorded in week one, the same way: same
          start and end point, same one-take rule, same tempo range, same point
          in a session. Then listen to both, in order, once through.
        </p>

        <p>
          The comparison only works if the conditions match. A cold single take
          in week one against take nine after a warm-up in week four proves only
          that take nine beats take one.
        </p>

        <ul>
          <li>
            <strong>Done badly: deciding from memory.</strong> Your memory of
            week one is generous. You have heard the improved version many more
            times since.
          </li>
          <li>
            <strong>Done badly: recording and never listening back.</strong> The
            file is not the evidence. The comparison is.
          </li>
          <li>
            <strong>Done badly: letting the finish line drift.</strong> A goal
            quietly rewritten mid-month to whatever now looks reachable will
            always be met.
          </li>
        </ul>

        <p>
          <strong>The question this stage answers:</strong> what changed, and can
          I hear it?
        </p>

        <p>
          <strong>Move on when</strong> you can state the change in a sentence a
          stranger could check by listening to both files.{" "}
          <em>The bridge transition no longer drops a beat</em> is a claim the
          recordings settle. <em>It feels smoother</em> is not. Then write down
          what is now the worst thing: that sentence is the finish line for the
          next loop.
        </p>

        <p>
          The <Link href="/readiness">song readiness score</Link> pressure-tests
          whether the finished version survives outside the practice chair.
          The <Link href="/log">practice evidence log</Link> keeps the tempo or
          clean-pass result beside the session that produced it, and withholds
          a direction until the same focus has enough sessions to support one.
        </p>

        <h2>Why the loop is closed</h2>

        <p>
          Each stage produces exactly what the next one consumes. That is what
          makes this a loop and not a list of good advice.
        </p>

        <ul>
          <li>
            <strong>Baseline produces the target.</strong> Without it, isolate is
            a guess, and the guess is reliably the part that is most enjoyable to
            play.
          </li>
          <li>
            <strong>Isolate produces a fragment that works.</strong> Without it,
            reconnect is playing the whole piece again and hoping.
          </li>
          <li>
            <strong>Reconnect produces a version that holds up.</strong> Without
            it, prove records a performance that collapses in the same place it
            always did.
          </li>
          <li>
            <strong>Prove produces the next baseline.</strong> The worst-thing
            sentence at the end of stage four is the finish line at the start of
            the next stage one.
          </li>
        </ul>

        <p>
          The underlying principle is not original to GuitarHub. Practice works
          when it targets a specific weakness at the edge of what you can
          currently do, with feedback on whether the attempt worked. That is
          usually called deliberate practice. What the loop adds is a shape, so{" "}
          <em>target a specific weakness</em> becomes a step you can tell you
          have finished. There is more on{" "}
          <Link href="/deliberate-practice-guitar">
            what that looks like at the instrument
          </Link>
          .
        </p>

        <h2>What the method leaves out</h2>

        <p>
          Three familiar measurements are missing on purpose. Each measures
          something real. None measures whether you can play.
        </p>

        <h3>Lesson collecting</h3>

        <p>
          Saving a lesson is not acquiring a skill, and new material is the
          cheapest thing available to acquire. Material enters when the loop asks
          for it. Once the isolate stage has produced the question{" "}
          <em>how do I get from this shape to that one without a gap</em>, a
          lesson answers a question you already have. Browsing a library first
          answers questions you never asked, and the pile grows faster than you
          can play it down.
        </p>

        <h3>Watch time</h3>

        <p>
          Hours watched measures attendance at somebody else&apos;s playing. The
          unit of progress here is a recording of yours, and no counter here
          tracks how long you spent. Watching is an input, and inputs are not
          evidence.
        </p>

        <h3>Streaks</h3>

        <p>
          A streak measures showing up, which is real and weak. You can run a
          sixty-day streak playing only what you already play well, and that is
          the more comfortable option, so a streak biases each session toward
          whatever is easiest to finish. The loop counts weeks that ended with
          evidence instead. A week without a recording produced no evidence,
          which is a fact about the week and not a verdict on you.
        </p>

        <h2>Common questions</h2>

        {FAQS.map((item) => (
          <Fragment key={item.q}>
            <h3>{item.q}</h3>
            <p>{item.a}</p>
          </Fragment>
        ))}

        <h2>Where to start</h2>

        <p>
          If you already know your finish line, build the four weeks. The{" "}
          <Link href="/breakthrough">30-day breakthrough planner</Link> turns one
          goal into a week-by-week sequence and names the evidence each week has
          to produce. It needs no account.
        </p>

        <p>
          If you do not know what to work on, start at the other end. The{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> ends with a
          named blocker, which is the input the baseline stage needs anyway.
        </p>
      </Article>
    </>
  );
}
