import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  GUIDES,
  LEARN,
  OG_IMAGE,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/how-to-practice-strumming`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to practice strumming and rhythm guitar";

const DESCRIPTION =
  "Practice strumming with a hand that never stops, counted eighths, five patterns in order and a click on beats 2 and 4, then move on to sixteenths and syncopation.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Practice strumming", href: "/how-to-practice-strumming" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/how-to-practice-strumming"),
  title: "How to Practice Strumming and Rhythm Guitar | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Why do I keep speeding up when I strum?",
    a: "Usually because the hand stops moving between strokes, so each stroke starts from rest and arrives early, or because a chord change pulls the strum forward. Keep the down-up motion going through every beat, including the strokes that miss the strings, and practice the change against a click until it lands on time.",
  },
  {
    q: "What is the most useful strumming pattern to learn first?",
    a: "After straight eighth notes, the pattern counted 1, 2-and, and-4-and: down, down-up, up-down-up, with the hand missing the strings on beat 3. It fits a wide range of songs in 4/4, and learning it teaches the skill every other pattern needs, which is keeping the hand moving through a stroke you do not play.",
  },
  {
    q: "Should I strum with a pick or my fingers?",
    a: "Either works. A thin to medium pick, roughly 0.5 to 0.7 millimeters, gives a bright, even strum and is easier for beginners to control. Strumming with the fingers gives a softer sound. Choose one for a month so the motion has a chance to settle.",
  },
  {
    q: "How do I work out the strumming pattern of a song?",
    a: "Count the beat out loud while the song plays, then listen for which strums land on the numbers and which land on the ands. Tap the pattern on your leg with the down-up motion going, and only then try it on the guitar. Many songs use one main pattern with small variations at the ends of phrases.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/practice",
  "/practicing-guitar-with-a-metronome",
  "/how-to-change-chords-faster",
  "/advanced",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/how-to-practice-strumming"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: CANONICAL,
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: { "@id": "https://suedeai.ai/founder#person" },
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function HowToPracticeStrummingPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/how-to-practice-strumming"
        crumbs={CRUMBS}
        title={
          <>
            How to practice strumming so{" "}
            <em className="font-display italic text-peach">the groove holds.</em>
          </>
        }
        dek="Rhythm guitar is a hand that never stops and a choice about which strokes touch the strings. Practice those two things and every pattern gets easier."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To practice strumming, keep your strumming hand moving down and up in
          a constant, even motion locked to the beat: down on every beat and up
          on every &ldquo;and&rdquo; between them. A strumming pattern is just a
          choice about which of those strokes hit the strings and which pass
          just above them. Count out loud, start at 60 to 70 BPM on a metronome,
          learn five patterns in order from straight quarter notes to
          syncopation, and record yourself to check that the beat holds through
          the chord changes.
        </p>

        <h2>The pendulum rule</h2>

        <p>
          Picture the strumming hand as a pendulum. In a song counted in eighth
          notes, it moves down on each number (1, 2, 3, 4) and up on each
          &ldquo;and&rdquo; between them, at an even speed, for the whole song.
          It never stops and never changes direction early.
        </p>

        <p>
          When a pattern leaves out a stroke, the hand still makes the motion,
          it just passes above the strings. These are ghost strums, and they are the central idea in rhythm guitar. They keep your
          place in the bar for you. A hand that stops between strokes has to
          restart from rest and guess when to come back in, which is a common source of rushing and dragging.
        </p>

        <p>
          Stage 3 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link> teaches this as its own module, Up and Down, with lessons on the hand that never stops and on ghost strums.
        </p>

        <h2>Count out loud</h2>

        <p>
          Say the count while you play: &ldquo;1 and 2 and 3 and 4 and.&rdquo;
          It feels clumsy for a few days and then becomes the fastest way to
          learn any pattern, because you can say where each stroke goes before
          your hand knows it. If you lose the count, you have found the spot to
          slow down.
        </p>

        <h2>Five patterns, in order</h2>

        <p>
          Learn these one at a time, each on a single chord first, then on a
          two-chord change. D is a downstroke, U is an upstroke, and a dash is a
          ghost strum where the hand moves but misses the strings.
        </p>

        <ol>
          <li>
            <strong>Quarter notes: D - D - D - D -.</strong> One downstroke on
            each beat, with the up motion silent. This is the first strum in
            the curriculum, and Stage 2 checks it at sixteen bars at 80 BPM.
          </li>
          <li>
            <strong>Straight eighths: D U D U D U D U.</strong> Every stroke
            hits. Keep the downs and ups the same volume, then try accenting the
            downs.
          </li>
          <li>
            <strong>Down, down-up: D - D U D - D U.</strong> Counted 1, 2-and,
            3, 4-and. The first pattern with a ghost strum in it.
          </li>
          <li>
            <strong>The syncopated pattern: D - D U - U D U.</strong> Counted 1,
            2-and, and-4-and. Beat 3 is a ghost strum, so the upstroke on the
            &ldquo;and&rdquo; of 2 rings across it. This pattern fits a wide
            range of songs in 4/4.
          </li>
          <li>
            <strong>Sixteenths: 1 e and a.</strong> The hand moves twice as
            fast, down on 1 and &ldquo;and&rdquo;, up on &ldquo;e&rdquo; and
            &ldquo;a&rdquo;. Start with all sixteen strokes muted, then let only
            some of them sound. This is the engine of funk rhythm guitar.
          </li>
        </ol>

        <p>
          Songs in 3/4 and 6/8 use the same pendulum with a different count:
          &ldquo;1 and 2 and 3 and&rdquo; for 3/4, and &ldquo;1 2 3 4 5 6&rdquo;
          with a stress on 1 and 4 for 6/8. Stage 3 of the curriculum covers both
          meters.
        </p>

        <h2>The metronome: slow first, then move the click to 2 and 4</h2>

        <p>
          Set the <Link href="/practice">metronome</Link> between 60 and 70 BPM and play each pattern until you can do four bars in a row with every stroke on time and the count still in your mouth. Then raise the tempo in steps of 5 BPM. The <Link href="/tempo">tempo ladder builder</Link> lays out the steps for a specific passage.
        </p>

        <p>
          Once a pattern holds at 80 to 90 BPM, try this. Set the metronome to
          half your tempo and hear each click as beat 2 and beat 4 of the bar.
          At a song tempo of 100 BPM, set the click to 50. Now the click is the
          backbeat, the snare drum&apos;s job in most pop and rock, and you
          supply beats 1 and 3 yourself. It is harder, and it is much closer to
          playing with a drummer. The <Link href="/practicing-guitar-with-a-metronome">metronome guide</Link> covers more ways to use the click as a test instead of a crutch.
        </p>

        <h2>Accents make it groove</h2>

        <p>
          A pattern played at one even volume sounds mechanical. Once the
          strokes are in place, add accents: dig in slightly on beats 2 and 4 for
          a rock or pop backbeat feel, or on the first stroke of each bar for a
          folk feel. Change only how deep the pick goes into the strings, not
          the size or speed of the motion, or the timing will move with the
          volume.
        </p>

        <p>
          The <Link href="/advanced/pick-dynamics">Dynamics Without Rushing drill</Link> trains exactly this: alternating soft and loud bars while the microphone checks that the timing stays put.
        </p>

        <h2>Mechanics that keep the motion easy</h2>

        <ul>
          <li>
            <strong>Move from the wrist and forearm together</strong>, with a
            loose rotation like shaking water off your hand, not a stiff arm
            swing from the shoulder.
          </li>
          <li>
            <strong>Hold the pick loosely</strong>, just firmly enough that it
            does not fly out of your hand. A loose grip lets the pick give a
            little as it crosses the strings, which smooths the sound.
          </li>
          <li>
            <strong>Aim the strokes.</strong> Downstrokes usually favor the bass
            strings and upstrokes catch the top three or four. You rarely need
            all six strings on an upstroke.
          </li>
          <li>
            <strong>Strum over the sound hole or the neck pickup area.</strong>{" "}
            Strumming near the bridge sounds thinner and is harder to control.
          </li>
        </ul>

        <h2>Changing chords without breaking the strum</h2>

        <p>
          The strumming hand is the timekeeper, so it never waits for the
          fretting hand. If the new chord is not ready, the strum still happens
          on time. To give the fretting hand room, lift the old chord on the
          last upstroke of the bar and let that stroke catch the open strings.
          At tempo it sounds like part of the pattern.
        </p>

        <p>
          If the change is the reason the strum breaks down, isolate the change
          itself. The <Link href="/how-to-change-chords-faster">chord change guide</Link> covers anchor fingers, one-minute changes and how to put the change on the beat.
        </p>

        <h2>Record it and check the time</h2>

        <p>
          Your sense of time in the moment is generous. Record thirty seconds of
          each pattern with the click audible and listen back. Listen for the
          strum drifting ahead of the click on upstrokes, for a stretched beat
          at each chord change, and for downs that are much louder than ups.
          The <Link href="/record-guitar-practice-on-phone">phone recording guide</Link> covers placement and what to listen for.
        </p>

        <h2>A fifteen-minute rhythm session</h2>

        <ol>
          <li>
            <strong>3 minutes:</strong> ghost-strum warm-up. The pendulum on
            muted strings at 60 BPM, counting out loud.
          </li>
          <li>
            <strong>5 minutes:</strong> today&apos;s pattern on one chord, then
            on a two-chord change, four bars clean before you raise the tempo.
          </li>
          <li>
            <strong>4 minutes:</strong> the same pattern with the click on 2 and
            4, or with accents if that is still too hard.
          </li>
          <li>
            <strong>3 minutes:</strong> a song section with the pattern,
            recorded.
          </li>
        </ol>

        <h2>Beyond the basics: the rhythm drills</h2>

        <p>
          When the five patterns are solid, the Advanced Lab has four rhythm
          drills that listen to the timing of each attack through your
          microphone:
        </p>

        <ul>
          <li>
            <Link href="/advanced/funk-sixteenths">Syncopated Sixteenths</Link>:
            constant sixteenth-note motion with only the written hits sounding.
          </li>
          <li>
            <Link href="/advanced/triplet-sixteenth-shift">Gear Shift: Triplets to Sixteenths</Link>:
            switching subdivisions while the beat stays still.
          </li>
          <li>
            <Link href="/advanced/quarter-note-triplets">Three Over Two</Link>:
            quarter-note triplets, three even hits across two beats.
          </li>
          <li>
            <Link href="/advanced/dotted-eighth-displacement">Dotted-Eighth Displacement</Link>:
            an accent that walks across the beat while you keep the four
            underneath.
          </li>
        </ul>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
