import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  ARTICLE_AUTHOR,
  GUIDES,
  LEARN,
  SITE_URL,
  STRUMLY,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/beginner-guitar-practice-routine`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "A beginner guitar practice routine for the first 90 days";

const DESCRIPTION =
  "A 20-minute daily beginner guitar practice routine for your first 90 days: tuning, two chords, one-minute changes, strumming, and a recording every 30 days.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Beginner practice routine", href: "/beginner-guitar-practice-routine" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/beginner-guitar-practice-routine"),
  title: "Beginner Guitar Practice Routine: Your First 90 Days | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // No `images` key: Next attaches the colocated opengraph-image.tsx card
    // only when the page leaves `images` unset.
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "How long should a beginner practice guitar each day?",
    a: "Fifteen to twenty-five minutes, five or six days a week. In the first month your fingertips set the limit more than your attention does, and two short sessions in one day beat one long one. Daily contact matters more than session length, because each night of sleep consolidates what the session started.",
  },
  {
    q: "How long until I can play a whole song?",
    a: "On this plan the first complete song is the target for days 61 to 90, after the eight open chords and steady strumming are in place. A two-chord song with A and D comes earlier, in the first month, and it counts: playing a short piece start to finish without stopping is the skill every later song uses.",
  },
  {
    q: "Should a beginner learn chords or scales first?",
    a: "Chords first. Open chords and a steady strum let you play real songs within weeks, and songs are what keep a beginner practicing. Single notes and the first scale arrive in the fourth stage of the GuitarHub curriculum, once changes and strumming hold up on their own.",
  },
  {
    q: "What should I do on a day with only ten minutes?",
    a: "Tune, run one set of one-minute changes on the chord pair you are working on, and play one song or study through once. That keeps the daily contact that builds calluses and consolidates the change, and it takes ten minutes.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/learn/guitar",
  "/learn/guitar/routine",
  "/how-to-change-chords-faster",
  "/guitar-finger-pain",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/beginner-guitar-practice-routine"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${CANONICAL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: ARTICLE_AUTHOR,
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function BeginnerGuitarPracticeRoutinePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/beginner-guitar-practice-routine"
        crumbs={CRUMBS}
        title={
          <>
            A beginner guitar practice routine for{" "}
            <em className="font-display italic text-peach">the first 90 days.</em>
          </>
        }
        dek="Twenty minutes a day, three 30-day phases, and a recording on days 1, 30, 60 and 90 that shows you exactly what changed."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          A beginner guitar practice routine for the first 90 days is 15 to 25
          minutes a day, five or six days a week, built from the same five
          blocks every time: tune, check one chord string by string, time one
          chord change, strum against a click, and finish by playing something
          musical. What changes across the 90 days is the material inside the
          blocks. Days 1 to 30 cover tuning and your first two chords. Days 31
          to 60 add the rest of the open chords and a strumming hand that never
          stops. Days 61 to 90 end with one complete song. Record yourself on
          day 1 and again on days 30, 60 and 90, and the recordings tell you
          what worked.
        </p>

        <p>
          This page is the plan for your first three months. The lessons
          themselves live in the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link>, which this plan follows stage by stage, and the <Link href="/learn/guitar/routine">A-to-D chord practice routine</Link> runs the timer for the daily blocks while you are on your first two chords.
        </p>

        <h2>Why twenty minutes a day beats two hours on Saturday</h2>

        <p>
          Two things decide the dose for a beginner, and neither is willpower.
          The first is your fingertips. Steel strings press thin skin into the
          fret wire, and the skin toughens through repeated, moderate contact.
          Short daily sessions build calluses. A long weekend session builds
          blisters, and then a week off while they heal.
        </p>

        <p>
          The second is sleep. In a 2002 study published in <em>Neuron</em>,
          Matthew Walker and colleagues trained people on a finger-tapping
          sequence and found they were faster after a night of sleep, with no
          additional practice. A chord change is a finger sequence too. Every
          day you practice gives you another night of that consolidation, which
          is why six short sessions move a beginner further than one long one
          with the same total minutes.
        </p>

        <p>
          So the routine is built for a real weekday: twenty minutes that fit
          before work or after dinner, and a ten-minute version for the days
          that collapse.
        </p>

        <h2>The daily twenty minutes</h2>

        <p>
          The five blocks stay the same for all 90 days. Only the chords and
          songs inside them change.
        </p>

        <ol>
          <li>
            <strong>Tune (2 minutes).</strong> Use the <Link href="/practice">guitar tuner</Link> and check all six strings, low to high: E, A, D, G, B, E. Recheck after every adjustment, because tightening one string pulls the neck and nudges the others.
          </li>
          <li>
            <strong>One chord, string by string (3 minutes).</strong> Form
            the chord, strum it once, then pick each string that belongs in it,
            one at a time. Any string that buzzes or dies gets fixed before
            you move on: a fingertip more upright, closer to the fret, or
            pressing a little firmer.
          </li>
          <li>
            <strong>One change against the clock (5 minutes).</strong> Pick
            one pair of chords and count how many clean changes you make in
            sixty seconds, strumming once on each arrival. Do two or three
            rounds and write down the best count. The <Link href="/how-to-change-chords-faster">chord change guide</Link> covers the finger moves that raise that number.
          </li>
          <li>
            <strong>Strum against a click (7 minutes).</strong> Set the <Link href="/practice">metronome</Link> between 60 and 80 BPM and play the current chords in time, starting with one downstroke per beat. The click decides whether the change arrived on time. Your ear in the moment is too generous.
          </li>
          <li>
            <strong>Play something (3 minutes).</strong> A study, a riff, or a
            song section, played start to finish without stopping. Then write
            one line: the chord pair, today&apos;s one-minute count, and the
            tempo. The <Link href="/log">practice evidence log</Link> keeps that line where you can read the trend.
          </li>
        </ol>

        <p>
          On a short day, run blocks 1, 3 and 5. When you have more or less
          than twenty minutes, the <Link href="/session">practice session builder</Link> resizes the blocks to the time you actually have.
        </p>

        <h2>Days 1 to 30: tune, hold, and two chords</h2>

        <p>
          The first month matches Stage 1 and Stage 2 of the curriculum: Sound
          Check, then Two Chords, First Study. The goal is small and specific.
          By day 30 you tune the guitar on your own, play D and A with every
          string ringing, and hold sixteen bars of steady downstrokes at 80
          BPM.
        </p>

        <ul>
          <li>
            <strong>Week 1.</strong> How to hold the guitar and the pick, the
            six open strings by name, tuning, and reading tab and chord boxes.
            Record your day 1 take: the six open strings, picked one at a time,
            and whatever chord you can already make. It will sound rough. That
            is the point of keeping it.
          </li>
          <li>
            <strong>Week 2.</strong> The D chord and the A chord, each checked
            string by string. D sounds from string 4 down to string 1. A
            sounds from string 5 down to string 1.
          </li>
          <li>
            <strong>Weeks 3 and 4.</strong> The D-to-A change with one finger
            kept in place, one-minute changes every day, and four downstrokes
            per bar against the click. Finish the month with a two-chord study
            or song played start to finish.
          </li>
        </ul>

        <p>
          The <Link href="/learn/guitar/routine">A-to-D chord practice routine</Link> is built for exactly this stretch: seven timed blocks, from tuning to two-chord songs, with durations you can edit and your history kept in the browser.
        </p>

        <h2>Days 31 to 60: the open eight and a hand that never stops</h2>

        <p>
          Month two matches Stage 3, The Open Eight. You add A minor, E minor
          and D minor, then the stretch chords E, C and G. With A and D that
          makes eight open chords, and with a capo they cover songs in many
          more keys.
        </p>

        <p>
          The strumming hand changes job at the same time. Instead of one
          downstroke per beat, it moves down and up in a steady pendulum, down
          on every beat and up on every &ldquo;and,&rdquo; whether or not it
          touches the strings. That constant motion is what keeps time when a
          pattern skips a stroke. The <Link href="/how-to-practice-strumming">strumming guide</Link> takes it from straight eighths to the patterns most songs use.
        </p>

        <ul>
          <li>
            <strong>Weeks 5 and 6.</strong> Am, Em and Dm, then C to Am and
            Am to Em as your one-minute pairs. C to Am keeps two fingers
            exactly where they are, so it climbs quickly.
          </li>
          <li>
            <strong>Weeks 7 and 8.</strong> E, C and G. G to C is the hardest
            change in this set, because no finger stays on the same string and
            fret, so give it its own one-minute rounds every day.
          </li>
          <li>
            <strong>Day 30 and day 60 check.</strong> Record the same passage
            you will record at the end of the month, at the same tempo, from
            the same spot. Listen to both takes back to back before you decide
            how the month went.
          </li>
        </ul>

        <h2>Days 61 to 90: one finished song</h2>

        <p>
          The last month turns parts into a piece. Choose one song that uses
          three or four of your open chords and a strum you can already hold.
          The finish line is one take from the count-in to the last chord with
          no stops, recorded on day 90.
        </p>

        <ol>
          <li>
            Play the whole song once, slowly, and mark the change that breaks
            first. That is your target for the week.
          </li>
          <li>
            Put that one change on a tempo ladder. The <Link href="/tempo">tempo ladder builder</Link> gives you a starting speed, a target, and the steps between them.
          </li>
          <li>
            Reconnect it: play two bars before the change and two bars after,
            then the whole section, then the whole song.
          </li>
          <li>
            Check the song with the <Link href="/readiness">song readiness score</Link> before you record the day 90 take, so you know which part is most likely to break.
          </li>
        </ol>

        <p>
          If the song is solid before day 90, spend five minutes a day on the
          first scale shape. Stage 4 of the curriculum, The First Scale, picks
          up there with single notes and alternate picking.
        </p>

        <h2>Run it as a loop: baseline, isolate, reconnect, prove</h2>

        <p>
          The 90 days use the same four-stage loop as every other plan on this
          site. The day 1 recording is your <strong>baseline</strong>. The
          daily one-minute changes and string checks <strong>isolate</strong>{" "}
          the single change or chord that fails. Playing the change back inside
          a study or song is where you <strong>reconnect</strong> it. The day
          30, 60 and 90 recordings <strong>prove</strong> what moved. The <Link href="/method">GuitarHub method</Link> explains each stage and the exit test that tells you it is finished, and the <Link href="/record-guitar-practice-on-phone">phone recording guide</Link> covers how to make the four takes comparable.
        </p>

        <h2>Common mistakes in the first 90 days</h2>

        <ul>
          <li>
            <strong>Learning a new chord every day.</strong> A chord is
            learned when you can change into it in time, not when you can make
            the shape once. Two chords you can change between beat ten chords
            you can only hold.
          </li>
          <li>
            <strong>Skipping the tuner.</strong> Practicing on an out-of-tune
            guitar teaches your ear the wrong sound. Two minutes, every
            session.
          </li>
          <li>
            <strong>Practicing through sharp pain.</strong> Tender fingertips
            are normal in the first weeks. Sharp pain, numbness, or pain in
            the wrist are stop signals. The <Link href="/guitar-finger-pain">finger pain guide</Link> covers the difference and the guitar setup changes that help.
          </li>
          <li>
            <strong>Stopping at every mistake.</strong> In block 5, keep going
            through the error. Restarting trains restarting.
          </li>
          <li>
            <strong>Judging progress by feel.</strong> How a session felt
            depends on how tired you were. The recordings and the one-minute
            counts are the evidence.
          </li>
        </ul>

        <p>
          For a second view of the beginner path, Strumly&apos;s <a href={STRUMLY.beginnerPath}>beginner guitar learning path</a> lays out the same early skills in order. When you are ready to set one finish line for a month, the <Link href="/breakthrough">30-day breakthrough planner</Link> turns it into four weeks of focused practice.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
