import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  GUIDES,
  LEARN,
  OG_IMAGE,
  SITE_URL,
  STRUMLY,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/how-to-change-chords-faster`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to change chords faster on guitar";

const DESCRIPTION =
  "Change guitar chords faster with anchor fingers, guide fingers, shape moves and one-minute changes, with exact fingerings for D-A-E, C-Am, G-D and G-C.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Change chords faster", href: "/how-to-change-chords-faster" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/how-to-change-chords-faster"),
  title: "How to Change Chords Faster on Guitar | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Is it OK to let the open strings ring while I change chords?",
    a: "Yes. On the last eighth note before a new chord, many players lift the old shape and strum whatever is open while the fingers travel. At song tempo it reads as part of the strum. What does not work is stopping the strumming hand to wait for the fretting hand, because that breaks the time.",
  },
  {
    q: "Should I look at my fretting hand during a change?",
    a: "While you learn the shape, yes. Once the one-minute count for a pair is climbing, start looking at the next chord's position a beat early, then practice a round with your eyes up. A change you can only make while watching is not finished yet.",
  },
  {
    q: "Which chord change should a beginner practice first?",
    a: "D to A. The index finger can stay on string 3 at fret 2 for both shapes, so only two fingers move. It is the first change in the GuitarHub curriculum. After it, C to Am is a quick pair to add, because two fingers stay exactly where they are.",
  },
  {
    q: "How many one-minute changes is good?",
    a: "Work it out from the song. At 100 BPM in 4/4 there are 25 bars a minute, so a song that changes chord once per bar needs 25 changes a minute, and one that changes every two beats needs 50. Aim above the song's number, so the change has time to spare.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/learn/guitar/routine",
  "/tempo",
  "/how-to-practice-strumming",
  "/how-to-play-barre-chords",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/how-to-change-chords-faster"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: CANONICAL,
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: { "@id": "https://suedeai.ai/founder#person" },
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function HowToChangeChordsFasterPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/how-to-change-chords-faster"
        crumbs={CRUMBS}
        title={
          <>
            How to change chords{" "}
            <em className="font-display italic text-peach">faster.</em>
          </>
        }
        dek="Fast changes come from moving less, not from moving harder. Keep what can stay, slide what can slide, move the rest as one shape, and leave early."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To change chords faster on guitar, move fewer fingers a shorter
          distance. Keep any finger that sits on the same string and fret in
          both chords pressed down (an anchor finger). Slide any finger that
          stays on the same string but moves fret (a guide finger). Move the
          remaining fingers together as one shape instead of placing them one
          at a time, and start the move a beat early, while the old chord is
          still sounding. Measure it with one-minute changes: count how many
          clean changes you make in sixty seconds, every day, for each chord
          pair.
        </p>

        <p>
          The fingerings below use string numbers: string 6 is the thickest,
          low E, and string 1 is the thinnest, high E. A chord written as
          x32010 lists the frets from string 6 to string 1, with x for a
          string you do not play and 0 for an open string.
        </p>

        <h2>Why your changes are slow</h2>

        <p>
          A slow change is rarely a slow hand. It is usually one of four habits,
          and you can see all of them in a phone video of your fretting hand.
        </p>

        <ul>
          <li>
            <strong>Fingers lift too far.</strong> Every centimeter a finger
            travels away from the strings is a centimeter it has to travel back.
          </li>
          <li>
            <strong>Fingers land one at a time.</strong> First finger, check,
            second finger, check. Three separate placements take three times as
            long as one.
          </li>
          <li>
            <strong>Fingers that could stay, leave.</strong> Lifting a finger
            that belongs in both chords throws away the one landmark you had.
          </li>
          <li>
            <strong>The move starts late.</strong> If you only think about the
            next chord on the beat it is due, you are already behind.
          </li>
        </ul>

        <h2>Anchor fingers: what stays down</h2>

        <p>
          An anchor finger sits on the same string and fret in both chords. It
          never lifts. It keeps your hand located on the neck and leaves fewer
          fingers to move. Look for anchors first, every time you learn a new
          pair.
        </p>

        <ul>
          <li>
            <strong>C (x32010) and A minor (x02210).</strong> In both shapes the
            index finger is on string 2 at fret 1 and the middle finger is on
            string 4 at fret 2. Only the ring finger moves, from string 5 at
            fret 3 to string 3 at fret 2.
          </li>
          <li>
            <strong>D (xx0232) and A (x02220).</strong> Play A with the middle
            finger on string 4, the index on string 3, and the ring on string 2,
            all at fret 2. The index is now on string 3 at fret 2 in both
            chords, so it stays down while the other two fingers trade places.
            This is the fingering the GuitarHub curriculum teaches for the first
            change.
          </li>
          <li>
            <strong>G (320033) and D (xx0232).</strong> In this version of G the
            ring finger plays string 2 at fret 3 and the pinky plays string 1 at
            fret 3. D also has the ring finger on string 2 at fret 3, so it
            becomes the anchor and the rest of the hand pivots around it.
          </li>
          <li>
            <strong>E minor (022000) and G (320003).</strong> Finger E minor with
            the index on string 5 and the middle finger on string 4. G puts the
            index on string 5 at fret 2 as well, so it stays while the middle
            finger moves to string 6 at fret 3 and the ring finger lands on
            string 1.
          </li>
        </ul>

        <p>
          Notice that two of those depend on choosing a fingering. When a chord
          has more than one standard fingering, choose the one that shares a
          finger with the chords around it in the song.
        </p>

        <h2>Guide fingers: slide, do not lift</h2>

        <p>
          A guide finger stays on the same string but moves to a different
          fret. Instead of lifting it, ease the pressure and slide it along the
          string, keeping light contact. The string acts as a rail, so the
          finger arrives in the right place without you looking for it.
        </p>

        <p>
          The key of A shows it best. Using the A fingering above, the index
          finger is on string 3 at fret 2 for D, stays there for A, and slides
          back to fret 1 for E (022100). Across A, D and E, the one, four and
          five chords in the key of A, the index finger never leaves string 3.
        </p>

        <h2>Shape moves: travel as one unit</h2>

        <p>
          When no finger can stay, the fingers that move should move together,
          already arranged in the next shape. Two pairs show how much of a
          change this removes.
        </p>

        <ul>
          <li>
            <strong>A minor (x02210) to E (022100).</strong> The fingers make
            the same shape in both chords, one string apart. A minor sits on
            strings 4, 3 and 2. E is the identical shape on strings 5, 4 and 3.
            Keep the shape locked and move the whole hand one string toward the
            ceiling.
          </li>
          <li>
            <strong>G (320003) to C (x32010).</strong> Play G with the ring
            finger on string 6, the middle on string 5, and the pinky on string
            1. For C, the ring and middle fingers step across one string
            together, to string 5 at fret 3 and string 4 at fret 2, and the index
            lands on string 2 at fret 1. Two fingers moving as a pair is one
            move, not two.
          </li>
        </ul>

        <p>
          A useful drill for any pair is the shape drop. Form the destination
          chord, lift every finger a few millimeters while keeping the shape,
          hold it in the air for a beat, and drop all the fingers at once. Then
          strum and check that every string rings. Ten clean drops trains the
          hand to arrive as a unit.
        </p>

        <h2>Look ahead and leave early</h2>

        <p>
          The fretting hand should start moving before the new chord is due. On
          a four-beat bar, think the name of the next chord on beat 3, and start
          the move on the last &ldquo;and&rdquo; of the bar. Your strumming hand
          keeps going through the gap. If the last upstroke of the bar catches
          a few open strings while the fingers travel, that is normal and,
          at tempo, it sounds like part of the strum.
        </p>

        <p>
          Your eyes lead too. Once a pair feels familiar, look at where the next
          chord&apos;s anchor or lowest finger lands, a beat before you need
          it, instead of watching the chord you are holding.
        </p>

        <h2>One-minute changes: the number that tells you</h2>

        <p>
          The measurement for all of this is one-minute changes. It is in Stage
          2 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link>, and it works for any pair of chords.
        </p>

        <ol>
          <li>
            Choose one pair of chords, for example D and A.
          </li>
          <li>
            Form the first chord. That position is zero.
          </li>
          <li>
            Start a sixty-second timer. Change to the second chord and strum
            once: that is one. Change back and strum: two. Keep alternating.
          </li>
          <li>
            Count only changes where the chord was fully formed when you
            strummed. Do not stop to fix a bad one. Just keep going.
          </li>
          <li>
            Write down the count with the date. Do two or three rounds per pair
            and keep the best.
          </li>
        </ol>

        <p>
          Run it every day for the pairs in the song you are learning. The
          number moves day by day in a way that your sense of the change does
          not, and the <Link href="/log">practice evidence log</Link> shows the trend once you have three sessions in it. For D and A, the <Link href="/learn/guitar/routine">A-to-D chord practice routine</Link> times both directions for you, starting on A and starting on D.
        </p>

        <h2>Put the change in time</h2>

        <p>
          A one-minute count measures speed. A song needs the change on the
          beat. Once a pair is climbing, move it to the <Link href="/practice">metronome</Link>:
        </p>

        <ol>
          <li>
            At 60 BPM, strum each chord four times (one bar) and change. Four
            clean bars in a row moves you to the next step.
          </li>
          <li>
            Change every two beats.
          </li>
          <li>
            Change every beat. This is the hardest step and the one that makes
            the bar-length change easy at song tempo.
          </li>
          <li>
            Raise the tempo in small steps and repeat. The <Link href="/tempo">tempo ladder builder</Link> sets the starting speed, the target, and the steps between.
          </li>
        </ol>

        <p>
          When the change holds against the click, play it inside the song
          again: two bars before it, two bars after it, then the full section.
          The isolated drill only counts once it survives that.
        </p>

        <h2>A ten-minute chord change session</h2>

        <ol>
          <li>
            <strong>1 minute:</strong> check both chords string by string. Fix
            any string that buzzes.
          </li>
          <li>
            <strong>2 minutes:</strong> silent shape drops into each chord,
            anchors and guides held.
          </li>
          <li>
            <strong>3 minutes:</strong> one-minute changes, three rounds, best
            count written down.
          </li>
          <li>
            <strong>3 minutes:</strong> the change against the click, four
            beats, then two.
          </li>
          <li>
            <strong>1 minute:</strong> play the change inside the song or study
            it came from.
          </li>
        </ol>

        <p>
          Strumly&apos;s guide to <a href={STRUMLY.chordTransitions}>smoother chord transitions</a> goes further into finding which single finger is arriving late. When the change you need is into a barre chord, the <Link href="/how-to-play-barre-chords">barre chord guide</Link> covers the F chord and the moves in and out of it, and the <Link href="/how-to-practice-strumming">strumming guide</Link> keeps the other hand steady while the changes speed up.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
