import type { Metadata } from "next";
import Link from "next/link";
import Article, { type RelatedLink } from "@/components/Article";
import {
  GUIDES,
  OG_IMAGE,
  SITE_URL,
  STRUMLY,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";

const CANONICAL = `${SITE_URL}/practicing-guitar-with-a-metronome`;
const PUBLISHED = "2026-08-29";

const TITLE = "How to Actually Practice With a Metronome";
const DESCRIPTION =
  "Most players play along with a click instead of testing against it. What the gap tells you, how to subdivide, where to put the click, and when to leave it off.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES].map((entry) => [entry.href, entry]),
);

/**
 * Related links, resolved against the route registry where an entry exists and
 * falling back to the literal below where it does not. `lib/site.ts` is the one
 * place titles and blurbs live, so a registry hit always wins; the literals are
 * here only so a sibling guide landing in the same release still renders a card
 * instead of silently dropping out of this list.
 */
const RELATED_SOURCE: readonly RelatedLink[] = [
  {
    href: "/tempo",
    title: "Tempo ladder builder",
    blurb:
      "Turn the tempo you own and the tempo you want into an ordered set of sessions.",
  },
  {
    href: "/why-cant-i-play-guitar-fast",
    title: "Why you cannot play fast yet",
    blurb:
      "What actually limits speed, and why turning the metronome up is rarely the fix.",
  },
  {
    href: "/deliberate-practice-guitar",
    title: "Deliberate practice on guitar",
    blurb:
      "What deliberate practice means at the instrument, and how it differs from playing something again.",
  },
  {
    href: "/how-to-practice-guitar-effectively",
    title: "How to practice guitar effectively",
    blurb:
      "What to do with a practice hour so it changes your playing instead of filling the time.",
  },
];

const RELATED: readonly RelatedLink[] = RELATED_SOURCE.map(
  (item) => ENTRY_BY_HREF.get(item.href) ?? item,
);

// The canonical estate @ids, copied from app/layout.tsx. Referenced rather than
// redefined: the Organization and Person nodes are already declared once in the
// root layout, which renders on this page too.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: "How to actually practice with a metronome",
      description: DESCRIPTION,
      // `image` is a recommended Article property, and without it the page is
      // not eligible for an Article rich result. Every route serves the
      // 1200x630 card generated by app/opengraph-image.tsx.
      image: `${SITE_URL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: PUBLISHED,
      inLanguage: "en-US",
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
    },
  ],
};

export default function MetronomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        eyebrow="Timing and tempo"
        title={
          <>
            How to actually practice with a{" "}
            <em className="font-display italic text-peach">metronome.</em>
          </>
        }
        dek="Playing along with a click measures how well you follow a sound. Testing against it measures your time. This is how to run the second one."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          A metronome is a measuring instrument, not an accompanist. Playing
          along with it mostly tests how well you follow a sound, which is a
          different skill from keeping time. The version that changes your
          playing is the opposite: you keep the time, and the click checks it.
          Make the click sparse enough that the timekeeping is genuinely yours,
          put the passage against it, and listen to the gap between your note and
          the click. Where that gap opens is the fault. A metronome does not make
          you steady. It makes unsteadiness audible.
        </p>

        <h2>What a click actually reveals</h2>

        <p>
          A metronome does one thing: it produces an event at a fixed interval.
          It has no opinion about your playing and no way to correct you. All of
          the information sits in the distance between the click and your note,
          and that distance carries three readings.
        </p>

        <ul>
          <li>
            <strong>Direction.</strong> Are you consistently in front of the
            click, or consistently behind it? The two have different causes and
            different fixes, and guessing wrong costs you the week.
          </li>
          <li>
            <strong>Location.</strong> Which beat, which bar, which side of a
            chord change. A timing problem that is really one transition is a
            small job. A timing problem everywhere is a different job.
          </li>
          <li>
            <strong>Shape.</strong> Does the gap grow steadily from the top, or
            open in one spot and close again? Steady growth is a tempo you cannot
            hold. A spike is a passage you cannot play yet.
          </li>
        </ul>

        <p>
          A click on every beat gives you almost none of this. It re-anchors you
          four times a bar, so you never drift far enough for the drift to be
          visible. That is why quarter notes under a strummed song feel
          reassuring and teach so little: they confirm you can stay within a beat
          of a reference, which you already could.
        </p>

        <h2>Subdivision is the part you are missing</h2>

        <p>
          Time is not the beats but the space between them, and that space is
          where almost everything you play lives. With the click on the beat, the
          beat is the only place you have a reference. Offbeats, sixteenths, the
          back half of a strum pattern, the moment you release a chord: all
          unsupervised.
        </p>

        <p>
          So supervise it yourself. Count the subdivision out loud while you
          play, in whatever unit the passage moves in. Out loud matters, because
          counting in your head quietly stops when a bar gets hard, and the bar
          that stops you counting is the bar you were looking for.
        </p>

        <p>
          Match the click to the passage, not to the smallest note in it. A click
          on every sixteenth under a sixteenth-note figure removes the thing you
          are building, which is your own even division of the beat. Click the
          eighths and let your hands own the sixteenths.
        </p>

        <h2>Move the click to expose your real time-keeping</h2>

        <h3>Beats two and four</h3>

        <p>
          Halve the metronome tempo and hear each click as the backbeat. For a
          piece at 120, set the metronome to 60 and count four beats with the
          clicks landing on two and four. Beats one and three are yours to place
          now. Getting in takes a few attempts, because starting against a click
          that is not beat one is genuinely harder, and drift shows up within a
          bar or two rather than never: a rushed beat one has nothing propping it
          up.
        </p>

        <h3>Beat one only</h3>

        <p>
          Quarter the tempo. At 120 that is a click at 30, one per bar in common
          time, near the bottom of the range on many metronomes. You are keeping
          three beats out of four, so one rushed bar puts your downbeat audibly
          in front of the click instead of merely feeling wrong. This is where
          most players find their time is fine in the easy bars and moves
          everywhere else.
        </p>

        <h3>Bars with no click at all</h3>

        <p>
          Sparser than one click per bar needs a metronome that can mute bars, a
          gap or silence setting if yours has one. Two bars of click, two bars of
          nothing, repeating. Play through the silence and find out whether you
          land back on the click or in front of it. For two bars there is no
          reference at all, and the verdict arrives at once.
        </p>

        <h3>The click on the offbeat</h3>

        <p>
          The hardest placement, and it tests what the others cannot: whether
          your subdivision is even. Keep the metronome at the quarter-note tempo,
          count one and two and over it, then flip the count so the clicks land
          on the ands rather than the numbers. It will invert on you the first
          several times, snapping back until the click sounds like a downbeat
          again. That inversion is the test: if your eighths are uneven, the flip
          has nothing steady to sit on.
        </p>

        <h2>What playing ahead and dragging feel like</h2>

        <h3>Playing ahead</h3>

        <p>
          The click seems to arrive a moment after you rather than with you, as
          though the metronome had slowed down. The passage feels urgent and the
          sensation is one of leaning. Rushing shows up in the easy bars, in the
          bar after a difficult one, and anywhere the music gets louder. Relief
          speeds people up as reliably as nerves do.
        </p>

        <h3>Dragging</h3>

        <p>
          The click seems to pull away, and playing feels like chasing something.
          Dragging sits in the physically expensive bar: the stretch, the barre,
          the position shift, the first chord after a change your fretting hand
          has not finished making. It also appears wherever you are still
          deciding what comes next, because deciding takes time the bar does not
          have.
        </p>

        <h3>The combination that costs you</h3>

        <p>
          The common pattern is both at once. Rush into the hard bar, drag
          through it, come out in front again. Across a take the errors cancel,
          so the average looks fine while the take sounds wrong. Nobody hears an
          average. They hear the two places where the pulse moved.
        </p>

        <p>
          One cheap test for direction, once the click is sparse: turn it down
          until it is only just audible. Land exactly on it and your attack
          swallows the click, so it seems to vanish. Land off it and you hear two
          separate events, and their order tells you which way you went.
        </p>

        <h2>Tempo is a measurement, not a target</h2>

        <p>
          A number on a metronome means nothing by itself. What makes it a
          measurement is the condition attached, so write that down beside it.
          Bars nine to twelve, 84 BPM, three passes in a row, cold, no missed
          notes and no stopping. That is a reading. Just 84 is a memory, and
          memory rounds in your favor.
        </p>

        <p>
          Cold is the load-bearing word: first thing in the session, no run-up,
          no eight attempts. Best of eight is a ceiling, and a ceiling is not
          what shows up when you play for someone. What you can repeat cold is a
          floor, and the floor is the only number worth building on.
        </p>

        <p>
          A number with no condition drifts upward on its own. The tempo you hit
          once on the twentieth try is your tempo by Thursday, and every session
          after it is built on a coincidence.
        </p>

        <p>
          With a real floor and a target, the distance between them is a plan
          rather than a wish. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> turns those two numbers
          into an ordered set of sessions: every increase capped, some sessions
          repeating a tempo instead of adding to it, and at least one that drops
          below the top speed and climbs back. Reaching a tempo once and owning
          it are different events.
        </p>

        <p>
          When the target refuses to arrive however patiently you climb, the
          ceiling is usually not made of tempo.{" "}
          <Link href="/why-cant-i-play-guitar-fast">
            What actually limits speed
          </Link>{" "}
          is worth reading before you turn the number up again.
        </p>

        <h2>Four drills, each with a pass condition</h2>

        <p>
          Each takes a few minutes and returns a yes or a no. A drill with no
          pass condition is time near a metronome.
        </p>

        <ol>
          <li>
            <strong>The cold three.</strong> First thing in the session, no
            warm-up: three consecutive clean passes at one tempo.{" "}
            <em>Pass:</em> three in a row, not three out of five. Every other
            number depends on this one.
          </li>
          <li>
            <strong>The silent bar.</strong> Two bars of click, two bars muted,
            repeating. <em>Pass:</em> four cycles where the click returns exactly
            where you expected it.
          </li>
          <li>
            <strong>The one-question listen.</strong> Record thirty seconds
            against a sparse click, then listen back for one thing: ahead or
            behind, and where. <em>Pass:</em> you can name a bar.
          </li>
          <li>
            <strong>The handover.</strong> Play the passage with the click, then
            immediately without it, then a third time with it back on.{" "}
            <em>Pass:</em> the click comes back roughly where your playing left
            it. A large jump means the click was carrying you.
          </li>
        </ol>

        <h2>When not to use a metronome</h2>

        <p>
          A click answers one narrow question. Pointed at a different one it
          teaches something you then have to undo.
        </p>

        <ul>
          <li>
            <strong>When the problem is not timing.</strong> Tone, vibrato,
            whether a bend arrives in tune, the balance inside a voicing. A click
            holds no information about any of them and pulls your attention off
            what you sat down to fix.
          </li>
          <li>
            <strong>When the motion does not exist yet.</strong> A click is a
            deadline. Give one to a hand that has not made the movement and you
            get a tense approximation you then have to practice your way out of.
            Build the motion slowly and freely. Add the clock once it repeats.
          </li>
          <li>
            <strong>When the music is not in strict time.</strong> A rubato
            intro, a free ending, a passage meant to breathe. Practicing those to
            a click removes the thing they are.
          </li>
          <li>
            <strong>When you are playing with a recording or with people.</strong>{" "}
            The recording is the reference, and so is the drummer. A click
            running against a human is an argument you cannot win.
          </li>
          <li>
            <strong>When you can no longer play the piece without one.</strong>{" "}
            That is a dependency, and the handover drill is how you catch it. The
            cure is not more click. It is the sparse settings above, in order.
          </li>
          <li>
            <strong>When you are playing for the pleasure of it.</strong> Not
            every session is practice, and a measuring instrument is poor
            company.
          </li>
        </ul>

        <h2>Where the click sits in a week</h2>

        <p>
          A metronome is one tool inside a session, not the session. It belongs
          to the moments when you are testing something specific and want an
          outside opinion, which is a narrow slice of the week.{" "}
          <Link href="/method">The GuitarHub method</Link> puts that slice in
          order: measure where you are, shrink the problem, put it back under
          pressure, then record and compare. A click earns its place in the first
          and third.
        </p>

        <p>
          Practice moves when an attempt has a specific target and honest
          feedback attached, which is what a sparse click supplies. There is more
          on{" "}
          <Link href="/deliberate-practice-guitar">
            what that looks like at the instrument
          </Link>
          , and on{" "}
          <Link href="/how-to-practice-guitar-effectively">
            how to spend a practice hour
          </Link>
          . Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers the scheduling side.
        </p>

        <p>
          One last thing a click cannot do. It tells you that you are late, not
          why, and the why is almost always somewhere else: a chord shape your
          hand reaches for a beat too late, a pick stroke starting on the wrong
          side of the string, a breath you stopped taking four bars ago. Naming
          that cause is a separate job. Strumly&apos;s guide to{" "}
          <a href={STRUMLY.aiCoach}>practicing with an AI coach</a> covers what
          that kind of feedback is good for and where it stops.
        </p>

      </Article>
    </>
  );
}
