import type { Metadata } from "next";
import Link from "next/link";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, STRUMLY } from "@/lib/site";

const CANONICAL = "https://guitarhub.org/30-day-guitar-challenge";

const TITLE = "The 30-Day Guitar Challenge That Actually Works";
const DESCRIPTION =
  "Most 30-day guitar challenges measure the streak instead of the playing. Here is how to pick a finish line you can prove, run the four weeks, and judge day 30.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Rendered as the visible "Common questions" section AND as the FAQPage
 * node below. One source, so the structured data is verbatim by
 * construction rather than by somebody remembering to keep two copies
 * in sync. Answers stay plain strings with no inline markup for the
 * same reason.
 */
const FAQS = [
  {
    q: "Does missing a day mean starting the challenge over?",
    a: "No. Missing a day costs one session. The challenge is judged on whether the day 30 recording differs from the day 1 recording, not on how many days in a row you practiced.",
  },
  {
    q: "How long should each practice session be?",
    a: "Long enough to do the repair work rather than only warm up and play through. The GuitarHub planner accepts sessions of 15 to 60 minutes, three to six days a week, and builds the same four-week sequence at any of those settings.",
  },
  {
    q: "Can I work on more than one finish line in the same 30 days?",
    a: "Pick one. Two finish lines split the month into two fortnights, and a fortnight is rarely enough to get through diagnosis and repair on either. Write the second one down and run it next month.",
  },
  {
    q: "What if I cannot record myself properly?",
    a: "A phone voice memo is enough. The recording is a measurement, not a release. What matters is that the day 1 and day 30 takes exist, were played under the same conditions, and can be listened to back to back.",
  },
] as const;

// Same @ids as app/layout.tsx, so the Article attaches to the existing
// Organization and Person nodes instead of minting duplicates.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: TITLE,
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without
      // it the page is not eligible for an Article rich result. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: "2026-08-29",
      dateModified: "2026-08-29",
      inLanguage: "en-US",
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: CANONICAL,
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

const RELATED_HREFS = new Set([
  "/method",
  "/guitar-practice-plateau",
  "/deliberate-practice-guitar",
  "/guitar-practice-routine-intermediate",
]);

const RELATED = GUIDES.filter((guide) => RELATED_HREFS.has(guide.href));

export default function ThirtyDayGuitarChallengePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        title={
          <>
            The 30-day guitar challenge{" "}
            <em className="font-display italic text-peach">that actually works.</em>
          </>
        }
        dek="Streak challenges measure attendance. This one measures playing: one finish line, a day 1 baseline, four weeks that each do a different job, and two recordings you compare at the end."
        updated="2026-08-29"
        related={RELATED}
      >
        <p>
          A 30-day guitar challenge works when it ends with two recordings you
          can play back to back: one from day 1, one from day 30, of the same
          thing, under the same conditions. Everything else is scaffolding.
          Choose one finish line narrow enough that someone could listen for a
          minute and say whether you hit it. Record it before you practice.
          Spend the four weeks diagnosing what breaks, repairing that one thing,
          putting it back under pressure, and performing it. The daily streak is
          not the measure. The pair of recordings is.
        </p>

        <h2>Why most 30-day challenges fail</h2>

        <p>
          The common format asks you to play every day for 30 days. It is easy
          to explain, easy to start, and it measures the wrong thing. Attendance
          and change are not the same, and a challenge scored on attendance
          cannot tell them apart. Four failure modes account for most of it.
        </p>

        <ul>
          <li>
            <strong>The streak becomes the scoreboard.</strong> A checked box
            records that you picked up the guitar, not what you did with it.
            Thirty checked boxes can describe 30 sessions of playing the parts
            you already play well.
          </li>
          <li>
            <strong>The goal is too broad to judge.</strong> Get better at
            rhythm has no finish line. On day 30 you will argue with yourself
            about whether it happened, and there is no evidence in the argument.
          </li>
          <li>
            <strong>There is no baseline.</strong> Without a day 1 recording,
            the comparison at the end runs against your memory of how you
            sounded, and memory bends toward whatever you already believe.
          </li>
          <li>
            <strong>One missed day ends the run.</strong> All-or-nothing framing
            turns a single skipped evening into a reason to abandon the
            remaining three weeks.
          </li>
        </ul>

        <h2>Choose a finish line narrow enough to prove</h2>

        <p>
          A finish line is one sentence describing a performance you can either
          deliver or not. The test is whether a person who knows nothing about
          your practice could listen to a recording and answer yes or no without
          a follow-up question. If the answer needs context from you, the finish
          line is still a wish.
        </p>

        <ul>
          <li>
            Get faster becomes <em>play the main riff cleanly at 120 bpm, up
            from the 88 bpm I can hold today.</em>
          </li>
          <li>
            Get better at rhythm becomes <em>play two minutes of this groove
            against a click without losing the pulse.</em>
          </li>
          <li>
            Learn the fretboard becomes <em>find and play the same phrase in
            three neck positions without hunting for the notes.</em>
          </li>
          <li>
            Finish a song becomes <em>record this song from count-in to final
            chord in one take, no restarts.</em>
          </li>
        </ul>

        <p>
          Two sizing rules. The finish line has to be something you cannot do
          today, or there is nothing to prove. It also has to be close enough
          that four focused weeks could plausibly reach it, which usually means
          taking a piece of a large goal rather than the goal. Play the solo is
          often a month of work. Play the whole song at tempo is often not.
        </p>

        <p>
          The{" "}
          <Link href="/breakthrough">30-day breakthrough planner</Link> holds you
          to one finish line and turns it into a week-by-week sequence with the
          evidence each week has to produce. It runs in your browser and needs
          no account.
        </p>

        <h2>Record the baseline before you practice</h2>

        <p>
          Day 1 is a recording day. Play the thing once, all the way through,
          before you have warmed up on it and before you have started fixing
          anything. One take. Keep the mistakes.
        </p>

        <p>
          A phone on a table is enough. The recording does not have to sound
          good, but it does have to be repeatable, so write the conditions
          beside it: tempo, where you started, whether a click was running, what
          room you were in. You repeat those conditions on day 30, because a
          comparison between two different setups proves nothing.
        </p>

        <p>
          While it is fresh, write one line naming the exact bar, transition, or
          beat where the performance first came apart. That line is your week 1
          diagnosis, and most of the month depends on it being specific. The
          chorus is messy is not specific. The change out of the fourth bar of
          the chorus arrives half a beat late is.
        </p>

        <h2>The four-week arc</h2>

        <p>
          Each week does a different job. Running the same practice for four
          weeks is how a challenge turns into 30 repetitions of the same
          plateau.
        </p>

        <h3>Week 1: diagnose honestly</h3>

        <p>
          Find the single place the performance breaks, not the list of
          everything imperfect. Play the whole thing a few times and watch for
          the failure that repeats. If two candidates keep competing, take the
          earlier one. An error near the start compounds into everything after
          it.
        </p>

        <h3>Week 2: repair one thing</h3>

        <p>
          Take the broken piece out of its context and work it alone, at a
          tempo where playing it correctly is boring. Slow enough that failure
          is rare, then step the speed up. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> turns one passage into
          a starting speed, a target, and the steps between them. Put the piece
          back into the song at the end of each session so you are repairing the
          join and not just the fragment. If the break is a chord change, the
          Strumly guide to{" "}
          <a href={STRUMLY.chordTransitions}>smoother chord transitions</a>{" "}
          covers the mechanics.
        </p>

        <h3>Week 3: add real pressure</h3>

        <p>
          A repaired passage played alone at a comfortable tempo is not yet a
          repaired performance. Put it back under the conditions that will exist
          on day 30: full length, real tempo, a click or a backing track, and a
          cold start with no warm-up run first. Work that holds in isolation
          often falls apart here, and finding that out in week 3 leaves time to
          respond.
        </p>

        <h3>Week 4: perform and compare</h3>

        <p>
          Stop making changes. Rehearse the version you have, record the final
          take under the day 1 conditions, and put the two recordings side by
          side. Week 4 is not for one last improvement. It is for making the
          result repeatable.
        </p>

        <h2>What to record, and when</h2>

        <ul>
          <li>
            <strong>Day 1.</strong> The baseline take, before practicing, plus
            the written conditions and the first breakdown point.
          </li>
          <li>
            <strong>End of week 2.</strong> The repaired piece on its own, at
            the fastest tempo where it stays clean. That number is the one you
            are trying to move.
          </li>
          <li>
            <strong>End of week 3.</strong> A full run under pressure. Expect it
            to be worse than the isolated take from week 2. The size of that gap
            is your week 4 workload.
          </li>
          <li>
            <strong>Day 30.</strong> The final take, under the day 1 conditions,
            recorded whether or not it goes well.
          </li>
        </ul>

        <p>
          Between those points, one line per session is enough: what you worked
          on, at what tempo, and what changed. The log exists so that on day 30
          you can tell whether a result came from the work or from a good night.
          How you structure the session itself is a separate problem, and the
          Strumly guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers it.
        </p>

        <h2>Missing a day is not failure</h2>

        <p>
          A missed day costs one session. Quitting on day 12 costs the other 18.
          Streak framing makes those feel like the same size of mistake, which
          is the most expensive thing about it.
        </p>

        <p>
          So drop the streak. The month is scored on whether the day 30
          recording differs from the day 1 recording in the way you predicted.
          Four missed days with the other 26 spent on the actual blocker beats
          30 days of running the whole song from the top.
        </p>

        <p>
          What genuinely breaks a 30-day run is changing the finish line
          partway through. Week 2 is uncomfortable by design, because week 2 is
          where you work slowly and alone on the one thing you are worst at.
          Switching goals at that point feels like progress and resets the month
          to zero. If the finish line was chosen badly, write that down, finish
          the 30 days anyway, and choose better next time.
        </p>

        <h2>Judging day 30 honestly</h2>

        <p>
          Play the day 1 recording first, then the final take, once each. Then
          answer three questions.
        </p>

        <ol>
          <li>
            Is the thing you named on day 1 still the first thing that breaks?
            If it is, the month did not reach the target, whatever else
            improved along the way.
          </li>
          <li>
            Can the difference be heard without knowing where to listen? Play
            both takes for someone who has not been told what changed. If they
            cannot hear it, the change may still be real, but it is small.
          </li>
          <li>
            Can you repeat the final take right now? A performance you produced
            once out of nine attempts is a good sign, not a finished skill.
          </li>
        </ol>

        <p>
          If the finish line was a song, the{" "}
          <Link href="/readiness">song readiness score</Link> checks it against
          the parts that tend to break under pressure, which is a useful second
          opinion before you call the month done.
        </p>

        <h2>If it did not work</h2>

        <p>
          Missing the finish line is a result, not a wasted month. The log
          usually tells you which of a small number of things happened.
        </p>

        <ul>
          <li>
            <strong>The finish line was too broad.</strong> Effort spread across
            a goal containing several independent problems. Cut it to the
            smallest piece still worth playing and run that.
          </li>
          <li>
            <strong>You practiced the whole thing instead of the broken part.</strong>{" "}
            Common, comfortable, and easy to spot in the log: sessions that
            describe playing through rather than working on. Week 2 is the week
            that got skipped.
          </li>
          <li>
            <strong>You never found the real blocker.</strong> What you repaired
            was not what was breaking the performance. The{" "}
            <Link href="/diagnose">practice plateau diagnostic</Link> is built
            for this case, and walks you to the part of your practice that
            stopped producing change.
          </li>
          <li>
            <strong>It is working, slower than 30 days.</strong> Tempo up, error
            count down, target not yet reached. Keep the same finish line and
            run a second month rather than starting over on something new.
          </li>
        </ul>

        <h2>Common questions</h2>

        {FAQS.map((item) => (
          <div key={item.q}>
            <h3>{item.q}</h3>
            <p>{item.a}</p>
          </div>
        ))}

        <hr />

        <p>
          The{" "}
          <Link href="/breakthrough">30-day breakthrough planner</Link> takes a
          finish line, the days you have, and your session length, and lays out
          the four weeks with the evidence each one has to produce. Record day 1
          before you build the plan. The baseline is the part people skip, and
          it is the part the whole month gets measured against.
        </p>
      </Article>
    </>
  );
}
