import type { Metadata } from "next";
import Link from "next/link";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, TOOLS, STRUMLY } from "@/lib/site";

const CANONICAL = "https://guitarhub.org/guitar-practice-routine-intermediate";

const TITLE = "An Intermediate Guitar Practice Routine in Five Blocks";
const DESCRIPTION =
  "A five-block practice routine for players stuck between beginner and fluent, in a 25-minute and a 50-minute version, plus what to cut on a 10-minute day.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description:
      "Five blocks with different jobs, in a 25-minute and a 50-minute version. The structure stays fixed; the material inside it moves as the evidence moves.",
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

// These @ids match the Organization and Person nodes defined in app/layout.tsx.
// Referencing rather than redefining keeps one entity per node across the site.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

/**
 * Rendered verbatim in the Q&A section below AND emitted as the FAQPage node.
 * Both read from this array, so the structured data can never drift from the
 * visible text.
 */
const FAQS = [
  {
    q: "How long should an intermediate guitar practice session be?",
    a: "Long enough to hold a real repair block. Fifty minutes fits all five blocks comfortably. Twenty-five works if you run the tempo ladder inside the repair block and take the time out of the pressure block rather than out of the cold-start test.",
  },
  {
    q: "Should scales be part of an intermediate practice routine?",
    a: "Only inside a block that needs them. A scale is warm-up material when it matches the motion your repair target requires, and it is repair material when the failing unit is a position shift or a string crossing inside that scale. A scale run attached to no target belongs outside the session.",
  },
  {
    q: "What should I do if I cannot identify a repair target?",
    a: "Record one cold take of a song you claim to know, listen to it once, and write down the first place it broke. That is the target. If nothing broke, the piece is too easy to diagnose anything and you need a harder one on the list.",
  },
  {
    q: "How often should the routine itself change?",
    a: "The five blocks stay. The material inside them changes when the evidence says so: when the error rate stops dropping across two consecutive sessions, when the unit has been clean at the song's tempo for three sessions, or when the cold-start test starts breaking somewhere new.",
  },
] as const;

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: TITLE,
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without
      // it the page is not eligible for an Article rich result. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: "2026-08-29",
      dateModified: "2026-08-29",
      inLanguage: "en-US",
      mainEntityOfPage: CANONICAL,
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
  ],
};

const RELATED = [
  ...GUIDES.filter((guide) =>
    [
      "/how-to-practice-guitar-effectively",
      "/guitar-practice-plateau",
      "/deliberate-practice-guitar",
    ].includes(guide.href),
  ),
  ...TOOLS.filter((tool) => tool.href === "/breakthrough"),
];

export default function IntermediatePracticeRoutinePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        title={
          <>
            An intermediate guitar practice routine{" "}
            <em className="font-display italic text-peach">
              that changes every week.
            </em>
          </>
        }
        dek="Five blocks with different jobs, in a 25-minute and a 50-minute version. The structure stays fixed. The material inside it moves as the evidence moves."
        updated="2026-08-29"
        related={RELATED}
      >
        <p>
          An intermediate practice routine works when the session is split into
          five blocks with different jobs: a warm-up with a stated intent, one
          repair target, tempo work on that target, repertoire played under
          pressure, and a cold-start test. A 50-minute session runs 5 / 15 / 10
          / 15 / 5 minutes. A 25-minute session runs 3 / 10 / 8 / 4, with the
          tempo ladder folded into the repair block. Keep the five blocks fixed
          and change the material inside them as the evidence changes. A routine
          that is identical in week four to week one has stopped producing
          change, because the fault it was built to fix is either fixed by now
          or was never the real one.
        </p>

        <h2>Why the intermediate stall is a structure problem</h2>

        <p>
          You can almost play a hundred things and fully play none. That is
          rarely a talent ceiling and it is usually not a discipline problem
          either. It is what happens when every session is built from the same
          material: the songs you can already mostly play, at the speed you can
          already mostly play them, stopping and restarting whenever a bar goes
          wrong.
        </p>

        <p>
          That session feels like work and produces very little, because nothing
          in it is aimed at a specific fault and nothing in it measures whether
          the fault moved. The five blocks below exist to give each part of the
          hour one job and one output. If the sessions have stopped producing
          any change at all, read{" "}
          <Link href="/guitar-practice-plateau">
            why guitar practice plateaus
          </Link>{" "}
          first, because a plateau needs a diagnosis before it needs a routine.
        </p>

        <h2>The five blocks, and what each one is for</h2>

        <p>
          Run them in this order. Each block hands its output to the next, and
          the last block generates the input for tomorrow.
        </p>

        <h3>1. Warm-up with intent, 5 minutes</h3>

        <p>
          This block gets your hands and ears working and commits you to the one
          thing the session will fix.
        </p>

        <p>
          Use material that matches the motion your repair target needs. If the
          target is a barre change, warm up moving between barre shapes slowly
          and cleanly. If it is string crossing at speed, cross strings at a
          tempo where nothing misfires. A warm-up made of unrelated scale
          patterns is just the first five minutes of playing.
        </p>

        <p>
          End the block by naming the target out loud or writing it down. If you
          cannot finish the sentence &ldquo;today I am fixing ___&rdquo;, you do
          not have a session yet. You have practice time.
        </p>

        <h3>2. The one repair target, 15 minutes</h3>

        <p>
          This block makes one specific thing measurably better. It is the only
          block that is allowed to feel bad.
        </p>

        <p>
          Take the smallest unit that actually breaks. Usually that is two bars,
          one chord change, one position shift, or one string crossing. Not a
          section, and never a whole song. Work it well under performance speed
          with your phone recording the entire block, so you are judging the
          take instead of the memory of the take.
        </p>

        <p>
          The test is countable: five correct repetitions in a row, counted, not
          &ldquo;it is mostly there now&rdquo;. If you cannot get five, the unit
          is too big or the tempo is too high. Halve the unit before you lower
          the tempo again.
        </p>

        <p>
          Choose the target from your own evidence, not from a video you saw:
          the place the pressure block collapsed last session, or the break
          point the cold-start test exposed. The{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> is a faster
          route to it when the recording is ambiguous. For chord changes
          specifically, Strumly&apos;s guide to{" "}
          <a href={STRUMLY.chordTransitions}>smoother chord transitions</a>{" "}
          breaks the motion into the parts worth isolating.
        </p>

        <h3>3. Tempo work, 10 minutes</h3>

        <p>
          This block finds the speed at which the repaired unit falls apart,
          which is the real edge of the skill.
        </p>

        <p>
          Build a ladder: a starting tempo where the unit is genuinely clean,
          the tempo the music actually runs at, and steps between them. Climb
          one step at a time. When the fault reappears, drop two steps, play it
          clean three times, and climb again. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> lays out the steps if
          you would rather not do the arithmetic mid-session.
        </p>

        <p>
          Two rules keep this block honest. The top of the ladder is the
          song&apos;s tempo, not a personal record, because playing faster than
          the music requires is a separate skill and it is not the one that
          finishes your song. And clean at a slow tempo counts for nothing if
          you never climb. The point is to move the break point, not to enjoy
          the bottom rung.
        </p>

        <h3>4. Repertoire under pressure, 15 minutes</h3>

        <p>
          This block proves the repair survives contact with the actual song.
        </p>

        <p>
          Pressure is anything that removes your ability to stop and restart. A
          click. A backing track. One take with no restarts. Standing up.
          Recording. Another person in the room. Pick one constraint and keep it
          for the whole week so the sessions stay comparable.
        </p>

        <p>
          The failure this block catches is specific: the passage is clean in
          isolation and still collapses inside the song, because the bar before
          it and the bar after it were never part of the repair. Play into the
          passage and out of it, not just through it.
        </p>

        <h3>5. The cold-start test, 5 minutes</h3>

        <p>
          This block measures what survives with no runway.
        </p>

        <p>
          Play one piece you claim to know, once, cold, with no practice run and
          no restart. Everyone plays better on the third attempt. The first
          attempt is what you would have on a stage, at a jam, or when someone
          hands you a guitar.
        </p>

        <p>
          Keep a rotating list of four to six cold-start pieces and note two
          things after each: whether you finished, and where it broke. That
          break point becomes a candidate target for the next session, which is
          how the routine feeds itself. The{" "}
          <Link href="/readiness">song readiness score</Link> checks the same
          piece against the parts that usually fail under pressure.
        </p>

        <p>
          This is the cheapest block and the only one that measures anything.
          When the session gets cut short, cut something else.
        </p>

        <h2>The two session lengths, side by side</h2>

        <p>The 50-minute session:</p>

        <ul>
          <li>
            <strong>5 minutes.</strong> Warm-up with intent.
          </li>
          <li>
            <strong>15 minutes.</strong> The one repair target.
          </li>
          <li>
            <strong>10 minutes.</strong> Tempo work on that unit.
          </li>
          <li>
            <strong>15 minutes.</strong> Repertoire under pressure.
          </li>
          <li>
            <strong>5 minutes.</strong> The cold-start test.
          </li>
        </ul>

        <p>The 25-minute session:</p>

        <ul>
          <li>
            <strong>3 minutes.</strong> Warm-up with intent.
          </li>
          <li>
            <strong>10 minutes.</strong> The repair target, with the tempo
            ladder run inside it.
          </li>
          <li>
            <strong>8 minutes.</strong> Repertoire under pressure.
          </li>
          <li>
            <strong>4 minutes.</strong> The cold-start test.
          </li>
        </ul>

        <p>
          Notice what did not happen: the short session is not the long session
          halved. Tempo work merges into repair because both are working the
          same unit. The pressure block absorbs most of the cut because it is
          the block that tolerates being short. The cold-start test gives up one
          minute, because removing it saves almost nothing and costs you the
          only measurement in the session.
        </p>

        <h2>How to swap material in without rebuilding the routine</h2>

        <p>Only the inputs change. The blocks do not.</p>

        <ul>
          <li>
            <strong>Warm-up.</strong> The motion your repair target needs, at a
            tempo where it is clean.
          </li>
          <li>
            <strong>Repair.</strong> The smallest failing unit from last
            session&apos;s pressure block or cold start.
          </li>
          <li>
            <strong>Tempo.</strong> That repaired unit, plus the tempo the song
            actually runs at.
          </li>
          <li>
            <strong>Pressure.</strong> The song the unit belongs to, played
            under the one constraint you kept all week.
          </li>
          <li>
            <strong>Cold start.</strong> The next piece on your rotating list.
          </li>
        </ul>

        <p>
          The repair input is the one that matters. It should come out of your
          own last session, not out of a feed. If you cannot say where this
          week&apos;s target came from, you picked it because it looked
          interesting, and the routine has quietly turned back into lesson
          collecting. Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers the same problem from the routine-design side.
        </p>

        <p>
          Retire a cold-start piece once it survives three cold starts in a row
          and put a harder one in its place. A list you always finish has
          stopped telling you anything.
        </p>

        <h2>What should change week to week</h2>

        <p>
          The blocks hold their shape across a month. The emphasis inside them
          moves.
        </p>

        <ol>
          <li>
            <strong>Week 1.</strong> Record a baseline before deciding anything.
            The repair target is whatever that recording exposes, not what you
            assumed on the way to the guitar.
          </li>
          <li>
            <strong>Week 2.</strong> Same target, bigger unit. Two bars become
            the phrase; the phrase becomes the section it sits in.
          </li>
          <li>
            <strong>Week 3.</strong> The target moves to the seams, meaning the
            bar before and the bar after. Pressure gets the longest block this
            week.
          </li>
          <li>
            <strong>Week 4.</strong> No new repair. The session is pressure and
            cold start only. Record the final take beside the baseline and name
            the change the two recordings actually support.
          </li>
        </ol>

        <p>
          Change one variable at a time. If you swap the target, the tempo
          ceiling, and the song in the same week, the routine can no longer tell
          you which change did anything.
        </p>

        <p>
          Three signals say a target has finished its work: the error rate stops
          dropping across two consecutive sessions, the unit stays clean at the
          song&apos;s tempo for three sessions running, or the cold-start test
          starts breaking somewhere else. Any one of them means pick a new
          target. Two of them mean you should have picked one already.
        </p>

        <h2>The ten-minute day</h2>

        <p>
          Do not run all five blocks at two minutes each. A two-minute repair
          block is not practice, it is a checklist you ticked.
        </p>

        <p>A ten-minute day is a repair day:</p>

        <ul>
          <li>
            <strong>2 minutes.</strong> Warm up on the exact motion the target
            needs.
          </li>
          <li>
            <strong>6 minutes.</strong> The repair unit, recorded, and nothing
            else.
          </li>
          <li>
            <strong>2 minutes.</strong> One cold start, one piece, no second
            attempt.
          </li>
        </ul>

        <p>
          The tempo ladder and the pressure block are gone for the day, and that
          is correct. Both need enough repetitions to mean something, and
          neither survives being handed ninety seconds.
        </p>

        <p>
          Mark the session short in whatever you use to log it. A week with
          three ten-minute days and two full sessions is a fine week, but if the
          log does not say so, you will read the flat cold-start results as a
          plateau instead of as a short week.
        </p>

        <h2>Questions about this routine</h2>

        {FAQS.map((faq) => (
          <section key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </section>
        ))}
      </Article>
    </>
  );
}
