import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import {
  GUIDES,
  OG_IMAGE,
  SITE_URL,
  STRUMLY,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";

const CANONICAL = `${SITE_URL}/how-long-to-practice-guitar-each-day`;
const PUBLISHED = "2026-08-29";

const TITLE = "How Long Should You Practice Guitar Each Day?";
const DESCRIPTION =
  "Duration is the wrong variable and attention is the right one. How to tell when a session stopped working, plus shapes for 10, 25 and 60 minutes.";

export const metadata: Metadata = {
  title: `${TITLE} | GuitarHub`,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Related links are resolved from the route registry by href, so titles and
 * blurbs live in exactly one place. An href the registry does not know is
 * dropped rather than rendered with invented text — which also means a route
 * added to `lib/site.ts` later starts appearing here on its own.
 */
const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/session",
  "/guitar-practice-routine-intermediate",
  "/how-to-practice-guitar-effectively",
  "/tempo",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

/**
 * Rendered as the visible Q&A section AND serialised into the FAQPage node
 * below, from this one array. Schema.org requires the marked-up answer to
 * appear on the page, so generating both from one source is the only way to
 * keep them identical after an edit. Plain strings: no links, no markup.
 */
const FAQS = [
  {
    q: "Is 30 minutes a day enough to get good at guitar?",
    a: "Thirty attentive minutes a day is enough to keep moving, and for most players it is more than they currently get. It does not set the ceiling; the goal does that. Thirty minutes aimed at one passage will fix that passage, and the same thirty spread across five ambitions will fix none of them.",
  },
  {
    q: "Should I practice every day, or take rest days?",
    a: "Most days is the better default. The limit on a session is attention rather than tissue recovery, so a day off is a scheduling decision and not a physical requirement. Pain is the exception: hand, wrist or forearm pain is a reason to stop and get it looked at, not to practice through.",
  },
  {
    q: "Does two hours a day improve you twice as fast as one?",
    a: "No, because the attentive part of two hours is not twice the attentive part of one. Past the point where you can tell a clean repetition from a dirty one, the extra time rehearses the mistake instead of removing it. If you have two hours, split them and give the halves different jobs.",
  },
  {
    q: "How long until I hear progress?",
    a: "That depends on the goal, and no honest answer arrives in weeks. What you can do is make the answer checkable: record one passage today, work on it for four weeks, record it the same way again, and listen to both. That comparison settles it where a general number cannot.",
  },
] as const;

// The canonical estate @ids, copied from app/layout.tsx. Referenced rather than
// redefined: the Organization and Person nodes are already declared once in the
// root layout, which renders on this page too.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: TITLE,
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without it
      // the page is not eligible for an Article rich result. Every route serves
      // the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${SITE_URL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: PUBLISHED,
      inLanguage: "en-US",
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

export default function HowLongToPracticePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        eyebrow="GuitarHub guide"
        title={
          <>
            How long should you practice guitar{" "}
            <em className="font-display italic text-peach">each day?</em>
          </>
        }
        dek="Duration is the wrong variable. Here is the right one, how to tell when a session has stopped working, and what to do with 10, 25 or 60 minutes."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          There is no correct number of minutes. Duration is the wrong variable;
          attention is the right one. A focused twenty minutes changes your
          playing more than an unfocused two hours, because practice only moves
          what you are paying attention to. Practice as long as you can stay
          specific about what you are fixing, then stop.
        </p>

        <p>
          If you want a number to start from, take twenty to forty minutes on
          most days over ninety minutes twice a week. Not because short sessions
          are special. Because a repair has to survive a night&apos;s sleep before
          you know it held, and the only way to run that test often is to
          practice often.
        </p>

        <h2>The limit is concentration, not fingers</h2>

        <p>
          Ask a player why they stopped and the answer is usually physical: tired
          hand, sore fingertips. Sore fingertips are real in the first few weeks
          and stop being the limit after that. What runs out first, for nearly
          everyone past that stage, is the ability to hold one specific target in
          mind and evaluate each attempt against it.
        </p>

        <p>
          That evaluation is the expensive part of a session and the part that
          does the work. A repetition you did not evaluate still taught you
          something, just not the thing you chose. An hour of unevaluated
          repetition teaches you whatever your hands happened to do.
        </p>

        <p>
          So the useful question is not how many minutes you can sit with the
          instrument. It is how many minutes you can stay specific.{" "}
          <em>The third finger lands late on the C, listen for it, fix it</em> is
          practice. <em>Run the song again</em> is a fine way to spend an evening
          and a poor way to fix a bar.
        </p>

        <h2>How to tell a session has stopped producing change</h2>

        <p>
          Sessions rarely end. They decay, and the decay is hard to notice from
          inside because it feels exactly like continuing. Any one of these tells
          can be a bad minute; two at once means the useful part of the session
          is behind you.
        </p>

        <ul>
          <li>
            <strong>You cannot say what you are fixing.</strong> Answer out loud.
            If it takes more than a second, or comes out as the name of a song
            rather than a location inside it, you are no longer aiming at
            anything.
          </li>
          <li>
            <strong>Repetitions stop getting a verdict.</strong> Early on you
            know instantly whether a pass was clean. Later the pass ends and you
            have no opinion. That is the evaluation shutting down, and it shuts
            down well before the hands do.
          </li>
          <li>
            <strong>A mistake you had fixed comes back.</strong> Not a new one —
            the old one, returning. You have dropped below the attention the fix
            requires, and every repetition from here argues with it.
          </li>
          <li>
            <strong>You drift toward what already works.</strong> The bar you
            came to repair gets shorter run-ups and the intro gets longer ones.
            Nobody decides to do this.
          </li>
          <li>
            <strong>You raise the tempo out of boredom.</strong> The honest
            reason to move up a rung is that the current one is clean and cold.
            Being tired of it is a different reason wearing the same clothes.
          </li>
          <li>
            <strong>You start negotiating.</strong>{" "}
            <em>One more good one and I will stop</em>, said twice, is a coin
            flip you keep re-flipping.
          </li>
        </ul>

        <p>
          When two of those show up, stop. Stopping is the last measurement you
          take: a session that ends while you can still tell a clean pass from a
          dirty one ends with a result, and one that runs past that point ends
          with a fog.
        </p>

        <h2>Why long sessions can move you backwards</h2>

        <p>
          A practice session does not record your intentions. It records what
          your hands actually did, and it weights the late repetitions as heavily
          as the early ones. In the last stretch of a long session, what your
          hands do is the sloppy version. You are not failing to make progress
          there; you are making progress on the wrong take. That is why a
          two-hour night can leave a passage worse than it was at the
          forty-minute mark.
        </p>

        <p>
          There is a second cost, harder to see. A long session produces a strong
          memory of effort, and that memory buys patience with an approach that
          is not working. Three weeks of twenty-five-minute sessions are easy to
          abandon when the recording says they did nothing. Three weeks of
          two-hour nights are not.
        </p>

        <p>
          The check takes ninety seconds and is worth running on any session past
          about forty minutes. Before you pack up, play the thing you were
          repairing once, cold. If it is worse than it was mid-session, the last
          stretch cost you something, and tomorrow should be shorter.
        </p>

        <h2>Three session shapes</h2>

        <p>
          Time is the one budget you know in advance, so it is the sensible thing
          to plan against. All three shapes assume you already know your repair
          target. If you do not, the{" "}
          <Link href="/method">GuitarHub method</Link> covers how the target gets
          chosen and how you know when it is finished.
        </p>

        <p>
          Ten, twenty-five and sixty are the common sizes, not the only ones.
          For a number that is none of those, the{" "}
          <Link href="/session">practice session builder</Link> splits whatever
          minutes you have into blocks that total exactly that length, weighted
          toward the one thing you named as broken. On a short evening it drops
          the blocks whose share came out too small to be worth starting, rather
          than shrinking all of them into setup time, and it tells you which
          ones went and why.
        </p>

        <h3>Ten minutes: one repair, recorded</h3>

        <p>
          Do not run a miniature version of your full routine. Five blocks at two
          minutes each is a checklist you ticked.
        </p>

        <ul>
          <li>
            <strong>2 minutes.</strong> The exact motion the target needs. Not
            general warm-up — that motion.
          </li>
          <li>
            <strong>6 minutes.</strong> The repair unit alone, at a tempo where
            you are correct on purpose rather than correct by luck.
          </li>
          <li>
            <strong>2 minutes.</strong> One cold pass of the passage in context,
            recorded, no second attempt.
          </li>
        </ul>

        <p>
          The recording is what makes ten minutes count. Without it a short day
          leaves no trace, and a week of short days reads back as a plateau
          rather than a short week.
        </p>

        <h3>Twenty-five minutes: repair, then pressure</h3>

        <ul>
          <li>
            <strong>3 minutes.</strong> The motion.
          </li>
          <li>
            <strong>12 minutes.</strong> The repair unit, tempo work folded into
            it. One target, not three. If you are climbing speeds, the{" "}
            <Link href="/tempo">tempo ladder builder</Link> decides which rung
            this session owns, so you are not deciding it while tired.
          </li>
          <li>
            <strong>7 minutes.</strong> The repaired part back inside the music,
            at a tempo where the whole passage survives rather than the fragment.
          </li>
          <li>
            <strong>3 minutes.</strong> One cold pass, recorded.
          </li>
        </ul>

        <p>
          Twenty-five is the shape most weekday sessions should take: long enough
          to repair something and test the repair in one sitting, short enough
          that your evaluation still works at the test.
        </p>

        <h3>Sixty minutes: two sessions, not one</h3>

        <p>
          An hour is not a longer version of twenty-five minutes. Treat it as two
          sessions with a real break between them: put the guitar down, leave the
          room, five to ten minutes.
        </p>

        <ul>
          <li>
            <strong>First half.</strong> Repair, exactly as above, on one target.
          </li>
          <li>
            <strong>The break.</strong> Load-bearing, not optional. Without it
            the second half is the decayed tail of the first.
          </li>
          <li>
            <strong>Second half.</strong> A different job: repertoire, the whole
            piece, new material, or a second target that uses a different skill.
          </li>
        </ul>

        <p>
          Changing jobs is the point of the break: the first target has had all
          the attention it can use today, and another twenty minutes on it is
          repetition without evaluation. If both halves have to be repair, make
          the second structurally different — a timing problem after a
          fretting-hand problem.
        </p>

        <h2>When a long session is the right call</h2>

        <p>
          None of this makes long sessions bad. It makes them bad at one job.
          Repair — slow, evaluated, one passage at a time — degrades with
          duration. Plenty of guitar work does not.
        </p>

        <ul>
          <li>
            <strong>Playing.</strong> Ninety minutes of songs you already know is
            not practice and does not need to be. It is why most people picked up
            the instrument.
          </li>
          <li>
            <strong>Learning new material.</strong> Reading through a piece,
            working out an arrangement, finding fingerings. Exploratory work
            tolerates length far better than repair.
          </li>
          <li>
            <strong>Stamina.</strong> If the goal involves a forty-minute set,
            at some point you have to play for forty minutes without stopping.
          </li>
          <li>
            <strong>Playing with other people.</strong> A rehearsal runs as long
            as it runs, and what it builds — listening, holding your part,
            recovering mid-song — is not available alone in a room.
          </li>
        </ul>

        <p>
          The mistake is counting those hours as practice and then wondering why
          the stuck bar is still stuck. Keep them in a separate column: a week
          with four hours of playing and eighty minutes of repair is a good week,
          and the eighty minutes is what moves the bar.
        </p>

        <h2>Days with almost no time</h2>

        <p>
          Some days you have four minutes between two obligations. Four minutes
          beats zero, but only if all four go to one thing.
        </p>

        <ul>
          <li>
            <strong>3 minutes.</strong> The single hardest join in what you are
            working on, slowly, correctly. Nothing else gets touched.
          </li>
          <li>
            <strong>1 minute.</strong> One cold pass of it, no retries, so the
            day produces a verdict instead of a feeling.
          </li>
        </ul>

        <p>
          Skip the warm-up, skip repertoire, skip the ladder: each needs more
          repetitions than four minutes contains.
        </p>

        <p>
          On a day with genuinely no minutes, the useful move is not a guilty two
          minutes with the guitar on your lap. It is thirty seconds with a note:
          write tomorrow&apos;s target in a sentence containing a location.
          Choosing the target is the one part of practice that is easier away
          from the instrument.
        </p>

        <h2>Making the number stick</h2>

        <p>
          Two counts matter more than session length: how many days a week you
          pick up the instrument, and how many end with a recorded verdict.
          Session length is what you adjust to protect those two. A forty-minute
          session that costs you the next two days was not really forty minutes.
        </p>

        <p>
          For the weekly structure this sits inside — which blocks get cut first
          when the clock shrinks — see the{" "}
          <Link href="/guitar-practice-routine-intermediate">
            intermediate practice routine
          </Link>
          . For what to do inside the repair block once you are in it,{" "}
          <Link href="/how-to-practice-guitar-effectively">
            how to practice guitar effectively
          </Link>{" "}
          is the companion piece to this one.
        </p>

        <p>
          Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          takes the same problem from the scheduling side, and it has a companion
          piece on{" "}
          <a href={STRUMLY.aiCoach}>practicing guitar with an AI coach</a>.
        </p>

        <h2>Common questions</h2>

        {FAQS.map((item) => (
          <Fragment key={item.q}>
            <h3>{item.q}</h3>
            <p>{item.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
