import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  ARTICLE_AUTHOR,
  GUIDES,
  LEARN,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/guitar-finger-pain`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "Sore fingertips and hand pain from guitar: what to do";

const DESCRIPTION =
  "Why fingertips hurt when you start guitar, how calluses form, how to press lighter, the setup fixes that help, and the pain signals that mean stop and get checked.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Sore fingertips and hand pain", href: "/guitar-finger-pain" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/guitar-finger-pain"),
  title: "Guitar Finger Pain: Sore Fingertips, Calluses, Hand Pain | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // No `images` key: Next attaches the colocated opengraph-image.tsx card
    // only when the page leaves `images` unset.
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Should I keep playing with sore fingertips?",
    a: "Tender fingertips in your first weeks are expected, and short sessions through mild tenderness are how calluses form. Stop for the day when a fingertip feels hot, stinging or raw, or when a blister starts. Never play through a blister. Pain anywhere other than the fingertip pads is a different matter: stop and read the warning signs on this page.",
  },
  {
    q: "How long until my fingers stop hurting?",
    a: "For most players who practice briefly and often, the sharp soreness eases within the first few weeks, and calluses keep thickening for months after that. Long gaps reset part of the progress, because calluses soften when you stop playing. Daily short sessions get you through this stage fastest.",
  },
  {
    q: "Do nylon strings hurt less than steel strings?",
    a: "Yes. Nylon strings on a classical guitar sit at lower tension and are softer under the fingertip, so most beginners find them gentler. Lighter-gauge steel strings and a professional setup also reduce the pressure each note needs.",
  },
  {
    q: "Is it normal for my wrist or thumb to hurt after playing?",
    a: "No. Fingertip tenderness is normal; aching in the wrist, thumb, forearm or elbow is a warning sign that something in your posture, grip or guitar setup is overloading the hand. Rest it, check your thumb pressure and wrist angle, and if the pain is still there after a day or two of rest, see a doctor or a hand therapist.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/beginner-guitar-practice-routine",
  "/how-to-play-barre-chords",
  "/session",
  "/coming-back-to-guitar",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/guitar-finger-pain"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${CANONICAL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: ARTICLE_AUTHOR,
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function GuitarFingerPainPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/guitar-finger-pain"
        crumbs={CRUMBS}
        title={
          <>
            Sore fingertips, hand pain, and{" "}
            <em className="font-display italic text-peach">when to stop.</em>
          </>
        }
        dek="Tender fingertips in the first weeks are part of learning guitar. Pain anywhere else is information. Here is how to tell them apart and what to change."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          Sore fingertips are normal when you start guitar or come back after a
          break. Steel strings press the skin of your fingertip pads into the
          fret wire, and the skin responds by toughening into calluses over the
          first weeks of regular playing. Keep sessions short and frequent, press
          only as hard as the note needs, and have the guitar set up so the
          strings sit low. Sharp pain, numbness, tingling, or pain in your wrist,
          thumb, forearm or elbow is a different thing. Stop playing and, if it
          does not settle with rest, see a doctor or a hand therapist.
        </p>

        <h2>The safety rule, first</h2>

        <p>
          Tenderness on the pads of the fretting fingertips is expected. These
          are stop signals:
        </p>

        <ul>
          <li>Sharp, stabbing or burning pain anywhere in the hand or arm.</li>
          <li>
            Numbness, tingling, or pins and needles in the fingers or thumb.
          </li>
          <li>
            Aching in the wrist, thumb base, forearm, elbow or shoulder that is
            still there the next day.
          </li>
          <li>Swelling, or a joint that looks or feels different.</li>
          <li>A finger that catches, clicks or locks as it bends.</li>
          <li>Weaker grip, or fingers that stop doing what you tell them.</li>
          <li>
            A blister or cracked fingertip that turns red, hot, swollen or
            weeps.
          </li>
        </ul>

        <p>
          If any of these appear, stop playing for the day. If they persist
          after rest, or come back each time you play, book an appointment with
          your doctor, a sports medicine clinic, or a hand therapist (an
          occupational or physical therapist who specializes in hands). Some
          clinics specialize in performing arts medicine and treat musicians
          every day. Do not use painkillers to keep playing through pain. Pain
          is the signal that tells you what to change.
        </p>

        <h2>Why fingertips hurt at the start</h2>

        <p>
          To sound a note, you press a string until it touches the fret. The
          string is a thin steel wire under tension, and all that force lands on
          a small patch of skin. The skin on an untrained fingertip is not built
          for it, so it gets tender, and if you overdo it, it blisters.
        </p>

        <p>
          With repeated, moderate pressure, the outer layer of skin thickens
          into calluses. Calluses spread the load and make pressing painless.
          The key word is moderate. Too little playing and the skin never
          adapts. Too much at once and you get a blister, which forces days off
          and sends you back toward the start.
        </p>

        <h2>The callus timeline</h2>

        <p>
          For most players who practice a little every day, the first week is
          the most tender, the sharp soreness fades over the following few
          weeks, and the calluses keep developing for months. Calluses soften
          when you stop playing, which is why a two-week break feels like a
          partial restart and why returning players feel it too.
        </p>

        <p>
          The fastest route through this stage is frequency, not volume:
        </p>

        <ul>
          <li>
            <strong>Play 10 to 15 minutes, two or three times a day</strong>{" "}
            in the first weeks, instead of one long session. The <Link href="/session">practice session builder</Link> turns a short window into timed blocks so a ten-minute session still covers the important work.
          </li>
          <li>
            <strong>Stop at the first sign of heat or stinging</strong> in a
            fingertip. That is the point just before a blister.
          </li>
          <li>
            <strong>Leave blisters alone.</strong> Do not pop them and do not
            play on them. Let them heal fully before you play on that finger
            again.
          </li>
          <li>
            <strong>Do not peel or bite calluses.</strong> If a callus develops
            a rough edge that snags strings, smooth it gently with a fine nail
            file.
          </li>
          <li>
            <strong>Keep fretting-hand nails short</strong>, so you can press
            with the fingertip pad instead of the soft part further back.
          </li>
          <li>
            <strong>Play before a long shower or dishes, not straight after.</strong>{" "}
            Skin softened by hot water wears faster under the strings.
          </li>
        </ul>

        <h2>Press less: the minimum-pressure test</h2>

        <p>
          Most beginners press several times harder than a note needs, and the
          extra force goes straight into the fingertip, the thumb and the wrist.
          Find the real number with this test:
        </p>

        <ol>
          <li>
            Fret a single note, for example string 3 at fret 2, and pick it
            repeatedly in a slow, steady rhythm.
          </li>
          <li>
            Gradually ease off the pressure until the note starts to buzz or
            choke.
          </li>
          <li>
            Add back just enough pressure for a clear note. That is all the note
            needs.
          </li>
          <li>Repeat on each finger, then on a whole chord.</li>
        </ol>

        <p>
          Two placement details reduce the pressure further. Put the fingertip
          just behind the fret wire, not in the middle of the space between
          frets: the closer you are to the fret, the less force a clean note
          takes. And press with the tip of the finger, keeping the finger
          arched instead of letting it collapse flat.
        </p>

        <p>
          Watch the thumb. A thumb clamped hard against the back of the neck is
          a common source of aching at the base of the thumb and in the web
          of the hand. The thumb is a counterweight, not a vise. On an
          electric guitar with a strap, or when seated with the guitar resting
          against your body, you can let the weight of your arm draw the
          fingers into the strings, which takes most of the load off the thumb.
        </p>

        <h2>Fix the guitar, not just the hand</h2>

        <p>
          A guitar with high strings makes every note harder to press, and
          plenty of entry-level guitars leave the factory that way. A setup by a
          guitar technician adjusts the neck, the string height at the bridge,
          and the nut, and is one of the best-value changes a beginner can make.
        </p>

        <ul>
          <li>
            <strong>High action.</strong> If there is a visible gap between the
            strings and the frets up the neck, the action is likely high. A tech
            measures and lowers it.
          </li>
          <li>
            <strong>High nut slots.</strong> If chords near the headstock are
            much harder than the same shapes higher up, try a capo at fret 1. If
            the first-position chords suddenly feel easy, the nut slots are a
            likely cause, and a tech can lower them.
          </li>
          <li>
            <strong>String gauge.</strong> Lighter strings need less force. On
            an acoustic, a set labeled extra light or custom light is gentler
            than the common light gauge. Ask the tech to adjust the setup for the
            new strings.
          </li>
          <li>
            <strong>Old strings.</strong> Corroded strings feel rough and wear
            fingertips faster. Fresh strings feel smoother.
          </li>
          <li>
            <strong>Nylon strings.</strong> A classical guitar with nylon
            strings is much softer on the fingertips, and is a good choice for
            a player whose fingertips are the main obstacle.
          </li>
        </ul>

        <h2>Warm up the whole hand</h2>

        <p>
          A short warm-up spreads the load before you ask the hand for barre
          chords or long stretches. Three to five minutes is enough:
        </p>

        <ol>
          <li>
            Open and close both hands slowly ten times, then let the arms hang
            and shake out loosely.
          </li>
          <li>
            Play a slow chromatic pattern on one string, frets 1, 2, 3 and 4
            with fingers 1, 2, 3 and 4, at 60 BPM on the <Link href="/practice">metronome</Link>, using the lightest pressure that gives a clean note.
          </li>
          <li>
            Strum a few easy open chords before any barre chord or stretch.
          </li>
        </ol>

        <p>
          Posture matters as much as the warm-up. Keep the fretting wrist as
          close to neutral as the chord allows rather than sharply bent, keep the
          shoulders down, and take a short break every 20 to 30 minutes in longer
          sessions. When seated, a footstool or a strap set so the guitar sits
          at the same height as when you stand keeps the neck where your hand
          can reach it without the wrist folding.
        </p>

        <h2>Barre chords are the next sore spot</h2>

        <p>
          The first barre chords bring a new kind of soreness: the side of the
          index finger and the base of the thumb. The fix is leverage rather
          than grip strength, and the <Link href="/how-to-play-barre-chords">barre chord guide</Link> covers it step by step. Aching that spreads into the wrist or forearm during barre practice is one of the stop signals above, not a sign to push harder.
        </p>

        <h2>Coming back with a smaller dose</h2>

        <p>
          When you return after a blister, a sore week, or years away, start
          lower than feels necessary: two short sessions a day, easy chords,
          and the minimum-pressure test at the start of each one. The <Link href="/coming-back-to-guitar">guide to coming back to guitar</Link> lays out the first 30 days, and the <Link href="/beginner-guitar-practice-routine">beginner practice routine</Link> uses the same short daily blocks for the first 90.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
