import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  ARTICLE_AUTHOR,
  GUIDES,
  LEARN,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/learn-guitar-fretboard-notes`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "Learn the guitar fretboard notes, then connect them with CAGED";

const DESCRIPTION =
  "Learn every note on the guitar fretboard in four steps: the musical alphabet, strings 6 and 5, octave shapes, then the five CAGED chord shapes in order.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Fretboard notes and CAGED", href: "/learn-guitar-fretboard-notes" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/learn-guitar-fretboard-notes"),
  title: "Learn the Guitar Fretboard Notes and the CAGED System | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // No `images` key: Next attaches the colocated opengraph-image.tsx card
    // only when the page leaves `images` unset.
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "How long does it take to learn the notes on the fretboard?",
    a: "Strings 6 and 5 come first and come fastest, because every movable chord and scale shape is placed from a root on one of them. Give them a few minutes every day for two weeks before adding octave shapes. The full neck builds over the following weeks as you use the octave shapes and one-note-everywhere drill daily.",
  },
  {
    q: "Do I need to learn sharps and flats too?",
    a: "Learn the natural notes first. Every sharp or flat is one fret away from a natural: the fret above a note is its sharp, and the fret below is its flat. Once the naturals are instant, the sharps and flats come for free.",
  },
  {
    q: "Is the CAGED system necessary?",
    a: "It is a widely taught map for connecting chord shapes, arpeggios and scale positions across the whole neck. You can learn the notes without it, and CAGED is far more useful once you know the notes, because it tells you where each shape's roots are.",
  },
  {
    q: "Should I learn the notes or the scales first?",
    a: "Start with the notes on strings 6 and 5, then learn scales. A scale shape is much easier to move to a new key when you can put its root on the right fret immediately.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/advanced",
  "/how-to-play-barre-chords",
  "/how-to-practice-guitar-scales",
  "/how-to-practice-guitar-improvisation",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/learn-guitar-fretboard-notes"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${CANONICAL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: ARTICLE_AUTHOR,
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function LearnGuitarFretboardNotesPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/learn-guitar-fretboard-notes"
        crumbs={CRUMBS}
        title={
          <>
            Learn the notes on the fretboard,{" "}
            <em className="font-display italic text-peach">
              then connect them with CAGED.
            </em>
          </>
        }
        dek="Two facts, two strings, four octave shapes and five chord shapes. That is the whole map, learned a few minutes a day."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To learn the notes on the guitar fretboard, start with the musical
          alphabet and its two half steps, then learn the natural notes on
          string 6 and string 5 until you can name any of them instantly. Use
          octave shapes to carry those names to the other four strings, and
          drill one note in every position until the neck reads as a set of
          repeating patterns. Finally, connect the positions with the CAGED
          system: the five open chord shapes C, A, G, E and D, which link up the
          neck in that order. Five minutes a day, testing yourself without a
          diagram, does more than an hour of staring at a chart.
        </p>

        <h2>The two facts the whole neck runs on</h2>

        <p>
          Music uses seven letter names: A, B, C, D, E, F, G, then back to A.
          Between most neighboring letters there is a whole step, which on
          guitar is two frets. There are exactly two exceptions: B to C and E to
          F are half steps, one fret apart. There is no sharp between them.
        </p>

        <p>
          The second fact: twelve frets make an octave. The note at fret 12 has
          the same name as the open string, an octave higher, and the pattern
          from fret 12 to fret 24 repeats the pattern from the open string to
          fret 12. Learn frets 0 to 12 and you know the whole neck.
        </p>

        <p>
          Everything in between follows from those two facts. The fret above any
          natural note is its sharp, and the fret below is its flat, so the note
          at fret 6 on string 6 is called both A sharp and B flat.
        </p>

        <h2>Step 1: string 6 and string 5</h2>

        <p>
          Start with the two lowest strings, because every movable chord and
          scale shape is placed from a root on one of them. The natural notes
          are:
        </p>

        <ul>
          <li>
            <strong>String 6 (low E):</strong> E at the open string, F at fret
            1, G at 3, A at 5, B at 7, C at 8, D at 10, and E again at 12.
          </li>
          <li>
            <strong>String 5 (A):</strong> A open, B at 2, C at 3, D at 5, E at
            7, F at 8, G at 10, and A again at 12.
          </li>
        </ul>

        <p>
          Use the fret markers as landmarks. Most guitars have dots at frets 3,
          5, 7, 9 and 12. On string 6 that gives you G, A, B, C sharp and E, and
          on string 5, C, D, E, F sharp and A. Anchor the naturals to those
          dots and the gaps fill in.
        </p>

        <p>
          The <Link href="/advanced/musical-alphabet-low-e">musical alphabet on one string drill</Link> walks string 6 from the open string to fret 12 and back, and listens to each note through your microphone. Then the <Link href="/advanced/movable-shape-roots">first movable shape drill</Link> calls out chord names and has you find each root on string 6 or 5, the way you place a power chord or barre chord.
        </p>

        <h2>Step 2: octave shapes carry the names everywhere</h2>

        <p>
          You do not memorize strings 4 to 1 note by note. You reach them from
          strings 6 and 5 with octave shapes, which are fixed distances that
          always land on the same note name.
        </p>

        <ul>
          <li>
            <strong>From string 6:</strong> skip one string to string 4 and go
            up two frets. G at string 6, fret 3 is also G at string 4, fret 5.
          </li>
          <li>
            <strong>From string 5:</strong> skip one string to string 3 and go
            up two frets. C at string 5, fret 3 is also C at string 3, fret 5.
          </li>
          <li>
            <strong>From string 4:</strong> skip one string to string 2 and go
            up three frets. E at string 4, fret 2 is also E at string 2, fret 5.
            The extra fret comes from the B string, which is tuned a major third
            above the G string while every other neighboring pair is a fourth
            apart.
          </li>
          <li>
            <strong>From string 3:</strong> skip one string to string 1 and go
            up three frets, for the same reason. A at string 3, fret 2 is also A
            at string 1, fret 5.
          </li>
          <li>
            <strong>Strings 6 and 1:</strong> both are E strings, two octaves
            apart, so every fret has the same note name on both.
          </li>
        </ul>

        <p>
          With those five rules, knowing strings 6 and 5 means you can find any
          note on any string in one move.
        </p>

        <h2>Step 3: one note, everywhere</h2>

        <p>
          Now turn the map around. Instead of naming the note under your finger,
          pick a note and find every place it lives between the open strings
          and fret 12. C, for example, sits at string 5 fret 3, string 3 fret 5,
          string 2 fret 1, string 6 fret 8, string 4 fret 10, and string 1 fret
          8, among others.
        </p>

        <p>
          The <Link href="/advanced/every-c">Find Every C drill</Link> runs exactly this, across three octaves, and checks the pitch and octave of each note you play. Once C is automatic, do the same with one new note each day. A good order is the cycle of fourths, C, F, B flat, E flat, A flat, D flat, G flat, B, E, A, D, G, because it walks through every note and matches how many chord progressions move.
        </p>

        <p>
          Test yourself rather than reviewing. In a 2006 study, Henry Roediger
          and Jeffrey Karpicke found that students who practiced recalling a
          passage remembered more of it a week later than students who spent
          the same time rereading it. On the fretboard, that means naming notes
          from memory and checking afterward, not reading them off a chart.
        </p>

        <h2>Step 4: CAGED connects the shapes</h2>

        <p>
          The CAGED system takes the five open chord shapes, C, A, G, E and D,
          and treats each one as a movable shape. Your index finger, or a barre,
          takes over the job of the nut, and the shape can then be played
          anywhere on the neck. The five shapes fit together up the neck in the
          order of the name, C, A, G, E, D, and then the cycle repeats an octave
          higher.
        </p>

        <p>
          Here is C major played five ways, moving up the neck:
        </p>

        <ol>
          <li>
            <strong>C shape, open position:</strong> x32010. Root on string 5,
            fret 3.
          </li>
          <li>
            <strong>A shape, barre at fret 3:</strong> x35553. Root on string 5,
            fret 3.
          </li>
          <li>
            <strong>G shape, around frets 5 to 8:</strong> 875558. Roots on
            string 6 fret 8, string 3 fret 5 and string 1 fret 8.
          </li>
          <li>
            <strong>E shape, barre at fret 8:</strong> 8 10 10 9 8 8. Root on
            string 6, fret 8.
          </li>
          <li>
            <strong>D shape, around frets 10 to 13:</strong> xx 10 12 13 12.
            Root on string 4, fret 10.
          </li>
        </ol>

        <p>
          After the D shape, the C shape returns at fret 12, an octave above
          where you started. Every major chord works the same way. For G, the
          cycle starts on a different letter but keeps the order: the open G
          shape, the E shape barred at fret 3, the D shape at fret 5, the C shape
          around frets 7 to 10, and the A shape barred at fret 10.
        </p>

        <p>
          The full G and C shapes are awkward to fret as complete chords higher
          up the neck, and players often use partial versions of them. Their
          real value is as a map: each shape tells you where the roots, thirds
          and fifths of the chord sit in that region of the neck, and each one
          sits inside a position of the major scale. That is what connects
          chords, arpeggios and scales into one picture.
        </p>

        <p>
          The E and A shapes are the two barre chords most players learn first,
          and the <Link href="/how-to-play-barre-chords">barre chord guide</Link> covers them in detail. Stage 6 of the <Link href="/learn/guitar">GuitarHub guitar curriculum</Link>, Whole Neck, teaches both barre shapes in every position along with the major scale in five positions.
        </p>

        <h2>A ten-minute daily fretboard session</h2>

        <ol>
          <li>
            <strong>2 minutes:</strong> name the natural notes on string 6, then
            string 5, up and back, out loud, without looking at a chart.
          </li>
          <li>
            <strong>3 minutes:</strong> today&apos;s note, everywhere from the
            open strings to fret 12, using the octave shapes to jump between
            strings.
          </li>
          <li>
            <strong>3 minutes:</strong> one major chord through all five CAGED
            shapes, saying the shape name as you play it.
          </li>
          <li>
            <strong>2 minutes:</strong> random calls. Pick a string and a note
            name at random and find it. Use a <Link href="/practice">metronome</Link> at 40 BPM and aim to land each note on the next click.
          </li>
        </ol>

        <p>
          The click turns recall into a timed test, and timed recall is what
          you need in a song, where the next chord does not wait for you to
          count up from the nut.
        </p>

        <p>
          With the notes and shapes in place, the <Link href="/how-to-practice-guitar-scales">scale practice guide</Link> turns positions into music, and the <Link href="/how-to-practice-guitar-improvisation">improvisation guide</Link> uses the same roots and chord tones to make up phrases over chords.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
