import type { Metadata } from "next";
import Link from "next/link";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, STRUMLY, TOOLS, type SiteEntry } from "@/lib/site";

const CANONICAL = "https://guitarhub.org/deliberate-practice-guitar";

const DESCRIPTION =
  "Deliberate practice on guitar means one target you cannot hit yet, a difficulty where you keep missing, and honest feedback on every attempt.";

export const metadata: Metadata = {
  title: "Deliberate Practice on Guitar | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: "Deliberate Practice on Guitar",
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

// Same canonical @ids the root layout defines, so this Article attaches to the
// existing Suede Labs Organization and founder Person rather than minting
// duplicate entities for the same two things.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

/**
 * Rendered twice: once as the visible "Common questions" section, once as the
 * FAQPage node below. Keeping the strings in one place is what guarantees the
 * structured data matches the page text verbatim.
 */
const FAQ = [
  {
    q: "Is deliberate practice just practicing slowly?",
    a: "No. Slowing down is one way to reach the edge, and often the right one, but a slow repetition with no target and no feedback is still just a repetition. What matters is whether each attempt is aimed at something specific and checked afterward, not the number on the metronome.",
  },
  {
    q: "How long should a deliberate practice block be?",
    a: "Short enough that your attention holds for the whole of it. Twenty minutes on one target is a reasonable place to start, less on a tired day. When you stop hearing your own mistakes, the block is finished, whatever the clock says.",
  },
  {
    q: "Can you practice deliberately without a teacher?",
    a: "Yes, but you have to replace what a teacher supplies: a target chosen for you, an honest read on each attempt, and a decision about what to change next. The target and the decision you can supply yourself. The honest read is the part to hand off, to a recording, to a metronome, or to software that listens while you play.",
  },
  {
    q: "Does this mean playing for fun is a waste of practice time?",
    a: "No. Playing is the reason for the practice, and it is how songs settle into your hands. The two just do different jobs, so a week containing only one of them gets only one of the two results.",
  },
] as const;

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: "Deliberate Practice on Guitar",
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without
      // it the page is not eligible for an Article rich result. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: "2026-08-29",
      dateModified: "2026-08-29",
      inLanguage: "en-US",
      isAccessibleForFree: true,
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: CANONICAL,
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQ.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

// Pulled from the route registry so titles and blurbs stay in sync with the
// footer and the sitemap instead of drifting into a second copy here.
const RELATED_HREFS = [
  "/how-to-practice-guitar-effectively",
  "/guitar-practice-plateau",
  "/tempo",
  "/diagnose",
] as const;

const RELATED = RELATED_HREFS.map((href) =>
  [...GUIDES, ...TOOLS].find((entry) => entry.href === href),
).filter((entry): entry is SiteEntry => Boolean(entry));

export default function DeliberatePracticeGuitarPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        title={
          <>
            Deliberate practice,{" "}
            <em className="font-display italic text-peach">at the instrument.</em>
          </>
        }
        dek="One target you cannot hit yet, a difficulty where you keep missing, and something outside your own ear judging each attempt. Here is how to run that without a teacher in the room."
        updated="2026-08-29"
        related={RELATED}
      >
        <p>
          Deliberate practice on guitar means working on one thing you cannot
          yet play, at a difficulty where you keep failing, with something
          outside your own ear judging each attempt. Playing is what you do with
          material you already own. Deliberate practice is what you do with
          material you do not. Both belong in a week at the instrument, but only
          one of them is built to move what is currently out of reach.
        </p>

        <h2>Playing and practicing feel similar and are not</h2>

        <p>
          Sit down with a guitar and the default is playing. Your hands reach
          for the riff you always open with and the two songs you can get
          through without thinking. Nothing is wrong with that. It is most of
          why you own the instrument.
        </p>

        <p>
          Deliberate practice starts somewhere else. You name a failure, and you
          name it narrowly. Not “get better at barre chords.” The B-flat in the
          second verse buzzes on the third string every time you arrive from an
          open G. The second sentence is a target. The first is a mood.
        </p>

        <p>
          Three questions separate them, and you can answer all three about the
          hour you just finished:
        </p>

        <ul>
          <li>
            What was failing when you sat down, and is it still failing now?
          </li>
          <li>
            How many times did you stop mid-phrase because something was wrong?
          </li>
          <li>
            Could you have played most of that hour while thinking about
            something else?
          </li>
        </ul>

        <p>
          If nothing was failing, if you never stopped, and if your attention was
          free the whole time, you played. That is a legitimate way to spend an
          hour. It is just not the hour that moves the thing you are stuck on.
        </p>

        <h2>Feedback is the mechanism, not an extra</h2>

        <p>
          Repetition on its own does not sort good attempts from bad ones. It
          installs whatever you actually did, at whatever accuracy you actually
          did it. If your timing drifted late on every pass through a phrase and
          nothing told you, you rehearsed the drift. This is how practice can
          feel diligent and change nothing.
        </p>

        <p>
          A teacher is, mechanically, a feedback machine: a second set of ears
          that is not busy playing. You do not have one in the room, so you
          build that function out of parts you already have.
        </p>

        <h3>Record the attempt, then listen to it cold</h3>

        <p>
          Your ear while playing is occupied. It is running the next chord
          change, watching your fretting hand, and quietly forgiving you. Your
          ear on playback has none of those jobs and is much harder to fool.
        </p>

        <p>
          Record one take on your phone. Then listen for one thing only: was the
          timing steady, or was the chord clean, or was the bend in tune. One
          question per listen. The errors you hear on playback were mostly
          inaudible to you thirty seconds earlier, and that gap is the entire
          reason to record.
        </p>

        <h3>Let the metronome judge instead of accompany</h3>

        <p>
          Most players treat a click as a pacer to follow. Use it as a judge
          instead. Play the passage and pay attention to where you and the click
          separate, because that tells you which beat is actually causing the
          problem. Rushing into a hard bar and dragging out of it is a different
          diagnosis than being late the whole way through.
        </p>

        <p>
          A click on every beat hides small drift, since you get corrected four
          times a bar before the error can accumulate. Move the click to beats
          two and four, or to beat one only, and the drift becomes obvious. If
          you cannot hear yourself against it, the click is too quiet or the
          tempo is too fast.
        </p>

        <h3>Use a tool that reports something you cannot hear</h3>

        <p>
          Software that listens while you play can flag notes and timing you
          would argue with on your own. It does not know what you are trying to
          sound like, so it is not a replacement for your judgment. It is useful
          for the narrow question of whether what you played matches what you
          intended.{" "}
          <a href={STRUMLY.aiCoach}>
            Strumly&apos;s guide to practicing with an AI coach
          </a>{" "}
          is a longer read on where that fits into a session.
        </p>

        <h2>Work at the edge of what you can do</h2>

        <p>
          The edge is the level where you fail some of the time. Not most of the
          time, and not never.
        </p>

        <p>
          Below the edge you are playing. The attempts come out clean because
          they were always going to come out clean, and nothing about your
          playing had to change to produce them.
        </p>

        <p>
          Above the edge you are generating noise. When every attempt collapses,
          you cannot tell which one was closer, so there is nothing to correct
          toward. Practice above the edge feels like hard work and returns
          almost no information.
        </p>

        <p>
          The edge has a specific discomfort to it: you can nearly do the thing.
          You get it, lose it, and get it again. That instability is the point.
          It means the thing is still being built rather than already built or
          not yet started.
        </p>

        <p>
          Finding it is mechanical. Take the passage, drop the tempo until you
          can play it correctly twice in a row, then step up until it breaks.
          The speed just under the break is where the work happens. The{" "}
          <Link href="/tempo">tempo ladder builder</Link> does that arithmetic
          for you, but a metronome and a pencil do it just as well.
        </p>

        <p>
          The edge also moves. A tempo that was hard last week becomes a warm-up,
          which means practicing at last week&apos;s edge is playing. Re-find it
          every few sessions instead of assuming it stayed put.
        </p>

        <h2>It is meant to be short, and it is meant to be uncomfortable</h2>

        <p>
          Attention is the constraint here, not time. Deliberate practice asks
          you to hold a target in mind, notice a specific error, and change
          something on the next attempt. That kind of attention runs out well
          before your hands do.
        </p>

        <p>
          When it runs out, the session does not visibly fall apart. It degrades
          quietly. You keep repeating the passage, you stop catching the errors,
          and you start banking attempts at an accuracy you would not have
          accepted twenty minutes earlier. Stopping is the right move and also
          the hard one, because the guitar is still in your hands and the room is
          still quiet.
        </p>

        <p>
          The discomfort is not a virtue and it is not the goal. It is a location
          signal. A practice block that is entirely comfortable has drifted below
          the edge, which means you are playing. A block that is grim start to
          finish is above it.
        </p>

        <h2>Twenty deliberate minutes against two unfocused hours</h2>

        <p>
          The difference is not willpower or talent. It is how many attempts got
          judged.
        </p>

        <p>
          Two unfocused hours can contain hundreds of repetitions. Most of them
          are of material you already play, at a tempo you already own, and none
          of them were checked against anything. The four bars that are actually
          broken get a handful of passes on the way by, usually inside the whole
          song, usually at full speed, usually with the same error each time.
        </p>

        <p>
          Twenty deliberate minutes might contain thirty attempts. Each one is
          aimed at a single target, at a tempo where the outcome is in doubt, and
          each one is followed by a decision about what to change.
        </p>

        <p>Here is what those twenty minutes can look like:</p>

        <ol>
          <li>
            Two minutes: play the passage once at full speed and record it. That
            take is your before.
          </li>
          <li>
            Three minutes: listen back and name one error. Not three. One.
          </li>
          <li>
            Ten minutes: work at a tempo where that error shows up about half the
            time, changing one thing per attempt. A fingering, an anchor finger,
            where the shift starts, where you breathe.
          </li>
          <li>
            Three minutes: return to full speed and record the same passage
            again.
          </li>
          <li>
            Two minutes: write down what changed and what you will start with
            tomorrow.
          </li>
        </ol>

        <p>
          The two hours are not wasted. They are how songs get into your hands
          and how playing stays worth doing. But if a month of them has produced
          no change in the thing you cannot play, the missing ingredient is the
          twenty minutes rather than more hours. That is the usual shape of a{" "}
          <Link href="/guitar-practice-plateau">practice plateau</Link>.
        </p>

        <h2>What deliberate practice does not mean</h2>

        <ul>
          <li>
            <strong>Not more hours.</strong> It describes what a block of
            practice contains, not how long you sit with the guitar.
          </li>
          <li>
            <strong>Not drills instead of songs.</strong> A song is fine
            material. The deliberate part is what you do with the four bars of it
            that keep collapsing.
          </li>
          <li>
            <strong>Not a daily obligation.</strong> A short focused block a few
            times a week is deliberate practice. A daily streak of unfocused
            repetition is not.
          </li>
          <li>
            <strong>Not gear or software dependent.</strong> It needs a target, a
            tempo you can move, and a way to hear yourself back. A phone covers
            the third one.
          </li>
          <li>
            <strong>Not the whole session.</strong> Fifteen focused minutes
            followed by an hour of playing is a good session. Ninety minutes of
            half-attention is one long warm-up.
          </li>
        </ul>

        <h2>Where to point it</h2>

        <p>
          The method is useless without a target, and picking one is the part
          most players skip. If you are not sure where to aim, the{" "}
          <Link href="/diagnose">practice plateau diagnostic</Link> asks the
          questions that usually surface it. If you already know the target and
          want the structure that goes around the deliberate block,{" "}
          <Link href="/how-to-practice-guitar-effectively">
            how to practice guitar effectively
          </Link>{" "}
          covers the rest of the session, and{" "}
          <a href={STRUMLY.practiceRoutine}>
            Strumly&apos;s guide to designing a practice routine
          </a>{" "}
          covers the weekly shape around that.
        </p>

        <h2>Common questions</h2>

        {FAQ.map((item) => (
          <div key={item.q}>
            <h3>{item.q}</h3>
            <p>{item.a}</p>
          </div>
        ))}
      </Article>
    </>
  );
}
