import type { Metadata } from "next";
import Link from "next/link";
import Article from "@/components/Article";
import { GUIDES, OG_IMAGE, SITE_URL, STRUMLY } from "@/lib/site";

const CANONICAL = `${SITE_URL}/guitar-practice-schedule`;
const PUBLISHED = "2026-08-29";

const TITLE = "A Guitar Practice Schedule That Survives a Real Week";
const DESCRIPTION =
  "Daily guitar practice schedules collapse by Wednesday. Build the week around a minute total, one session you defend, and a cut order you decide in advance.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    // Required, not decorative: a page-level `openGraph` block replaces the
    // root layout's resolved object, taking the file-convention card with it.
    // See OG_IMAGE in lib/site.ts.
    images: [OG_IMAGE],
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Pulled from the route registry by href so titles and blurbs live in one
 * place. Listed explicitly rather than filtered, because the order below is a
 * reading order and not the registry's order.
 */
const RELATED_HREFS = [
  "/guitar-practice-routine-intermediate",
  "/method",
  "/30-day-guitar-challenge",
  "/how-to-practice-guitar-effectively",
] as const;

const RELATED = RELATED_HREFS.flatMap((href) =>
  GUIDES.filter((guide) => guide.href === href),
);

// Same @ids as app/layout.tsx, so this Article attaches to the Organization
// and Person nodes already declared there instead of minting duplicates.
const SUEDE_ORG_ID = "https://suedeai.ai/#organization";
const JASON_PERSON_ID = "https://suedeai.ai/founder#person";

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: TITLE,
      description: DESCRIPTION,
      // Google lists `image` as a recommended Article property, and without it
      // the page is not eligible for an Article rich result. Every route serves
      // the 1200x630 card generated by app/opengraph-image.tsx.
      image: "https://guitarhub.org/opengraph-image",
      datePublished: PUBLISHED,
      dateModified: PUBLISHED,
      inLanguage: "en-US",
      author: { "@id": JASON_PERSON_ID },
      publisher: { "@id": SUEDE_ORG_ID },
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
    },
  ],
};

export default function GuitarPracticeSchedulePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        title={
          <>
            A guitar practice schedule that{" "}
            <em className="font-display italic text-peach">
              survives a real week.
            </em>
          </>
        }
        dek="Built around a weekly minute total instead of a daily streak, with one session you defend, a cut order you decide in advance, and a ten-minute version that still does a job."
        updated={PUBLISHED}
        related={RELATED}
      >
        <p>
          A guitar practice schedule survives a real week when it is built
          around a weekly minute total instead of a daily streak. Pick a number
          of minutes you would hit in a bad week rather than a good one. Protect
          one anchor session at a fixed day and time and defend it the way you
          would defend a dentist appointment. Let every other session float.
          Decide in advance what gets cut when the week goes wrong, so that
          decision is not made at ten at night by whichever part of practice
          feels worst. Keep a ten-minute version that does one job properly.
          Then judge the week on whether the minutes landed on the thing you are
          trying to change — missed days included, because they happen in every
          real week and are not failure.
        </p>

        <p>
          The schedule that collapses on Wednesday usually collapsed on paper,
          before the week started. It was designed for the week you meant to
          have.
        </p>

        <h2>Why rigid daily schedules break</h2>

        <p>
          Thirty minutes every day at the same time describes what a settled
          practice looks like from the outside, which makes it a poor
          instruction for building one. Three things go wrong.
        </p>

        <p>
          <strong>It cannot represent a partial day.</strong> A schedule that
          only knows <em>practiced</em> and <em>did not practice</em> turns a
          fifteen-minute Tuesday into a miss, and being marked a failure for
          showing up is a reliable way to stop showing up.
        </p>

        <p>
          <strong>Every session is the same size.</strong> So the work that
          needs a long block — recording a full take, deciding what actually
          breaks, resetting a tempo ladder — never gets scheduled on purpose. It
          lands on whichever evening feels roomy, which is to say rarely.
        </p>

        <p>
          <strong>It fails all at once.</strong> Miss two days and the plan is
          no longer the plan you agreed to, and there is no defined way back
          into it. Most people do not resume a broken schedule. They wait for
          Monday, then for the first of the month.
        </p>

        <h2>Design the week around a total, not a streak</h2>

        <p>
          Replace <em>thirty minutes a day</em> with a weekly figure:{" "}
          <em>a hundred and fifty minutes this week</em>. The unit of the plan
          becomes the week, and the day becomes a place to put minutes. A
          skipped Tuesday is no longer a hole; it is minutes still on the table,
          and minutes can move. A streak cannot move — it can only break.
        </p>

        <p>
          Pick the number from evidence, not intention. Count what you actually
          did over the last three weeks, including the fifteen-minute evenings,
          and make the worst of the three your budget. A budget you clear is a
          schedule you keep. A budget set from your best week is the streak
          problem with extra arithmetic.
        </p>

        <p>
          Then make the sessions unequal on purpose. A hundred and fifty minutes
          might be one forty-five, two twenty-fives, and the rest in tens.
          Expensive work goes in the long session; cheap, repeatable work goes
          in the short ones.
        </p>

        <p>
          One rule keeps this from becoming an accounting exercise: minutes
          count only when they went to the thing you are trying to change.
          Twenty minutes playing what you already play well is a good evening,
          and it is not a deposit. Strumly&apos;s guide to{" "}
          <a href={STRUMLY.practiceRoutine}>designing a practice routine</a>{" "}
          covers what belongs inside the blocks once the week has a shape.
        </p>

        <h2>Protect one anchor session</h2>

        <p>
          An anchor is one session a week with a fixed day, a fixed time, and a
          job that justifies its length. Everything else floats around it. One
          anchor, not three: a second is not twice the protection, it is a
          session you feel guilty about.
        </p>

        <h3>Choosing the slot</h3>

        <ul>
          <li>
            <strong>Fewest dependencies wins.</strong> A slot that needs nobody
            else&apos;s cooperation survives more weeks than a better one that
            needs three people to hold their plans.
          </li>
          <li>
            <strong>Earlier than feels necessary.</strong> Sunday morning
            survives. Thursday at nine at night competes with a whole week of
            accumulated tiredness.
          </li>
          <li>
            <strong>Not against something you would rather do.</strong> A slot
            that makes you win an argument with yourself every week will
            eventually lose one.
          </li>
        </ul>

        <h3>What goes in it</h3>

        <p>
          The work that cannot be done in fragments. One full take of the piece,
          recorded and listened back. Naming the single repair target for the
          week. Setting or resetting a{" "}
          <Link href="/tempo">tempo ladder</Link> for the passage that is
          failing. Anything that needs a run-up, or that produces a decision the
          short sessions spend the week executing.
        </p>

        <p>
          The rule that makes it an anchor: if exactly one session happens this
          week, it is this one. Which means when Wednesday comes under threat,
          you do not move the anchor to cover it. You let Wednesday go.
        </p>

        <h2>Decide the cut order before you need it</h2>

        <p>
          At ten at night on a bad Wednesday you will cut whatever is least
          pleasant, and that is almost always the repair work — the one part
          that changes your playing. So the order gets decided in daylight, once.
        </p>

        <ol>
          <li>
            <strong>New material goes first.</strong> Starting a new song is the
            most expensive item in the week and the least urgent. It is also
            the hardest to give up, because opening something new feels like
            progress.
          </li>
          <li>
            <strong>Then the long warm-up.</strong> Keep two minutes of it. A
            warm-up is a ramp onto the work; a twelve-minute one has quietly
            become the session.
          </li>
          <li>
            <strong>Then full run-throughs.</strong> A run-through is
            measurement, and measurement is expensive in minutes. One a week is
            enough to see whether the repair is holding.
          </li>
          <li>
            <strong>Then volume on the repair target</strong>, but never the
            target itself. Six attentive repetitions beat twenty distracted
            ones, and six fit inside a short session.
          </li>
        </ol>

        <p>
          Two things never get cut: the anchor session, and the recording that
          makes the month comparable at the end.
        </p>

        <p>
          Writing the order down means a bad week produces a smaller version of
          the same plan instead of a different plan. That is the whole trick.
          Plans rarely die of one bad week. They die of being improvised four
          weeks in a row.
        </p>

        <h2>Make a ten-minute day count</h2>

        <p>
          A ten-minute session is not a compressed full session. It is one job,
          chosen before you sit down. If you sit down and then decide what to
          work on, the deciding is the session.
        </p>

        <ul>
          <li>
            <strong>One minute:</strong> tune and settle. Not a ritual.
          </li>
          <li>
            <strong>Six minutes:</strong> the named fragment — the smallest
            piece that still fails — at a tempo where you play it correctly on
            purpose rather than correctly by luck.
          </li>
          <li>
            <strong>Two minutes:</strong> play it with the bar before and the
            bar after, so the repair is attached to something instead of
            floating.
          </li>
          <li>
            <strong>One minute:</strong> write down the tempo you reached and
            where you stopped.
          </li>
        </ul>

        <p>
          That last minute is what lets ten-minute days accumulate. Without it,
          the first five minutes of the next session go to finding your place
          again, so a ten-minute day costs fifteen and returns five. With it,
          the next session opens with the answer already written.
        </p>

        <p>
          Turning a fixed number of minutes into blocks with distinct jobs is
          its own problem, and{" "}
          <Link href="/how-long-to-practice-guitar-each-day">
            how long to practice each day
          </Link>{" "}
          covers it. The{" "}
          <Link href="/guitar-practice-routine-intermediate">
            intermediate practice routine
          </Link>{" "}
          lays out that structure in a twenty-five and a fifty-minute version,
          the two sizes most weeks are made of.
        </p>

        <h2>Missed days are part of the plan</h2>

        <p>
          You will miss days. Work, illness, family, travel, and plain flatness.
          A schedule that treats those as anomalies will be wrong most weeks,
          and a plan that is wrong most weeks stops being consulted.
        </p>

        <p>
          Take the same week under both designs: you practice on four days out
          of seven and the minutes add up to what you intended. Under a daily
          schedule that is three failures. Under a weekly total it is a
          completed week. Same playing, two verdicts, and only one is still in
          use next Monday.
        </p>

        <p>
          A streak also gets more expensive the longer it runs, so a single
          break starts to feel like an ending rather than a Tuesday. A weekly
          total has nothing to break; its worst outcome is a week under budget,
          which is a number and not a verdict on you. The only miss that costs
          you the month is the one you convert into a decision to stop.
        </p>

        <h2>Restarting after a week you missed</h2>

        <p>
          Do not start the plan over. It is the most expensive response to a
          cheap event, and it resets the thing that took real work to build:
          knowing exactly what is broken and how slowly you have to play it.
          Assume the week cost you some tempo and none of the diagnosis.
        </p>

        <ol>
          <li>
            <strong>Keep the goal.</strong> A missed week is the worst moment to
            choose a new finish line. The new one looks exciting and the old one
            now smells of failure, which is a feeling about last week rather
            than a fact about the goal.
          </li>
          <li>
            <strong>Re-take the last thing you were working on, cold.</strong>{" "}
            Write down the tempo. It will be lower than where you left off. That
            is information about where to start, not a judgment.
          </li>
          <li>
            <strong>Drop the ladder a few steps, not to the bottom.</strong>{" "}
            Climb from the tempo you just measured, not the one you remember.
          </li>
          <li>
            <strong>Repeat the last week you completed</strong>, not the week
            the calendar says you are on. A repeated week costs seven days. A
            restart costs the month.
          </li>
          <li>
            <strong>Do not double next week to catch up.</strong> A double week
            is a heavy week, a heavy week fails on Wednesday, and that
            manufactures the second missed week.
          </li>
        </ol>

        <p>
          It is also why a month of practice is counted in weeks of the plan
          rather than consecutive calendar days. The{" "}
          <Link href="/30-day-guitar-challenge">30-day guitar challenge</Link>{" "}
          is judged on two recordings of the same thing under the same
          conditions. A missed week moves the second date; it does not void the
          first recording.
        </p>

        <h2>What this looks like on paper</h2>

        <p>
          One week at a hundred and fifty minutes, for a player working on a
          single failing passage.
        </p>

        <ul>
          <li>
            <strong>Sunday, 45 minutes — the anchor.</strong> Full take,
            recorded and listened back. Name this week&apos;s repair target. Set
            the tempo ladder for it.
          </li>
          <li>
            <strong>Tuesday, 25 minutes.</strong> Repair target, climbing the
            ladder. No run-through.
          </li>
          <li>
            <strong>Thursday, 25 minutes.</strong> Repair target, then reconnect
            it to the section around it.
          </li>
          <li>
            <strong>Two floating tens.</strong> The ten-minute template, on
            whichever two days actually exist.
          </li>
          <li>
            <strong>One open 35.</strong> Repertoire, new material, or a session
            that got missed. Deliberately the largest block and first on the cut
            list, so a bad week has somewhere to take its losses.
          </li>
        </ul>

        <p>
          The bad-week version is the anchor cut to thirty minutes, two tens,
          and nothing else: seventy minutes, still pointed at the same passage,
          still ending with a tempo written down. The same plan at a smaller
          size, which is the property that matters.
        </p>

        <h2>The schedule is only a container</h2>

        <p>
          A week with good structure and nothing worth putting in it is still
          wasted. The schedule decides when you practice and how the week
          absorbs damage. What goes inside comes from a diagnosis: one finish
          line, one thing that breaks, one repair target at a time.
        </p>

        <p>
          The <Link href="/breakthrough">30-day breakthrough planner</Link>{" "}
          turns one goal into four weeks and names the evidence each week has to
          produce — the material this schedule carries. It needs no account. If
          the harder question is what to work on rather than when,
          Strumly&apos;s guide to{" "}
          <a href={STRUMLY.aiCoach}>practicing guitar with an AI coach</a>{" "}
          covers turning a vague sense that something is off into a specific
          answer.
        </p>

        <p>
          Build the week from the worst version of itself. A schedule that only
          works on a good week has not been tested against the only kind of week
          you reliably get.
        </p>
      </Article>
    </>
  );
}
