import type { Metadata } from "next";
import Link from "next/link";
import { Fragment } from "react";
import Article from "@/components/Article";
import { breadcrumbList, crumbTrail } from "@/lib/breadcrumbs";
import {
  ARTICLE_AUTHOR,
  GUIDES,
  LEARN,
  SITE_URL,
  TOOLS,
  type SiteEntry,
} from "@/lib/site";
import { keywordsFor, keywordsText } from "@/lib/keywords";

const CANONICAL = `${SITE_URL}/record-guitar-practice-on-phone`;
const PUBLISHED = "2026-10-10";
const UPDATED = "2026-10-10";

const HEADLINE = "How to record your guitar practice on a phone";

const DESCRIPTION =
  "Record guitar practice on your phone: where to put it, how to set the level, how to run a day 1 versus day 30 comparison, and the five things to listen for.";

/** Read by both the visible trail and the BreadcrumbList node below. */
const CRUMBS = [
  ...crumbTrail("Guides", "/guides"),
  { name: "Record your practice on a phone", href: "/record-guitar-practice-on-phone" },
];

export const metadata: Metadata = {
  keywords: keywordsFor("/record-guitar-practice-on-phone"),
  title: "How to Record Your Guitar Practice on a Phone | GuitarHub",
  description: DESCRIPTION,
  openGraph: {
    title: HEADLINE,
    description: DESCRIPTION,
    url: CANONICAL,
    siteName: "GuitarHub",
    type: "article",
    publishedTime: PUBLISHED,
    // No `images` key: Next attaches the colocated opengraph-image.tsx card
    // only when the page leaves `images` unset.
  },
  alternates: { canonical: CANONICAL },
};

/**
 * Defined once and used twice: rendered as the visible Q&A at the foot of the
 * article and serialized into the FAQPage node, so the two cannot drift.
 */
const FAQS = [
  {
    q: "Should I record audio or video?",
    a: "Video, when you can. Landscape video with both hands in frame gives you the audio and shows why a note failed: a finger lifting too early, a thumb clamping, a wrist folding. Audio alone is enough for checking time and clean notes, and it is quicker to listen to.",
  },
  {
    q: "Do I need an external microphone?",
    a: "No. For practice evidence, the phone's built-in microphone is enough, as long as the placement and level stay the same from take to take. An external microphone improves the sound, and you can add one later without changing anything else in this routine.",
  },
  {
    q: "How often should I record my practice?",
    a: "One short take at the end of most sessions, and one full baseline-style take every 30 days. The short takes catch problems while they are small. The monthly takes, recorded the same way each time, are the ones you compare.",
  },
  {
    q: "Should the metronome be audible on the recording?",
    a: "For timing checks, yes, quietly. A click you can hear on playback lets you hear exactly where you rush or drag. For the monthly comparison, record a count-in and then play without the click, so you can hear whether your own time holds.",
  },
] as const;

const ENTRY_BY_HREF = new Map<string, SiteEntry>(
  [...TOOLS, ...GUIDES, ...LEARN].map((entry) => [entry.href, entry]),
);

const RELATED: readonly SiteEntry[] = [
  "/method",
  "/readiness",
  "/30-day-guitar-challenge",
  "/log",
]
  .map((href) => ENTRY_BY_HREF.get(href))
  .filter((entry): entry is SiteEntry => entry !== undefined);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": `${CANONICAL}#article`,
      headline: HEADLINE,
      description: DESCRIPTION,
      keywords: keywordsText("/record-guitar-practice-on-phone"),
      // Google lists `image` as a recommended Article property. Every route
      // serves the 1200x630 card generated by app/opengraph-image.tsx.
      image: `${CANONICAL}/opengraph-image`,
      datePublished: PUBLISHED,
      dateModified: UPDATED,
      inLanguage: "en-US",
      url: CANONICAL,
      mainEntityOfPage: { "@type": "WebPage", "@id": CANONICAL },
      isPartOf: { "@id": "https://guitarhub.org/#website" },
      author: ARTICLE_AUTHOR,
      publisher: { "@id": "https://suedeai.ai/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": `${CANONICAL}#faq`,
      mainEntity: FAQS.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
    breadcrumbList(CANONICAL, CRUMBS),
  ],
};

export default function RecordGuitarPracticeOnPhonePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />

      <Article
        guideHref="/record-guitar-practice-on-phone"
        crumbs={CRUMBS}
        title={
          <>
            Record your practice on a phone, and{" "}
            <em className="font-display italic text-peach">hear what changed.</em>
          </>
        }
        dek="The phone in your pocket is the most useful practice tool you own. Set it up once, record the same way every time, and every take becomes evidence."
        updated={UPDATED}
        related={RELATED}
      >
        <p>
          To record your guitar practice on a phone, put the phone about an arm&apos;s length in front of the guitar, pointed at the spot where the neck joins the body, with the end that holds its microphone toward the guitar. Set the level by playing your loudest part first and moving the phone back if it distorts. Then keep everything the same for every take: the spot, the distance, the room, the passage and the tempo. Record a full take on day 1 and the same take on day 30, listen to them back to back, and score both against the same five things: time, clean notes, changes, dynamics, and stops.
        </p>

        <p>
          This page is about recording as practice evidence: takes you compare
          to measure progress. For how a recording space shapes your guitar
          sound, see <Link href="/resources/recording-guitar-room-sound">how to hear the room in a guitar recording</Link>.
        </p>

        <h2>Why a recording beats your memory</h2>

        <p>
          While you play, your attention is on the next chord, not on the last
          one, and you hear the guitar from behind it, through your own body. A
          recording puts you in the audience. The rushed change, the buzzing
          string and the gap before the chorus are obvious on playback and
          nearly invisible in the moment.
        </p>

        <p>
          A recording also fixes the comparison problem. Memory of how you
          sounded a month ago drifts toward how you sound now, so progress
          disappears. Two takes recorded the same way do not drift. That is why
          the <Link href="/method">GuitarHub method</Link> starts and ends on a recording: the <strong>baseline</strong> stage is a take that shows where the playing breaks, and the <strong>prove</strong> stage is the same take a month later. The isolate and reconnect stages in between are the work the two takes measure.
        </p>

        <h2>Set up once, then never change it</h2>

        <p>
          A comparison only works when the only thing that changed is your
          playing. Decide the setup once and write it down.
        </p>

        <ul>
          <li>
            <strong>Acoustic guitar.</strong> Phone about 60 to 90 centimeters
            (two to three feet) in front of the guitar, at the height of the
            neck joint, angled toward where the neck meets the body. Pointing
            straight into the sound hole gives a boomy, bass-heavy take.
          </li>
          <li>
            <strong>Electric guitar through an amp.</strong> Phone about 30 to
            60 centimeters (one to two feet) in front of the speaker, at a volume
            you would practice at anyway. A loud amp right next to the phone
            distorts the microphone.
          </li>
          <li>
            <strong>Video.</strong> Landscape, on a stand or propped on a shelf,
            far enough back that both hands and the whole neck are in frame. You
            will learn as much from watching the hands as from listening.
          </li>
          <li>
            <strong>Mark the spot.</strong> A strip of tape on the floor or the
            shelf for the phone, and the same chair in the same place. Same room,
            and the same guitar if you have more than one.
          </li>
          <li>
            <strong>Silence the phone.</strong> Turn on Do Not Disturb or
            airplane mode before you record, so a notification does not land in
            the middle of your best take.
          </li>
        </ul>

        <h2>Get the level right</h2>

        <p>
          Most phone recording apps adjust the input level automatically and
          offer few manual controls, so distance is your level control. Before
          the first take:
        </p>

        <ol>
          <li>
            Record ten seconds of the loudest thing you will play, usually a
            hard strum.
          </li>
          <li>
            Play it back. If it crackles or sounds squashed, move the phone back
            and try again. If you can barely hear quiet notes, move it closer.
          </li>
          <li>
            If the app shows a waveform, the loudest strums should come close to
            the edges without flattening against them.
          </li>
          <li>
            In the app&apos;s settings, choose the highest quality or lossless
            option if there is one, and switch off any noise-reduction or
            enhancement feature. Those features are built for speech and can
            smear note attacks and room sound.
          </li>
        </ol>

        <p>
          Once the distance is right, it stays. Changing it between takes changes
          the sound more than a month of practice changes your playing.
        </p>

        <h2>What to record</h2>

        <p>
          The comparison take is one passage, start to finish, at a tempo you
          would actually attempt, with no restarts. A restart is information:
          leave it on the recording. Before you play, say the date, the passage
          and the tempo out loud, for example &ldquo;Day 1, verse and chorus,
          72 BPM.&rdquo; Then play a count-in on the <Link href="/practice">metronome</Link> and go.
        </p>

        <p>
          Choose a passage you will still be working on in a month, ideally the
          part of a song you want to finish. If you are not sure which part, the <Link href="/readiness">song readiness score</Link> points at the sections most likely to break.
        </p>

        <p>
          Between monthly takes, record one short take at the end of most
          sessions: thirty seconds of whatever you worked on. These catch
          problems while they are still small, and they show you whether the
          session&apos;s fix survived the end of the session.
        </p>

        <h2>The day 1 versus day 30 comparison</h2>

        <ol>
          <li>
            <strong>Record day 30 exactly like day 1.</strong> Same spot, same
            distance, same passage, same tempo, same count-in. Record it before
            you warm up on the passage, so it shows what you can do cold.
          </li>
          <li>
            <strong>Listen to day 1 once, all the way through.</strong> Write
            down the timestamp of every stop, stumble and buzz.
          </li>
          <li>
            <strong>Listen to day 30 once, the same way.</strong> Same notes,
            same timestamps.
          </li>
          <li>
            <strong>Play the hardest bar from each take back to back.</strong>{" "}
            This is where the change is easiest to hear.
          </li>
          <li>
            <strong>Score both takes on the five checks below</strong>, then
            write one sentence naming what improved and one naming what still
            breaks. The second sentence is next month&apos;s target.
          </li>
        </ol>

        <p>
          The <Link href="/log">practice evidence log</Link> is a good place for those two sentences and the tempo. If you are running a month toward one finish line, the <Link href="/30-day-guitar-challenge">30-day guitar challenge guide</Link> covers how to judge the day 30 take, and the <Link href="/breakthrough">30-day breakthrough planner</Link> sets the four weeks in between.
        </p>

        <h2>What to listen for: five checks</h2>

        <ul>
          <li>
            <strong>Time.</strong> Does the beat stay steady, especially at
            chord changes and the start of new sections? Rushing into a hard
            part and slowing down inside it are the classic timing faults. A quiet click on the recording makes both easy to hear.
          </li>
          <li>
            <strong>Clean notes.</strong> Count the buzzes, dead strings and
            notes that ring when they should be muted.
          </li>
          <li>
            <strong>Changes.</strong> Listen to the gap before each new chord.
            A clean change sounds continuous. A late one leaves a hole or a
            stretched beat.
          </li>
          <li>
            <strong>Dynamics.</strong> Does the chorus get louder than the
            verse, or does everything sit at one volume? Playing with dynamics
            on purpose is part of sounding like music.
          </li>
          <li>
            <strong>Stops and recoveries.</strong> Count the stops. Then listen
            to how you recover from a mistake: a recovery that keeps the beat is
            a skill, and it improves with practice like any other.
          </li>
        </ul>

        <p>
          With video, add a sixth check: the hands. Look for fingers lifting
          far off the strings, a thumb pressing hard behind the neck, shoulders
          rising, and the moment your eyes drop to the fretboard. Those usually
          sit right before the problem you heard.
        </p>

        <h2>File it so you can find it</h2>

        <p>
          Name each take with the date, the piece, the tempo and the day number,
          for example <code>2026-10-10 verse-chorus 72bpm day01</code>, and keep
          them in one album or folder. The recordings stay on your phone. Nothing
          needs to be uploaded or shared for any of this to work, so you can be
          as rough as you need to be on day 1.
        </p>

        <h2>Questions that come up</h2>

        {FAQS.map((faq) => (
          <Fragment key={faq.q}>
            <h3>{faq.q}</h3>
            <p>{faq.a}</p>
          </Fragment>
        ))}
      </Article>
    </>
  );
}
